### ISSUE TITLE
GetMediaLikers returns only 1000 likers

### ISSUE THREAD

**Issue by wynnwynn** [LevPasha/Instagram-API-python#102]
Hello,

This is my first post in GitHub, pardon me if i am posting it wrongly.

I have been trying to extract the full list of likers for a particular post, however the function only returns 1000 likers.

Is there any way i get get the full list?

thanks!

Wynn

**Comment by LevPasha** [comment]
@wynnwynn i don't sure, but i think this requst return something like "last_media" or "endpoint". And you should add this to next request. Try to find it in php lib.

**Comment by onemanarmy8** [comment]
its imposible to get more then 1000 likers

**Comment by anupamaa** [comment]
The GetMediaLikers function is only returning True or False. What is the correct way to get the actual list of likers for a given media ID?

**Comment by wynnwynn** [comment]
```
    InstagramAPI.getMediaLikers("media_id")
    info = InstagramAPI.LastJson
    print info
```
this should return in JSON format for parsing.

**Comment by artas728** [comment]
Hi Everyone
So, someone has solved the problem with 'getMediaLikers'? how to get if the likes of more than 1000?
Thanks

**Comment by wynnwynn** [comment]
artas728, there is no way to get more than 1000 as instagram only provides the latest 1000 likers.

**Comment by Ronaldomata34** [comment]
Hi! does somebody know how to solve it?

**Comment by wynnwynn** [comment]
It is the limitation of the api, it can't be changed

**Comment by Ronaldomata34** [comment]
some alternative? with other API, Do you know?

**Comment by arthur-barsegyan** [comment]
@Ronaldomata34 yeah, this library https://github.com/rarcega/instagram-scraper

**Comment by Ronaldomata34** [comment]
Thanks so much @arthur-barsegyan

**Comment by danielb1234** [comment]
Hey @arthur-barsegyan used the instagram-scraper but can't find a way to get media total likers, could you give some advice? Thanks

**Comment by arthur-barsegyan** [comment]
@danielb1234 I think a made a mistake in the last comment :) As I know, after the last Instagram API updates we can't get all media likes uses public API
