### ISSUE TITLE
How to keep logged in during developing?

### ISSUE THREAD

**Issue by skyberry333** [LevPasha/Instagram-API-python#103]
During the developing phase, I need to test the program multiple times which might causes temporary ban on the account due to frequent log in. Is there anyway to keep the login session?

**Comment by LevPasha** [comment]
Save this and and restore:
```python
                    'token': IG.token,
                    'username_id': IG.username_id,
                    'rank_token': IG.rank_token,
                    'uuid': IG.uuid,
                    'session': IG.s.cookies.get_dict(),
                    'user_agent': IG.USER_AGENT,
                    'device_id': IG.device_id
```
```python
            for (key, value) in f['session'].items():
                IG.s.cookies.set(key, value)
```
work fine to me.

**Comment by skyberry333** [comment]
@LevPasha  Thanks!

**Comment by tarun7singh** [comment]
@LevPasha @skyberry333 were you successful in keeping yourself logged in? please show me the code for it in detail. I can't understand what you really understand what you said above about saving and restoring. I am a beginner here. 
Thanks
