### ISSUE TITLE
GetUserFollowing paginating not working

### ISSUE THREAD

**Issue by alex-nishikawa** [LevPasha/Instagram-API-python#104]
The response to get "following" appears to always return the same "following" users.  Even when passing in the `next_max_id`

**Comment by rsxgti** [comment]
How to you pass in the next_max_id?

**Comment by alex-nishikawa** [comment]
@rsxgti 
It was a bug on Instagram's end.  Even the Instagram app scrolled forever.  It's fixed today.

**Comment by snenkov** [comment]
A quick question: how are you using the next_max_id pagination? Could you provide a code example please?

**Comment by jockonarock** [comment]
@snenkov 

Hey. I am also quite new to Instagram API, but after reading the API file, I kinda figured out that the max id is actually an argument that needs to be passed into the API method. So the default max id ='' would only fetch you the first 200 followers (for example), to retrieve the next 200, you need to update your max id to the next_max_id given by the JSON response file from your first request. And then you run your API method again with the new max id.

I have attached some of my code below for your reference.

Hope it helps

```
userid = 46123599xx
maxid = ''
has_more_value = True

while has_more_value == True:
	API.getUserFollowers(userid, maxid) #(userid,maxid)
	for i in API.LastJson['users']:
		followerlist.append(i['pk'])
	if API.LastJson['big_list'] == False:
		break
	maxid = API.LastJson['next_max_id']
	time.sleep(1)

**Comment by Haydardi** [comment]
@jockonarock 
Hey man, how the heck did you get the next_max_id, i keep getting an error saying "Key Error: 'next_max_id':
`Traceback (most recent call last):
  File "C:\Users\hayda\Dropbox\1.Instagram\Bot\3.Find Users\Check User Tags.py", line 75, in getUserFollowers
    max_id = InstagramAPI.LastJson['next_max_id']
KeyError: 'next_max_id`

And here's my code:
`followerCount = theUser['follower_count']
max_id = ''
    next_max_id = True
    try:
        while next_max_id:
            InstagramAPI.getUserFollowers(user_id, max_id)
            temp = InstagramAPI.LastJson
            for item in temp["users"]:
                if followerCount > len(followers):
                    followers.append(item['username'])
                else:
                    next_max_id = False
            max_id = InstagramAPI.LastJson['next_max_id']
            print(max_id)
            sleep(2)`

The account I'm fetching followers from has more than 35k followers. Am I missing something?
