### ISSUE TITLE
get Total Followers/Followings

### ISSUE THREAD

**Issue by gcrevell** [LevPasha/Instagram-API-python#106]
Get total users doesn't seem to get new users with each iteration. Each loop, when the "next_max_id" key is supposed to be used to get the next group of users, it gathers the same users. It seems the next_max_id value doesn't work to select the next set of users. Both functions work fine if the user has small enough numbers to have big_list in the return be false. 

Can you explain how the functions are supposed to work and what I'm doing wrong or look into why they don't work anymore?

Thanks.

My code:

```
api = InstagramAPI("UNAME", "PWORD")
api.login()
api.getTotalFollowings(296348895)
# The above line is the one with the issue. Each iteration of the while loop in getTotalFollowings 
# gets the same set of followers. It also loops infinitely because it never reaches the end.
```

**Comment by diegofcoelho** [comment]
I am not sure if makes nay difference, but here I submit userId as String.

Cheers

**Comment by gcrevell** [comment]
No. After a bit more research it seems instagram limits the number of followers and followings their API delivers and you can't get the next set. So I just made do. Thanks.

**Comment by diegofcoelho** [comment]
Here it seems okay when following number is bellow 30k.  Whilst all users are collected up to that number, Instagram start denying requests around that.

However, I would advise inserting some protection mechanism to force the api pause a random interval every other minute to guarantee Instagram won't detect a bot behaviour and deny user requests. Maybe that can solve you probably.. who knows..

I am planning to modify my forked version to such situation.

**Comment by wynnwynn** [comment]
There is a limit to the number of times one can call the api. From experience it requires a 15 minutes break after 200 api calls. So you probably would like to set a 15 minutes sleep after 200 calls.

**Comment by aReaSa** [comment]
@wynnwynn how can i set a sleep after calling? if i run getUserFollowers(has10kfollower) command it tries all list and my pc freeze...

**Comment by diegofcoelho** [comment]
@aReaSa You will need to modify the api and write the pause between requests. Use some convenient conditional and call a `time.sleep(TIMEinSECONDS)`. If you give a proper look into the function, you can see that LevPasha wrote it in a way that sequential requests are made until no new entries are added.
