### ISSUE TITLE
NeedDownloadError when trying to upload photo

### ISSUE THREAD

**Issue by absint0o** [LevPasha/Instagram-API-python#107]
Hi there,
i'm trying to upload a photo in my instagram account but withou success, i'm getting this error:

![sem titulo](https://cloud.githubusercontent.com/assets/13877015/22864757/f06090fa-f14e-11e6-8d1d-0724870a8cd6.png)

Can anyone help me please?
thank you very much!!!

**Comment by rensakamoto** [comment]
try `brew install ffmpeg`

**Comment by absint0o** [comment]
i have windows, windows does not have brew i think

**Comment by absint0o** [comment]
any idea on why this appends?
thank you very much!

**Comment by absint0o** [comment]
resolved the issue. just have to download manualy the ffmpeg and download it to a folder in c:\, then add the path c:\ffmpeg\bin to the paths system environment
