### ISSUE TITLE
uploadVideo() does not work

### ISSUE THREAD

**Issue by rsxgti** [LevPasha/Instagram-API-python#108]
uploadVideo() does not work. Anyway to upload videos?

**Comment by thedangler** [comment]
I concur, I get login success and it seems like it works but then check IG and nothing there.

**Comment by PKostya** [comment]
upload video work:
1.download video and image from post 
2.
```
thumbnail_local_path=download_file(data[0][1])
video_local_path = download_file(data[0][0])
api.uploadVideo(video =video_local_path, thumbnail= thumbnail_local_path,  caption=tags) 

```
