### ISSUE TITLE
how to use this api

### ISSUE THREAD

**Issue by amk11** [LevPasha/Instagram-API-python#11]
Hi, I was using your previous bot userinfo.py but that stopped working and now i tried to create my code for this api bot but i don't know how to. I want to convert the code below to use the latest api

ui.search_user(user_id="") 
   ui.get_followers(limit=10)
   for f in ui.followers:
                  bot.follow(f["id"])

**Comment by LevPasha** [comment]
@amk11 repeat my question here. You solve it?

**Comment by 179skr** [comment]
Nope i dont know how to use this api.

**Comment by h-2-0** [comment]
@amk11, @179skr 

I also didn't know how to use it but I looked at the test.py file and found some clues.

**Comment by drewhga** [comment]
@h-2-0 
How were you able to get it running

**Comment by h-2-0** [comment]
Well, it's rather simple. The test file show us how to log in:

```from InstagramAPI import InstagramAPI

InstagramAPI = InstagramAPI("login", "password")
InstagramAPI.login() # login```

And from there you do whatever you want to do based on the available AND active functions found in the InstagramAPI.py file. Good luck!

**Comment by h-2-0** [comment]
Well, it's rather simple. The test file show us how to log in:

```from InstagramAPI import InstagramAPI

InstagramAPI = InstagramAPI("login", "password")
InstagramAPI.login() # login```

And from there you do whatever you want to do based on the available AND active functions found in the InstagramAPI.py file. Good luck!

**Comment by h-2-0** [comment]
Well, it's rather simple. The test file show us how to log in:

```from InstagramAPI import InstagramAPI

InstagramAPI = InstagramAPI("login", "password")
InstagramAPI.login() # login```

And from there you do whatever you want to do based on the available AND active functions found in the InstagramAPI.py file. Good luck!

**Comment by h-2-0** [comment]
Well, it's rather simple. The test file show us how to log in:

```from InstagramAPI import InstagramAPI

InstagramAPI = InstagramAPI("login", "password")
InstagramAPI.login() # login```

And from there you do whatever you want to do based on the available AND active functions found in the InstagramAPI.py file. Good luck!

**Comment by h-2-0** [comment]
Well, it's rather simple. The test file show us how to log in:

```from InstagramAPI import InstagramAPI

InstagramAPI = InstagramAPI("login", "password")
InstagramAPI.login() # login```

And from there you do whatever you want to do based on the available AND active functions found in the InstagramAPI.py file. Good luck!

**Comment by drewhga** [comment]
So can I run it on python 2.7?

**Comment by 179skr** [comment]
@h-2-0 How would you pull someone's latest followers like 100 and follow each follower? Ive tried everything but nothing works.

**Comment by h-2-0** [comment]
@drewhga 
 
I'm using Python 3.4. I started using the Instagram-API-python with Python2.7 but for some reason which I can't remember I had to switch to 3.4. In my own personal notes I have that 'It requires python 3.4"

**Comment by h-2-0** [comment]
@drewhga 

I haven't used the Instagram-API-python for a few days but this is how I was getting followers:
```
InstagramAPI.getUserFollowers(target_id, next_max_id)
temp = InstagramAPI.LastJson
temp['users'][0] # this gets the latest follower
``` 
Problem is/was that I couldn't get past the first 100 latest followers (i.e. pagination. I actually reported the issue here). But if you only want the last 100 followers you shouldn't have any problem. 

I haven't checked how to follow yet.

**Comment by drewhga** [comment]
@h-2-0
Well, I'd love to run it on python 2.7 so I can run it on my phone. I use
qpython for android so I'm able to monitor the bot's progress. Any idea on
a python 3.4/5 client for android?. Thanks btw

**Comment by h-2-0** [comment]
@drewhga 

I don't know of any python 3.4 for android, sorry.

**Comment by drewhga** [comment]
😖😖

**Comment by amk11** [comment]
Thanks @h-2-0 

Now i just need to figure out how to follow said list and i should be good. 


@drewhga i would recommend running it on a pc. The script will drain your android phones battery

**Comment by amk11** [comment]
@h-2-0 

If you do figure out how to follow people from temp['users'][0] please let me know. i am a complete noob when it comes to python. Thanks for all your help :+1:

**Comment by 179skr** [comment]
So im guessing no one knows how to follow using the api?
