### ISSUE TITLE
test.py throws an error "Need ffmpeg exe"

### ISSUE THREAD

**Issue by dleybz** [LevPasha/Instagram-API-python#111]
Screenshot attached

![image](https://cloud.githubusercontent.com/assets/7946482/23146568/cc4f65b2-f78c-11e6-97b6-33636adfa3d6.png)

**Comment by b3mb4m** [comment]
Same problem here, ubuntu 14.04.

**Comment by YuriyOrlov** [comment]
I had the same problem (Ubuntu 16.04). You have to run python terminal and 
```
>>> import imageio
>>> imageio.plugins.ffmpeg.download()
```
This means, that your Linux distro has no proper codec.

**Comment by lotusrs** [comment]
try install ffmpeg.

` sudo apt-get install ffmpeg`

**Comment by dleybz** [comment]
Is this API only for Ubuntu machines? What's the fix for Windows?
