### ISSUE TITLE
Logging in takes roughly 10 minutes

### ISSUE THREAD

**Issue by Kreh21** [LevPasha/Instagram-API-python#112]
When I try to login to the API or call a method it takes a very long time to load. It was working normally a few days ago. Anyone else having this issue?

**Comment by dsouzarc** [comment]
I don't have this issue - it takes roughly 2-4 seconds to login and make subsequent API calls

**Comment by onemanarmy8** [comment]
Maybe you have bad subnet\proxy ?

**Comment by Kingson** [comment]
Check your network and try login instagram app.
