### ISSUE TITLE
Saving logged in state during development?

### ISSUE THREAD

**Issue by tarun7singh** [LevPasha/Instagram-API-python#115]
I tried the method described by @LevPasha in issue #103. 
I am able to save values in a local JSON file.
but while trying to restore previous session in a new python session. i am getting following error.

```
for (key, value) in f['session'].items():
    IG.s.cookies.set(key, value)

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
AttributeError: class InstagramAPI has no attribute 's'

```

**Comment by tarun7singh** [comment]
@lotusrs I don't want to login again and again. I've saved values after logging in once. Now i want it to use values such as cookies etc. from previous login.
As describe in issue #103 check it you will understand what i want to do more.

**Comment by diegofcoelho** [comment]
Did you check Json integrity?

**Comment by tarun7singh** [comment]
Yes, @diegofcoelho JSON is valid. it passes as valid Json at [http://jsonlint.com/](Here).
And are you able to login from previously saved values?

**Comment by diegofcoelho** [comment]
Sorry, I might have understood wrong when I read it before.. You saved session details and want to restore the session itself or load saved data from previous requests?

**Comment by tarun7singh** [comment]
@diegofcoelho My mistake, maybe i was not clear enough. I want to restore the session itself. so that i don't have to login every time ( which may lead to temporary ban ) from Instagram. I have already saved session values (device_id, token, session etc.) in a json file but i am having problems in restoring them.

**Comment by diegofcoelho** [comment]
Okay, now I got it. I am afraid I can't help with it but from personal experience, you would need a crazy amount of requests/logins to get a proper ban.

I am preaching around that InstagramAPI itself should hold a few random time.sleep() resting points.. That solved most of problems around here..

Cheers
