### ISSUE TITLE
test.py throws an error "Need ffmpeg exe" (Windows)

### ISSUE THREAD

**Issue by dleybz** [LevPasha/Instagram-API-python#117]
Previous issue was closed when Ubuntu solution was given but not for Windows.
https://github.com/LevPasha/Instagram-API-python/issues/111#issuecomment-281786029

**Comment by 3to1null** [comment]
Download ffmpeg and reference the path to ffmpeg.exe in your PATH var.

http://adaptivesamples.com/how-to-install-ffmpeg-on-windows/
