### ISSUE TITLE
Nothing happens after running the test.py

### ISSUE THREAD

**Issue by monajalal** [LevPasha/Instagram-API-python#118]
I was expecting list of followers according to to the following line but I got this:
` 13 InstagramAPI.getUserFollowers(media_id["ranked_items"][0]["user"]["pk"]) # get first media owner followers`
```
mona@pascal:~/computer_vision/Instagram/levpasha/Instagram-API-python$ python test.py
Login success!

mona@pascal:~/computer_vision/instagram/levpasha/Instagram-API-python$
```
Please suggest fixes!

**Comment by tarun7singh** [comment]
For printing any Json obtained previously. you should use following code.

`InstagramAPI.getUserFollowers(media_id["ranked_items"][0]["user"]["pk"]) # get first media owner followers
print InstagramAPI.LastJson`
