### ISSUE TITLE
Get more than 200 followers and following

### ISSUE THREAD

**Issue by ahmdrz** [LevPasha/Instagram-API-python#12]
```python
def getTotalFollowers(self,usernameId):
        followers = []
        next_max_id = ''
        while 1:
            self.getUserFollowers(usernameId,next_max_id)
            temp = self.LastJson

            for item in temp["users"]:
                followers.append(item)
            
            if temp["big_list"] == False:
                return followers            
            next_max_id = temp["next_max_id"]         
            
def getTotalFollowings(self,usernameId):
        followers = []
        next_max_id = ''
        while 1:
            self.getUserFollowings(usernameId,next_max_id)
            temp = self.LastJson

            for item in temp["users"]:
                followers.append(item)
            
            if temp["big_list"] == False:
                return followers            
            next_max_id = temp["next_max_id"]  
```

**Comment by ahmdrz** [comment]
Added on #14

**Comment by h-2-0** [comment]
It seems it stop working. Can't past beyond the first 200 even using the next_max_id and login without 429 error. Could  somebody confirm this please?

**Comment by h-2-0** [comment]
@ahmdrz 

If it is not next_max_id...What could it be? self.rank_token? self.SIG_KEY_VERSION?

**Comment by h-2-0** [comment]
@LevPasha, @ahmdrz 

 At least one Instagram PHP user reported a problem with pagination. It was fix yesterday:
[https://github.com/mgp25/Instagram-API/commit/ee350234c0cb32702969578e552737a3d7213fb7](https://github.com/mgp25/Instagram-API/commit/ee350234c0cb32702969578e552737a3d7213fb7)


```
public function getUserFollowings($usernameId, $maxid = null) 
     { 
-        return new FollowingResponse($this->http->request("friendships/$usernameId/following/?max_id=$maxid&ig_sig_key_version=".Constants::SIG_KEY_VERSION."&rank_token=$this->rank_token")[1]); 
+        return new FollowingResponse($this->http->request("friendships/$usernameId/following/?&rank_token=$this->rank_token".(!is_null($maxid) ? '&max_id='.$maxid : ''))[1]); 
     }

```

**Comment by h-2-0** [comment]
I applied the mpg25 fix's logic (i.e. removing SIG_KEY_VERSION) to the getUserFollowers function but still doesn't works. 

```
def getUserFollowers(self, usernameId, maxid = ''):
    return self.SendRequest('friendships/'+ str(usernameId) +'/followers/?rank_token=' + self.rank_token + '&max_id=' + str(maxid))

```
Still @ahmdrz 's getUsersFollowers seems exactly the same as the latest version of mpg25's getUserFollowers function. An Instagram PHP user doesn't report a problem with paginating User's Followers.

**Comment by ahmdrz** [comment]
@h-2-0 thx for your report. I will check it again.

**Comment by isdito** [comment]
Hello.
This is working. Because I have the same problem. I can not return more than 198

followings_count = InstagramAPI.getSelfUsernameInfo()
my_id = InstagramAPI.LastJson['user']['pk']
followings_count=InstagramAPI.LastJson['user']['following_count']
seguidos= InstagramAPI.getTotalFollowings(my_id)
seguidos= InstagramAPI.LastJson['users']
my_followings = 0
while my_followings < followings_count:
	for x in seguidos:
		print x['username'],x['pk']
		my_followings+=1
