### ISSUE TITLE
Login & Upload Picture error 

### ISSUE THREAD

**Issue by jorgetorresny** [LevPasha/Instagram-API-python#120]
from InstagramAPI import InstagramAPI

InstagramAPI = InstagramAPI("#", "#")
InstagramAPI.login()
InstagramAPI.uploadPhoto("test.jpg", "Great day @ work!!")
InstagramAPI.logout()

Output 

Request return 429 error!
Login success!

Request return 500 error!

Any help will be greatly appreciated. I'm not sure why I'm getting this errors. I believe the 429 error is fine I been reading about it and maybe I could safely ignore it but error 500 I'm not finding information about it ... If I'm wrong, please correct me thanks

**Comment by jorgetorresny** [comment]
is anyone still working on this project?

**Comment by mavieth** [comment]
It was updated 7 days ago and still functions for me... So I am assuming yes.

**Comment by lolaraigada** [comment]
what happens when you do python test.py? I get Login success but then I don't know what to do. I've tried doing python InstagramAPI.py but I don't get any answers on terminal.

**Comment by LevPasha** [comment]
@lolaraigada this api work fine.
