### ISSUE TITLE
Trying to use this but get 429 error

### ISSUE THREAD

**Issue by thedangler** [LevPasha/Instagram-API-python#124]
Hello all im doing is logging in and getting the 429 error.

InstagramAPI(config.INSTA_USER, config.INSTA_PASS)

Request return 429 error!
Login success!

Anything I should do to try and resolve this?

**Comment by reneManqueros** [comment]
Can you show me the code you use to call it?

**Comment by thedangler** [comment]
from InstagramAPI import InstagramAPI
import config

def loginToGram():
    igapi = InstagramAPI(config.INSTA_USER, config.INSTA_PASS)
    if igapi.login():
        return igapi
    return False

igapi = loginToGram()


That's all I have and I'm getting the message

Request return 429 error!
Login success!

**Comment by alxdnlnko** [comment]
429 http status is not an error, it is a warning about high rate requests. Your login was success, just ignore that message and continue working with api. I get that message every time and everything works ok.

**Comment by thedangler** [comment]
Ok cool,
The videouploads don't work.
That is why I thought it was an issue.
