### ISSUE TITLE
Hash Tag?

### ISSUE THREAD

**Issue by jorgetorresny** [LevPasha/Instagram-API-python#125]
Is there a way to get information from a hashtag 
Post Number#
Top Post 
From Top post get how many likes does the like has?

**Comment by 0x0soir** [comment]
You can get all media from a hashtag using tagFeed, this function return all images ranked. Combined with getMediaLikers is possible to obtain all users "likers" for each media (using media_id):

Example:
```
API = InstagramAPI("username", "password")
API.login()
API.tagFeed("hashtag")
items = API.LastJson["ranked_items"]
for photo in items:
  API.getMediaLikers(photo["id])
  for userLiker in API.LastJson["users"]:
    print userLiker["username"]
```
