### ISSUE TITLE
Problem with Mode 5 aka Burstmode

### ISSUE THREAD

**Issue by LeonardSylvester** [LevPasha/Instagram-API-python#126]
after a while  I always got this report for some usernames:

============================== 
Upss 'username' is already in ex user list... 
==============================
============================== 
Upss 'username' is already in ex user list... 
==============================

than the bot is trying to put the same user on the list all the time and got stuck at this point. how can I fix this?

**Comment by aRandomStranger** [comment]
Hi,

Did you mean https://github.com/instabot-py/instabot.py instabot.py?

**Comment by ThomasMW** [comment]
This is the Instagram API, not the bot. You're in the wrong repo.
