### ISSUE TITLE
tagFeed : not "top posts" but "most recent"

### ISSUE THREAD

**Issue by tarun7singh** [LevPasha/Instagram-API-python#127]
Hello,

I would like to fetch recent medias with a hashtag, but I am only getting "Top posts."

Please suggest the best method for doing this.

**Comment by LevPasha** [comment]
Show output JSON.

**Comment by tarun7singh** [comment]
@LevPasha 

I used these commands
```
from InstagramAPI import InstagramAPI
InstagramAPI = InstagramAPI("login", "password")
InstagramAPI.login()
InstagramAPI.tagFeed("cat")
print InstagramAPI.LastJson
```
And got these results -
https://paste.ee/p/N4mvu

Any idea what i'm doing wrong?

**Comment by Beauma** [comment]
I'd like to know the answer as well. The output JSON only shows the top 9 posts, not the most recent. This seems to be still unresolved.
