### ISSUE TITLE
proxy login

### ISSUE THREAD

**Issue by wrwr2** [LevPasha/Instagram-API-python#128]
Hello, the simple InstaBot v.1 has a proxy option in the login, however the InstagramAPI which has more features has no proxy option in the login. Or maybe I did not find the way to do it. Help is required. Thanks.

**Comment by ThomasMW** [comment]
If you look at the login method in InstagramAPI.py you see an option to provide a proxy. However you want to implement it is up to you.

**Comment by wrwr2** [comment]
@ThomasMW You are right I did it and it worked. It just need few modifications to the input to add the variable proxy to the API file and the input file. Thanks!

**Comment by ThomasMW** [comment]
@wrwr2 If you want to share your code or make a commit, it could be added to the repo for everyone to use.
