### ISSUE TITLE
ImportError: No module named 'ImageUtils'

### ISSUE THREAD

**Issue by trevordavies095** [LevPasha/Instagram-API-python#129]
I'm getting this frustrating error when trying to run a simple script that outputs the users feed. I can't install ImageUtils because then I get this error.

```
 Could not find a version that satisfies the requirement PIL (from ImageUtils) (from versions: )
No matching distribution found for PIL (from ImageUtils)
```

Any ideas?

**Comment by ThomasMW** [comment]
Try 'pip install pillow'

**Comment by mehrdadmms** [comment]
i have pillow but i still get this error 

`Traceback (most recent call last):
  File "F:\DEV\python\Instagram-API-python\examples\InstagramAPI.py", line 35, in <module>
    from ImageUtils import getImageSize
ModuleNotFoundError: No module named 'ImageUtils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "user_followers.py", line 6, in <module>
    from InstagramAPI import InstagramAPI
  File "F:\DEV\python\Instagram-API-python\examples\InstagramAPI.py", line 38, in <module>
    from .ImageUtils import getImageSize
ImportError: attempted relative import with no known parent package

F:\DEV\python\Instagram-API-python\examples>pip install pillow
Requirement already satisfied: pillow in c:\programdata\anaconda3\lib\site-packages (5.2.0)`

**Comment by zainulabid33n** [comment]
SAME ISSUE AS ABOVE. pillow is already installed


Traceback (most recent call last):
  File "C:\Users\Umar\Documents\GitHub\Instagram-API-python\examples\InstagramAPI.py", line 34, in <module>
    from ImageUtils import getImageSize
ModuleNotFoundError: No module named 'ImageUtils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\test.py", line 6, in <module>
    from InstagramAPI import InstagramAPI
  File "C:\Users\Umar\Documents\GitHub\Instagram-API-python\examples\InstagramAPI.py", line 37, in <module>
    from .ImageUtils import getImageSize
ImportError: attempted relative import with no known parent package
PS C:\Users\Umar\Documents\GitHub\Instagram-API-python\examples> pip install pillow
Requirement already satisfied: pillow in c:\programdata\anaconda3\lib\site-packages (5.4.1)
PS C:\Users\Umar\Documents\GitHub\Instagram-API-python\examples>



SAME ISSUES AS ABOVE
