### ISSUE TITLE
Работа скрипта.

### ISSUE THREAD

**Issue by 1egion** [LevPasha/Instagram-API-python#13]
Привет. Я правильно понял, что из-за ключа не работает? 
Мне возвращает : 
Request return 400 error!
Request return 400 error!
Request return 400 error!
Request return 400 error!
Request return 400 error!
Login success!

**Comment by LevPasha** [comment]
https://github.com/LevPasha/Instagram-API-python/commit/3487c5aedf1232a677ec08952909760339ad09ec проверь.

**Comment by 1egion** [comment]
Можно как-то с тобой связаться не публично? вк , телеграм?

**Comment by LevPasha** [comment]
@1egion пиши на почту (смотри в "поддержать проект").
