### ISSUE TITLE
How get all comment of post?

### ISSUE THREAD

**Issue by artas728** [LevPasha/Instagram-API-python#130]
Hi! Help me, please. How can I get all comments of posts? Now I can get not all comments
For example, I want to get all comments of this post: https://www.instagram.com/p/BR_YeMfB4v3/?taken-by=ververa
id: '1477006830906870775_19343908'

Now I do:

`from InstagramAPI import InstagramAPI

API = InstagramAPI("username", "password")
API.login()
API.getMediaComments("1477006830906870775_19343908")
print API.LastJson`

And get only 5 comments(total post has more than 1000 comments)
How can I get all comments of posts?

**Comment by LevPasha** [comment]
@artas728 i think JSON return something like "max_id". Look for other function that have it:
```python
getLikedMedia(self,maxid=''):
```
And you need to change it like this. If you have success - mekr pull request.

**Comment by Ronaldomata34** [comment]
I get this problem : 
```
line 613, in SendRequest
    raise Exception("Not logged in!\n")
Exception: Not logged in!
```
somebody know how to solve it?

**Comment by oguzhankarabulut** [comment]
hey,
how can i reach to 'id: '1477006830906870775_19343908'' for my case?
