### ISSUE TITLE
getUserFollowings outdated

### ISSUE THREAD

**Issue by HenryCooperGithub** [LevPasha/Instagram-API-python#133]
Outdated, always returns the first 200
```
def getUserFollowings(self, usernameId, maxid = ''):
    return self.SendRequest('friendships/'+ str(usernameId) +'/following/?max_id='+ str(maxid)
    +'&ig_sig_key_version='+ self.SIG_KEY_VERSION +'&rank_token='+ self.rank_token)
```
Possible fix:
```
def getUserFollowings(self, usernameId, maxid = ''):
     if maxid == '':
            return self.SendRequest('friendships/'+ str(usernameId) +'/following')
      else:
            return self.SendRequest('friendships/'+ str(usernameId) +'/following/?max_id='+ str(maxid))
```

Someone with more endpoint experience please check it.

**Comment by LevPasha** [comment]
@hxhjx make pull

**Comment by sohiyel** [comment]
I have 1008 following and when I don't set the maxid it gives me just 153 users and when I want to set the maxid it gives me nothing.So I don't know how to set maxid and where I have to get it.
I replace the hxhjx code with the original code but nothing changed.
I'll be very thanks full if you send me an example code of how can i get all of followings.

**Comment by sagunsh** [comment]
still only returns the same 200 followings repeatedly
