### ISSUE TITLE
AttributeError: InstagramAPI instance has no attribute 'token'

### ISSUE THREAD

**Issue by Xigocloud** [LevPasha/Instagram-API-python#135]
Hi Guys,
I built a nice script with this Instagram API and it worked very well. But suddenly, I didn´t change anything, I get this error:

Traceback (most recent call last):
  File "C:\Users\user\Documents\Python\Instagram-API-python-master\0.py", line 41, in <module>
    InstagramAPI.uploadPhoto("post\upload.jpg"," Awesome Picture\n-----------\nTag us on your pictures!\n-----------\nHave Fun!\n-----------\n#dog#cute#awesome#animal#sweet") 
  File "C:\Users\user\Documents\Python\Instagram-API-python-master\InstagramAPI.py", line 131, in uploadPhoto
    '_csrftoken'        : self.token,

AttributeError: InstagramAPI instance has no attribute 'token'

Thanks for helping!

**Comment by rsxgti** [comment]
Youll have to wait until the code is updated

**Comment by Andreypnfrv** [comment]
Have just the same mistake. Any progress?

**Comment by kubmin** [comment]
Also receiving error after uploading a few times

**Comment by mohammadhosseinime** [comment]
I have this problem too
