### ISSUE TITLE
Parameterize device/User-agent to max number of instances running per server?

### ISSUE THREAD

**Issue by h-2-0** [LevPasha/Instagram-API-python#136]
Wouldn't be great if we could change device and/or user-agents in order to maximise the number of instances running per server? That way 1 server could 'run' _n_ devices, and each devices could run _n_ instances. 

One problem I see is which IG_SIG_KEY and EXPERIMENTS values to use per device. 

Anyway, is this even possible? Is it worth it? Thoughts, ideas? @LevPasha

**Comment by aRandomStranger** [comment]
You can, of course, change the device ID, sig key and these things on your own.
I run ~500 accounts on one server and with default settings (not all on the same time of course, maybe 10) and never occurred with issues.

You can change the settings by looking at https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI.py#L29.

**Comment by h-2-0** [comment]
@aRandomStranger, 

Thanks for replying. Interesting. Perhaps you could run more than 10 using different device. 

I tried changing the code already but then I realised about the variables unique to certain devices.

**Comment by h-2-0** [comment]
@aRandomStranger 
By the way, do you use proxies with the settings you mention?

**Comment by aRandomStranger** [comment]
No

**Comment by h-2-0** [comment]
@aRandomStranger Good to know!

**Comment by h-2-0** [comment]
This is a non-issue (I should have opened this referring to device ID, sig key, etc.). I'm closing it.

**Comment by diegofcoelho** [comment]
Guys, (@h-2-0, @aRandomStranger , @LevPasha )

I am thinking to build a dictionary like it was mentioned in this issue but I am in doubt if a different API key is issued for each Instagram version... Do any of you know about it?

**Comment by h-2-0** [comment]
@diegofcoelho 

Correct me if I'm wrong guys but I understand each device uses a different key. Check here for more info: [https://github.com/mgp25/Instagram-API/wiki/Technical-information](https://github.com/mgp25/Instagram-API/wiki/Technical-information)

**Comment by diegofcoelho** [comment]
literally? Like every single device connected have a api key? Because if so, can you imagine everyone using LevPasha's API is connecting using the same device! That would be ridiculously easy to find and block by Instagram.. I hope not but will read thoroughly soon!

**Comment by h-2-0** [comment]
@diegofcoelho 

[https://github.com/mgp25/Instagram-API/blob/326eb97dc353e9b33f91c18a8c05f7a1bc8e8401/src/Devices/GoodDevices.php](https://github.com/mgp25/Instagram-API/blob/326eb97dc353e9b33f91c18a8c05f7a1bc8e8401/src/Devices/GoodDevices.php)

**Comment by diegofcoelho** [comment]
Well, then is an API to rule them all! That is good, I guess!
