### ISSUE TITLE
Launch test.py error

### ISSUE THREAD

**Issue by Kingson** [LevPasha/Instagram-API-python#139]
**I got error info when launch test.py, details info below:**
My evrimont: macOS 10.12.3/Python 2.7.10
kingson:Instagram-API-python/ (master✗) $ python test.py                                                                                                                                                                      [17:07:05]
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from InstagramAPI import InstagramAPI
  File "/Users/kingson/Study/Mac/Instagram-API-python/InstagramAPI.py", line 25, in <module>
    from moviepy.editor import VideoFileClip
  File "/Library/Python/2.7/site-packages/moviepy/editor.py", line 22, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/Library/Python/2.7/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.video.VideoClip import VideoClip
  File "/Library/Python/2.7/site-packages/moviepy/video/VideoClip.py", line 20, in <module>
    from .io.ffmpeg_writer import ffmpeg_write_image, ffmpeg_write_video
  File "/Library/Python/2.7/site-packages/moviepy/video/io/ffmpeg_writer.py", line 15, in <module>
    from moviepy.config import get_setting
  File "/Library/Python/2.7/site-packages/moviepy/config.py", line 38, in <module>
    FFMPEG_BINARY = get_exe()
  File "/Library/Python/2.7/site-packages/imageio/plugins/ffmpeg.py", line 86, in get_exe
    raise NeedDownloadError('Need ffmpeg exe. '
imageio.core.fetching.NeedDownloadError: Need ffmpeg exe. You can download it by calling:
   #imageio.plugins.ffmpeg.download()

**Comment by budocay** [comment]
Very simple
put this in the script:
`
import imageio
imageio.plugins.ffmpeg.download()
`
It will work

**Comment by ThomasMW** [comment]
As the error states, you need FFMPEG.

If you're on Debian/Ubuntu you can install it by 'sudo apt install ffmpeg'.

**Comment by Kingson** [comment]
@ThomasMW  I am on Mac

**Comment by budocay** [comment]
@Kingson Use directly in test.py my previous answer, i did it before on my computer, it works well

**Comment by Kingson** [comment]
@budocay  Add " import imageio imageio.plugins.ffmpeg.download()" in test.py? Thanks for replay.

**Comment by Kingson** [comment]
@budocay Added, but I got same issue

**Comment by budocay** [comment]
Have you install pip (the package manager for python2) ?

**Comment by Kingson** [comment]
@budocay I installed pip
![screen shot 2017-04-14 at 5 28 13 pm](https://cloud.githubusercontent.com/assets/468509/25039744/e304cc0a-2137-11e7-9803-2ed1f93b45dd.png)

**Comment by budocay** [comment]
Launch test.py as sudo or root as you want

**Comment by ThomasMW** [comment]
Please don't run these python scripts as root, it's not needed and poor privilege management.

**Comment by budocay** [comment]
@Kingson I forgot one thing, put first the import imageio and the command, before from the API import

**Comment by Kingson** [comment]
@budocay @ThomasMW Thanks for help, It's works now

**Comment by ThomasMW** [comment]
Close the issue please.
