### ISSUE TITLE
getSelfUserFollowers return true/false

### ISSUE THREAD

**Issue by budocay** [LevPasha/Instagram-API-python#140]
Hello,

I don't understand one thing about this API, indeed I try to get all my followers on my account but when i use this function it return only True/False, Can you help me to understand this thing ?

Thank you

**Comment by ThomasMW** [comment]
Share your code, otherwise we can't see what you're doing wrong.

**Comment by budocay** [comment]
Sorry, I found the solution I try to get only my follower number, i did this
`from InstagramAPI import InstagramAPI
InstagramAPI = InstagramAPI("", "")
InstagramAPI.login() # login
InstagramAPI.getSelfUserFollowers()
print(InstagramAPI.LastJson)
`
Now I get my follower name etc but not my total follower number
Too, When I start my program every time I have: "Request return 429 error!" And after "Login Success", why ?

**Comment by ThomasMW** [comment]
To get your total follower count you can do this:

´InstagramAPI.getSelfUsernameInfo()
print InstagramAPI.LastJson['user']['follower_count']´

To get rid of the 429 status codes you can comment out lines 85 to 89 in InstagramAPI.py.

**Comment by budocay** [comment]
It works, thanks a lot man

**Comment by ThomasMW** [comment]
You're welcome.

**Comment by aReaSa** [comment]
i have question too like that.
i need another user follower list and each followers bio.
can i get that?
thanks a lot

**Comment by ThomasMW** [comment]
Yes you can.

First you need to request a users follower list using `getTotalFollowers(usernameId)` and then paginate through the multiple JSON using `next_max_id`. This will get you all the followers and their `usernameId`.

Then you can request the follower bio's using `getUsernameInfo(usernameId)`.

**Comment by ThomasMW** [comment]
@LevPasha, requesting a close for this issue.
