### ISSUE TITLE
How to get all my account followers?

### ISSUE THREAD

**Issue by snenkov** [LevPasha/Instagram-API-python#146]
I am trying to do a simple thing, which is to get all the followers of my account (as a test).
Below is my code:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Use text editor to edit the script and type in valid Instagram username/password

from InstagramAPI import InstagramAPI

InstagramAPI = InstagramAPI("accName", "password!")
InstagramAPI.login() # login
InstagramAPI.getTotalFollowings("accName")
```

I get the following error on my terminal:

```
Request return 429 error!`

Login success!

Request return 404 error!
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    InstagramAPI.getTotalFollowings("cortesbnk")
  File "/home/stelian/Instagram-API-python/InstagramAPI.py", line 733, in getTotalFollowings
    for item in temp["users"]:
KeyError: 'users'
```

Does this look familiar to anyone and do you know how it can be fixed?
Thanks!

P.S. Really loving the repository otherwise and enjoying the exploration of the functions

**Comment by aRandomStranger** [comment]
Have you tried using getTotalSelfFollowings instead of getTotalFollowings for your account?

**Comment by snenkov** [comment]
I did but that did not work as well. Could you (or someone else) provide the code in more detail as an example?

**Comment by ThomasMW** [comment]
The function is 

`def getSelfUserFollowers(self): 
     return self.getUserFollowers(self.username_id)`

So what you need to do is `getSelfUserFollowers()`, that's it.

**Comment by snenkov** [comment]
Okay, I managed to sucessfully get my followers data, so thanks for the feedback.
Now I have another issue, I cannot get more than 172 followers' data... how can I get the data for all the followers?

**Comment by Kingson** [comment]
@snenkov In fact, you can directly use InstagramAPI.getTotalFollowers(usernameId) API,  just need to replace usernameId.
It works for me.

**Comment by snenkov** [comment]
I did and it still doesn't go over 200 requests.
Also, I fixed a big linked to timing, as if you request too many too fast you get a message to wait a few min and the script stops.
So still, can anyone get the details your followers (over 200)?

**Comment by ThomasMW** [comment]
You need to paginate, which means you need to request the next JSON using `next_max_id`. You can tell in the JSON if there is another page to request when `more_available = true`.

When you have requested all the JSON you can combine them for a full list of the followers.

**Comment by snenkov** [comment]
Thanks for the feedback, I much appreciate it.
I read as much as I could on the web (and previous discussions here) and what you are saying aligns with what I have so far understood. My issue however is with the technical implementation, I do not fully understand how to tell the JSON that there is another page. Could you please assist me with a code example?

**Comment by snenkov** [comment]
Here is my code (and my misunderstanding of what it does).
```
print(len(InstagramAPI.getTotalSelfFollowers()))
my_followers = InstagramAPI.LastJson
print(len(my_followers['users']))
```
Result:

```
Request return 429 error!
Login success!

437
109
```

437 is the number of my real followers. But why do I get 109 from the LastJson request?

**Comment by snenkov** [comment]
I managed to fix it! Thanks!

**Comment by apobec3f** [comment]
Could you please post your code for getting the total number of followers? Thank you

**Comment by eXtraMt** [comment]
can i have the code please ?

i want to build something similar and i am stuck like you

**Comment by hossein9118** [comment]
I have the same problem with the getMediaLikers
can anyone help me please?
