### ISSUE TITLE
What is needed in order to do a sign up?  Any pointers, ideas, suggestions are welcome! 

### ISSUE THREAD

**Issue by h-2-0** [LevPasha/Instagram-API-python#148]
@LevPasha and others 

I have been building my app based on this great library (the best for Python). Now I would like to know how can I start doing my own sign up/registration process.  Thing is I have little idea how to do that. I'm guessing is similar to login() and requires the signup challenge. Other than that I have no clue on where to start (besides sniffing via Charles proxy).  I have checked the Instagram API PHP (which is the library this one is based on) but I fail to understand it since I know nothing of PHP. 

Has anyone done something similar and care to share? It could help anyone reading here as well. Any pointers, ideas, suggestions are welcome!  

Thanks!

**Comment by snenkov** [comment]
Hi @h-2-0 
are you trying to do a sandbox app with a proper permission request and thus apply for a live mode from the official Instagram API?
Is this what your question is in regards to, as I did not understand you very clearly.

**Comment by h-2-0** [comment]
Hi @snenkov, 
Thanks for replying. I'm not looking to do a sandbox app. What I would like to do is modify Instagram.py

**Comment by h-2-0** [comment]
@snenkov 
Sorry, I clicked the close button by mistake.. So I was saying I would like to add a signup()  function besides the login() one  into the instagramAPI.py file.  But I have no idea how to do it. Thanks!

**Comment by skawm** [comment]
@h-2-0 maybe what you can try if you dont already done it is crawling the website? Or sniff like said before the creation of an account through MITMproxy. If you do this it will be incredible :)

**Comment by h-2-0** [comment]
@skawm Thanks! I have tried with Charles proxy already. The difficult part for me is creating the Python classes to deal with signing up.

**Comment by skawm** [comment]
Oh ok yes, I can imagine the difficulty. Alas I cant help you, im beginner into the Python World
