### ISSUE TITLE
Is it possible to get historical data?

### ISSUE THREAD

**Issue by snenkov** [LevPasha/Instagram-API-python#149]
Does anyone know if it's possible to get historical data: i.e. how many followers a certain account had at a previous point in time?

**Comment by ThomasMW** [comment]
The information returned contains timestamps for media uploads, you could use that as a time reference. However, I didn't check but I don't remember there being timestamps for followers/followings.

**Comment by snenkov** [comment]
Okay, thank you, ThomasMW !
