### ISSUE TITLE
Request return 429 error!

### ISSUE THREAD

**Issue by beben06** [LevPasha/Instagram-API-python#15]
Hello, i just begin with your project and seems really interesting !!
But after editing to my credentials i execute and get in the console:
```
Request return 429 error!
Login success!
```

It seems working anyway but just asked if you know about ?

**Comment by ahmdrz** [comment]
According to source code : 

```python
         if response.status_code == 200:
            self.LastResponse = response
            self.LastJson = json.loads(response.text)
            return True
        else:
            print ("Request return " + str(response.status_code) + " error!")
            return False
```

So if the response code not equals to 200 , program will print `Request return <Response Code> error!`

429 error code means The user has sent too many requests in a given amount of time ("rate limiting").

I think your error occurred on these lines :

```python
                    self.syncFeatures()
                    self.autoCompleteUserList()
                    self.timelineFeed()
                    self.getv2Inbox()
                    self.getRecentActivity()
``` 

Add ` time.sleep(1) ` on SendRequest function and try again. 
And let me know what happened.

**Comment by LevPasha** [comment]
@beben06 @ahmdrz +1

**Comment by beben06** [comment]
Thks for yours answers @ahmdrz @LevPasha .
BTW you need to import time to use time.sleep:

```
import time
time.sleep(1)
```

But i still get the error and it happen all the time on the same request `self.autoCompleteUserList()`

I also tried to put `time.sleep(10)` between each requests but always same error.

To be honest the first time i launched the script, the request doesn't fail and i get my response, and i notice that the response begin with:
{'status': 'ok', 'expires': 1475501913, 'users':....
So i think you can't repeat this call before a certain time.

I found someone have the same issue with the project of mpg25 [here](https://github.com/mgp25/Instagram-API/issues/243)
I didn't understand why you need to make theses calls but apparently theses reproduce the behaviour of the instagram app [here](https://github.com/mgp25/Instagram-API/issues/129)

So i don't know how to yet but i will try to avoid to login multiple times and store the informations of connection in a way.

**Comment by ahmdrz** [comment]
@beben06 what do you want to do with this API ?
I use some methods like getLikedMedia , timelineFeed , etc. I changed this login code and remove syncFeatures , autoCompleteUserList and ... and works for me with out any problem. 

After i added autoCompleteUserList only in login code , Request return 503 error occurred. 
so i think login code needs all of the methods. 

But try your login withtout syncFeatures , autoCompleteUserList and ...

For myself , it working without these methods.

**Comment by shrx** [comment]
Same HTTP error here. This was on my first use of an Instagram API.
```
>>> from api.InstagramAPI import InstagramAPI
>>> InstagramAPI = InstagramAPI("mistyped username", "password")
>>> InstagramAPI.login()
Request return 400 error!
>>> InstagramAPI = InstagramAPI("correct username", "password")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'InstagramAPI' object is not callable
>>> exit()
...
>>> from api.InstagramAPI import InstagramAPI
>>> InstagramAPI = InstagramAPI("correct username", "password")
>>> InstagramAPI.login()
Request return 429 error!
Login success!

True
>>>
```

**Comment by ahmdrz** [comment]
My login code haven't these methods 
```python
                    self.syncFeatures()
                    self.autoCompleteUserList()
                    self.timelineFeed()
                    self.getv2Inbox()
                    self.getRecentActivity()
```

I try original code. A have same error. @LevPasha what you think about it ?
@shrx you can ignore this error like me.

I can't test it right now. But @beben06 said :
> But i still get the error and it happen all the time on the same request self.autoCompleteUserList()

So i think you can ignore this error by removing `self.autoCompleteUserList()` line.

**Comment by ahmdrz** [comment]
According to [Rate Limits on Instagram API](https://www.instagram.com/developer/limits/) :
>All rate limits on the Instagram Platform are controlled separately for each access token, and on a sliding 1-hour window. Live apps have higher rate limits than apps in Sandbox Mode.

All of the users which use this repository have same access token. I think this is cause of 429 error. @LevPasha

**Comment by ahmdrz** [comment]
After I change my forked codes with [this commit](https://github.com/ahmdrz/Instagram-API-python/commit/b9afaf6140c0ab105b7466fc24c3968c7ac81344)

>{u'status': u'fail', u'message': u'Sorry, too many requests. Please try again later.'}

**Comment by LevPasha** [comment]
@ahmdrz this api should work like android app. I don't think all of android app user have same access token.

**Comment by supermensa** [comment]
@LevPasha Is it possible to generate a unique access token without registering an app with Instagram?

**Comment by LevPasha** [comment]
@supermensa i don't understand you.

**Comment by supermensa** [comment]
No worries. It is somewhat answered in #6

**Comment by dE1l** [comment]
i think, we may write a timestamp to self.last_reguest_tstmp for every SendRequest.
And in SendRequest check:
if (time.time() - self.last_reguest_tstmp) >1:
sleep(1)

**Comment by monajalal** [comment]
I used time.sleep(1) after/before each SendRequest and I get this:
```
>>> InstagramAPI.login()
Request return 429 error!
Login success!

True
>>>
```

**Comment by monajalal** [comment]
@dE1l  I tried what you said and got the following error:

```
655     def SendRequest(self, endpoint, post = None, login = False):
656         if (time.time() - self.last_request_tstmp) >1:
657             time.sleep(1)
```

```
mona@pascal:~/computer_vision/instagram/levpasha/Instagram-API-python$ python test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    InstagramAPI.login() # login
  File "/home/mona/computer_vision/instagram/levpasha/Instagram-API-python/InstagramAPI.py", line 67, in login
    if (self.SendRequest('si/fetch_headers/?challenge_type=signup&guid=' + self.generateUUID(False), None, True)):
  File "/home/mona/computer_vision/instagram/levpasha/Instagram-API-python/InstagramAPI.py", line 656, in SendRequest
    if (time.time() - self.last_request_tstmp) >1:
AttributeError: InstagramAPI instance has no attribute 'last_request_tstmp'
```
