### ISSUE TITLE
Request return 400 error!

### ISSUE THREAD

**Issue by snenkov** [LevPasha/Instagram-API-python#152]
After making a few requests in the past 24 hours, my account was (I am guessing) stopped from making requests and hence, I have this error.
Does anyone know why it happens and more importantly, how it can be sustainable fixed, such that I can have a working application that downloads data regularly?

P.S. I saw that this issue was addressed numerous times, however I did not see any clear resolution proposals.
Thanks!

**Comment by robwatkiss** [comment]
Look at the response text - Instagram typically returns a JSON message telling you what's wrong.

`InstagramAPI.LastResponse.text`

**Comment by snenkov** [comment]
I just checked the [documentation](https://www.instagram.com/developer/limits/) and I found the following: `You may also receive responses with an HTTP response code of 400 (Bad Request) if we detect spammy behavior by a person using your app. These errors are unrelated to rate limiting. `
This does not really help me understand why I got this 400 code though... 
What I was doing was downloading data regarding likes per photo and profile data of various Instagram accounts.

**Comment by toxydose** [comment]
When you trying to log in with the new test account after registration Instagram says 'please, enter your phone number to ensure that it is you'
I got the same error, but I created a new acc and all is OK now.
Maybe you should periodically create the new accounts or just submit and validate your phone number.

**Comment by CityAceE** [comment]
Today my Instagram account stopped to work with Instagram-API-python :(
Every after time I get: Request return 400 error!

What I tried:
1. I used Instagram-API-python on different computers with Windows and Linux on the same IP - no luck.
2. I used official application installed in my Android smartphone which connected to Internet via Wi-Fi with the same IP - works good.
3. I used Instagram-API-python with different Instagram account on the same IP - works good.

It looks like Instagram server is able to recognize Instagram-API-python and block it.

Please help to solve this problem!

**Comment by MMrR0b0TT** [comment]
Did you try a different account?

**Comment by VladislavPrh** [comment]
Use time.sleep(2)
