### ISSUE TITLE
There is look up "who block me" API in instagram API?

### ISSUE THREAD

**Issue by Kingson** [LevPasha/Instagram-API-python#153]
There is look up "who block me" API in instagram API?   Or how to get  "who block me" data?
Hope anyway, points, suggestion to me, thanks.

**Comment by ThomasMW** [comment]
There is no information in the JSON returned when requesting a profile which states if the user has blocked you or not. When a user has blocked your account the request is simply denied with a 404 status.

The only way you can verify if a user has blocked your account is to first verify the existence of the user and then request the user using your own account. If the user exists but your account gets a 404 then you know the user has blocked your account.

**Comment by Kingson** [comment]
Thanks for your reply.
