### ISSUE TITLE
uploadvideo fails with 429, 202, 500 errors

### ISSUE THREAD

**Issue by nebukadnezar** [LevPasha/Instagram-API-python#154]
Running this code:
`InstagramAPI = InstagramAPI(user,pwd)`
`InstagramAPI.login() # login`
`print InstagramAPI.LastResponse.text`
`InstagramAPI.uploadVideo(video_local_path,thumbnail_local_path,caption=caption)`
`print InstagramAPI.LastResponse.text`

returns:
Request return 429 error!
Login success!
{extremely long JSON object containing account information - i.e. login was successful and returned this huge object}
Request return 202 error!
Request return 500 error!
{"message": "Other media configure error: b'yEmZkUpAj4'", "status": "fail"}

Tried both with mov and mp4 movie file, both are 600x600 square. Account is fine to log in via browser or insta app, and the same video uploads fine via app. Any ideas?

**Comment by addonis1990** [comment]
I am having a similar problem when I use upload videos. Did you figure out what was the issue ?

**Comment by nebukadnezar** [comment]
Nope - I assumed it was a server side thing. Insta seem to jump through hoops to prevent us from creating automated uploads.

**Comment by skawm** [comment]
Same since yesterday.. :( Did you find the issue ?

**Comment by skawm** [comment]
Just found the issue!!! @nebukadnezar  @addonis1990 Just change your ip by using a proxy or a vpn :+1:

**Comment by Haydardi** [comment]
@skawm how do you utilize a proxy?

**Comment by skawm** [comment]
@Haydardi look at the Login() function here ;) [https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI/InstagramAPI.py#L69](url)

**Comment by Subterraneus** [comment]
same problem and it keeps happening erasing the exif data.
