### ISSUE TITLE
follow() method does not work

### ISSUE THREAD

**Issue by dmrz** [LevPasha/Instagram-API-python#155]
Response is ok:

`{u'status': u'ok', u'friendship_status': {u'incoming_request': False, u'followed_by': False, u'outgoing_request': False, u'following': False, u'blocking': False, u'is_private': False}}`

But nothing happens, target user is not followed.

**Comment by ThomasMW** [comment]
Show us your code.

**Comment by dmrz** [comment]
`
InstagramAPI = InstagramAPI("dmrz", "V6EicqkRJcmME2A4")
InstagramAPI.login()
InstagramAPI.follow("25025320")
`

**Comment by ThomasMW** [comment]
You just shared your login information, please remove your username and password.

**Comment by dmrz** [comment]
That's not my real password :D I am trying to follow @instagram user.

**Comment by ThomasMW** [comment]
Ah good.

replace 
`InstagramAPI.follow("25025320")` 
with
`InstagramAPI.follow(25025320)`

**Comment by cihadsevim** [comment]
Can we generate accounts with this source?

**Comment by ThomasMW** [comment]
No, and please don't ask off-topic questions in other users threads.
