### ISSUE TITLE
Import problem 15.05.2017

### ISSUE THREAD

**Issue by DjHaski** [LevPasha/Instagram-API-python#159]
Hi!
I just downloaded this new API,  and got an error when importing InstagramAPI.
```
C:\ScriptFolder\MagicPython\Instagram>bot.py
Traceback (most recent call last):
  File "C:\ScriptFolder\MagicPython\Instagram\bot.py", line 1, in <module>
    from InstagramAPI import InstagramAPI
  File "C:\CodeMagic\Python35\lib\site-packages\instagram_api-0.1-py3.5.egg\InstagramAPI\__init__.py", line 23, in <module>
    import ImageUtils
ImportError: No module named 'ImageUtils'
```
What it is? ImageUtils.py seems to be in the folder with the API.

**Comment by xecgr** [comment]
It seems a python3 error
```
(ve_test)xecgr@carteras:~/dev/ve_test/src/instagramapi$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from InstagramAPI import InstagramAPI
>>> 
(ve_test)xecgr@carteras:~/dev/ve_test/src/instagramapi$ python3
Python 3.4.3 (default, Jul 28 2015, 18:20:59) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from InstagramAPI import InstagramAPI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xecgr/dev/ve_test/src/instagramapi/InstagramAPI/__init__.py", line 23, in <module>
    from ImageUtils import getImageSize
ImportError: No module named 'ImageUtils'
>>> 
```

It could be fixed modifying the import like this:
```
try:
    from ImageUtils import getImageSize
except:
    from .ImageUtils import getImageSize
```
But I get other dependecy errors later, could you confirm me if it can be solved with this minor change?

**Comment by DjHaski** [comment]
Yep, now it's working. Thank you! Closing this issue.

**Comment by kmushegi** [comment]
Hey,

I keep getting a similar problem but with the library itself; any tips would be appreciated
'ImportError: No module named InstagramAPI'
Installed it using pip and the GH link

**Comment by xecgr** [comment]
I think it's injected by [this change](https://github.com/LevPasha/Instagram-API-python/commit/c333876805d6e53ed41f02c1d31eb42ff23cac1c)

I don't know what you wanted to fix, but now the lib only works with the workaround 
```
from InstagramAPI import InstagramAPI
InstagramAPI.InstagramAPI(username,pwd)
```

We're discussing about rolling back this or not. You can test the library with previous hack so far

**Comment by kmushegi** [comment]
My issue is that when I do
`from InstagramAPI import InstagramAPI` in test.py I get:
>`Traceback (most recent call last):
>  File "test.py", line 7, in <module>
>    from InstagramAPI import InstagramAPI
>  File "/home/user/insta_project/Instagram-API-python/InstagramAPI/__init__.py", line 1, in <module>
>    from InstagramAPI.InstagramAPI import InstagramAPI
>ImportError: No module named InstagramAPI
`

I have a folder called insta_project where I put the API folder.

**Comment by xecgr** [comment]
There have been some refactorings and the client initialization has changed several times
Try changing this line from `InstagramAPI/__init__.py`
```
-from InstagramAPI.InstagramAPI import InstagramAPI
+from . import InstagramAPI
```
And initilizating client like this:
```
from InstagramAPI import InstagramAPI
username,password = "",""
api = InstagramAPI.InstagramAPI(username,password)
```

Let me know if you success...

**Comment by kmushegi** [comment]
Yeah I actually got it working this way! Couldn't find this thread to update afterwards.

**Comment by Tolmino** [comment]
hi, i have installed today and i have copy the  InstagramAPI directory in my site '/usr/lib64/python2.7/site-packages', and i have too this error:

./test.py 
Traceback (most recent call last):
  File "./test.py", line 6, in <module>
    from InstagramAPI import InstagramAPI
  File "/usr/lib64/python2.7/site-packages/InstagramAPI/__init__.py", line 2, in <module>
    from . import InstagramAPI
  File "/usr/lib64/python2.7/site-packages/InstagramAPI/InstagramAPI.py", line 4, in <module>
    import requests
ImportError: No module named requests

i have tried to modify File "/usr/lib64/python2.7/site-packages/InstagramAPI/__init__.py", with all suggested import string but i haven't had success .
where i'm wrong ?

**Comment by xecgr** [comment]
Install request lib in your environemnt: `pip install requests`

**Comment by Tolmino** [comment]
yes, look here:

pip install requests
Requirement already satisfied: requests in /usr/lib/python3.4/site-packages

and:
pip install -r requirements.txt 
Requirement already satisfied: requests==2.11.1 in /usr/lib/python3.4/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: requests-toolbelt==0.7.0 in /usr/lib/python3.4/site-packages (from -r requirements.txt (line 2))
Collecting moviepy==0.2.2.11 (from -r requirements.txt (line 3))
  Using cached moviepy-0.2.2.11.tar.gz
Requirement already satisfied: numpy in /usr/lib64/python3.4/site-packages (from moviepy==0.2.2.11->-r requirements.txt (line 3))
Requirement already satisfied: decorator in /usr/lib/python3.4/site-packages (from moviepy==0.2.2.11->-r requirements.txt (line 3))
Requirement already satisfied: imageio in /usr/lib/python3.4/site-packages (from moviepy==0.2.2.11->-r requirements.txt (line 3))
Requirement already satisfied: tqdm in /usr/lib/python3.4/site-packages (from moviepy==0.2.2.11->-r requirements.txt (line 3))
Requirement already satisfied: pillow in /usr/lib64/python3.4/site-packages (from imageio->moviepy==0.2.2.11->-r requirements.txt (line 3))
Installing collected packages: moviepy
  Found existing installation: moviepy 0.2.3.2
    Uninstalling moviepy-0.2.3.2:
      Successfully uninstalled moviepy-0.2.3.2
  Running setup.py install for moviepy ... done
Successfully installed moviepy-0.2.2.11

**Comment by xecgr** [comment]
I've tested the lib with python 2.7.
It seems that you have installed 3.4. Anyone has tested the lib with this version?

**Comment by larissalong** [comment]
I'm testing the lib with python 3.6 (Anaconda custom (x86_64)) and encountered the same problem when running the code "from InstagramAPI import InstagramAPI":

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'InstagramAPI'

I've installed InstagramAPI and requests but it still doesn't work.
