### ISSUE TITLE
Possible to retrieve Story data?

### ISSUE THREAD

**Issue by jockonarock** [LevPasha/Instagram-API-python#162]
Good day! 

It's a fantastic API that you have written. I am using this almost everyday.

I am wondering if it would be possible to retrieve the view count for Instagram stories?

**Comment by vegbrasil** [comment]
Hi guys,

Is there any progress in getting stories?

Thanks

**Comment by Rahandi** [comment]
yes it's possible, i've added pull request for instagram stories retrieval, and if you take your own story there's viewer_count variable that display the view count of your story
