### ISSUE TITLE
How to get the link of the last post from the user?

### ISSUE THREAD

**Issue by ghost** [LevPasha/Instagram-API-python#164]
Can you help me? :)

**Comment by ThomasMW** [comment]
What do you mean with 'link'.

**Comment by 72matvey** [comment]
Url. My goal is to send every new user post to me in Slack. using his username. Is this possible?  
Or what information I can get from the last post from the user?

**Comment by ThomasMW** [comment]
Yes it is. 

In the JSON returned when requesting a userFeed there is a "url" key with the url as the value per item/post.

**Comment by 72matvey** [comment]
Colleague, can you tell me how to write this?

**Comment by ThomasMW** [comment]
`user_posts = insta.getUserFeed(usernameID, max_ID)`
`info = insta.LastJson`
`img_url  = info['items'][i]['image_versions2']['candidates'][0]['url'].split("?")[0]`

Enjoy.

**Comment by 72matvey** [comment]
Many thanks. Do I need to get a usernameid first? And what is max_ID ?

**Comment by ThomasMW** [comment]
the max_ID is used then you want to paginate through the userfeed. You don't need this for the most recent upload so you can remove it from the request.

The usernameID you can get using
`info['user']['pk']`

**Comment by 72matvey** [comment]
Thanks again. Are there any details about writing these codes somewhere?

**Comment by ThomasMW** [comment]
There is no wiki at this point for this API, so you need to look through the main code and look up the methods to see how to form requests properly.

You can also examine the JSON which is returned every request to see what data can be found where.

**Comment by 72matvey** [comment]
Yes, I tried to do it. But I do not have enough knowledge, probably. Can you help me write what I need? I think you can do it with ease.

**Comment by 72matvey** [comment]
And what is [i] ?

`img_url` = info['items'][i]['image_versions2']['candidates'][0]['url'].split("?")[0]'

**Comment by ThomasMW** [comment]
Sorry, that needs to be `info['items'][0]['image_versions2']['candidates'][0]['url'].split("?")[0]`

**Comment by 72matvey** [comment]
But it says
` img_url = info['items'][0]['image_versions2']['candidates'][0]['url'].split("?")[0]
IndexError: list index out of range`

**Comment by ThomasMW** [comment]
What is the request you made?

**Comment by 72matvey** [comment]
`API.login()
user_posts = API.getUserFeed('1425767024389221')
info = API.LastJson
img_url = info['items'][0]['image_versions2']['candidates'][0]['url'].split("?")[0]`

**Comment by ThomasMW** [comment]
Do you see any information returned when you `print info`?

**Comment by 72matvey** [comment]
`API.login() 
username_id = API.searchUsername("davismallory")
info = API.LastJson

user_posts = API.getUserFeed(usernameid)
info = API.LastJson
img_url = info['items'][0]['image_versions2']['candidates'][0]['url'].split("?")[0]
print (img_url)`

I suppose the problem with usernameid. Or not?

**Comment by ThomasMW** [comment]
`API.searchUsername("davismallory")`
`info = insta.LastJson`
`username_id = info['user']['pk']`
`user_posts = API.getUserFeed(username_id)`
`info = API.LastJson`
`img_url = info['items'][0]['image_versions2']['candidates'][0]['url'].split("?")[0]`
`print (img_url)`

**Comment by ThomasMW** [comment]
Btw if you ever run into the trouble of not finding the key you want use this:
`print json.dumps(info, indent=4, sort_keys=True)`

It will print the JSON using a structured tree form so it's easier the see how everything is stored :)

**Comment by 72matvey** [comment]
This is really cool! Thank you! Do you know how I can automatically receive a link every time a user downloads a post?

---
I need your PayPal account and personal contact :)

**Comment by ThomasMW** [comment]
No problem. Do you mean whenever a user posts a photo?

It seems you're trying something which requires some basic programming skills.
You can contact me on Skype at thomas.weber.skype since it's unrelated to this API.

**Comment by ThomasMW** [comment]
No problem. Do you mean whenever a user posts a photo?

**Comment by 72matvey** [comment]
Yeah. Photo or video :)
