### ISSUE TITLE
KeyError: 'ranked_items'

### ISSUE THREAD

**Issue by ghost** [LevPasha/Instagram-API-python#165]
I'm running test.py

Request return 429 error!
Login success!

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    InstagramAPI.like(media_id["ranked_items"][0]["pk"]) # like first media
KeyError: 'ranked_items'
---
What is problem?

**Comment by ThomasMW** [comment]
It seems there are no "ranked_items" in the JSON returned.

"ranked_items" are the top posts, "items" are the recent posts.

**Comment by toxydose** [comment]
as usually, it`s caused by the account errors. You must verify your phone number on Instagram to parse with your account. Just try to log in with your account and most probably you will see the phone activation challenge.
