### ISSUE TITLE
Is it possible to get all media id of a location?

### ISSUE THREAD

**Issue by ekremgurdal** [LevPasha/Instagram-API-python#172]
Hey all!

Is it possible to get all media id of a location? I couldn't figure it out

**Comment by ekremgurdal** [comment]
I figured it out

**Comment by impshum** [comment]
Care to share? I've been battling this for over an hour now.

**Comment by ekremgurdal** [comment]
`following   = []
tid = []
next_max_id = True
while next_max_id:
    if next_max_id == True: next_max_id=''
    _ = API.getLocationFeed(**location_id**,maxid=next_max_id)
    following.extend ( API.LastJson.get('items',[]))
    next_max_id = API.LastJson.get('next_max_id','')
    temp = API.LastJson
    for f in temp['items']:
          tid.append(f['caption']['media_id']`

@impshum

**Comment by impshum** [comment]
Could you put that in a code block please? It's a tad hard to read.
