### ISSUE TITLE
How to get all posts and actions of your posts OR a public profile posts ?

### ISSUE THREAD

**Issue by kosmox** [LevPasha/Instagram-API-python#174]
I would like to pull all published posts in my Instagram account OR  from a public Instagram account with number of likes and comments for all individual posts.

Really appreciate all your help!

Thanks,

**Comment by the-rccg** [comment]
There is a function for getting all posts, including these features as a JSON, it's very aptly named in the API file. As Peskin would say, the derivation is trivial and left as an exercise to the reader.
