### ISSUE TITLE
Clickable links in Direct

### ISSUE THREAD

**Issue by socialhammer** [LevPasha/Instagram-API-python#175]
Hello.

Please help me. Instagram make links in Direct  - clickable. How can make it using this library?

**Comment by the-rccg** [comment]
This is no API issue, or at least not one legible from the information given. 
If you have trouble understanding the API code, I recommend: https://learnpythonthehardway.org/book/

**Comment by socialhammer** [comment]
Why no API? Using API I can send direct message, but can't add link in this message.

**Comment by jockonarock** [comment]
I am having the same issue. Please advise if anyone knows the solution!
Thanks in advance

**Comment by ABeltramo** [comment]
Why is this closed with no response? I'm also facing the same issue.

**Comment by adrianorod** [comment]
@ABeltramo I've tried with your ajustes for the pull request #419 , but its not working for me. Theres no exceptions, the direct message its been sent normally, but without the clickable links, only texts. Would you know what could be happening?

**Comment by ABeltramo** [comment]
I'm using my code almost every day and it's working. You have to put a full link inside text with the https part. You should try on the regular app and then use the same text using my API.
If I can help in any way feel free to share some code or more details.

**Comment by adrianorod** [comment]
@ABeltramo thanks for the help. My simplified code is that:

> from InstagramAPI import InstagramAPI
> 
> login = "login"
> password = "password"
> userToSend = "userId"
> message = "See my channel on YouTube: https://youtube.com/distritoalfa"
> 
> api = InstagramAPI(login, password)
> 
> if (api.login()):
>     api.direct_message(message, userToSend)
> else:
>     print("Can't login!")

Theres any other thing that we have to do to work correctly?

**Comment by ABeltramo** [comment]
It's working on my end! You can try this easily sending message to yourself setting `userToSend = InstaAPI.username_id`, the following is a screenshot I just made.
![screenshot_20180729-200904](https://user-images.githubusercontent.com/1122217/43369287-a39bd6ce-936b-11e8-9ddd-f34be6ddc921.png)
Are you really sure to use my code and not the standard direct_message? You should try changing the name of the method in my code (for example set it like send_message_or_link() ) and then try calling it again!

**Comment by adrianorod** [comment]
@ABeltramo I think we are close... I tried to change the name of the method in the InstagramAPI.py file to "direct_message_test". Now, when I call it in my code, I receive this error:

> AttributeError: 'InstagramAPI' object has no attribute 'direct_message_test'

It seems be something simple, but I have no much affinities with the operation of the API. Have I to configure something before run the script?

**Comment by adrianorod** [comment]
I got it! I had to run the setup.py. Sorry for my ignorance lol. Now its working correctly, I had only to include the "import re" in the InstagramAPI.py too.

So... I'm very grateful for the help.

**Comment by Arseka44** [comment]
> I got it! I had to run the setup.py. Sorry for my ignorance lol. Now its working correctly, I had only to include the "import re" in the InstagramAPI.py too.
> 
> So... I'm very grateful for the help.

So? You just needed to solve setup.py file?

**Comment by waysi0** [comment]
Can anybody help me? I am trying to send message with link and i want to make link clickable, but it appear as a string in inbox after sending.

**Comment by VitolLub** [comment]
> I got it! I had to run the setup.py. Sorry for my ignorance lol. Now its working correctly, I had only to include the "import re" in the InstagramAPI.py too.
> 
> So... I'm very grateful for the help.

Hi adrianorod. Please describe more, how you fix this issue? Thank you a LOT :)
