### ISSUE TITLE
Getting Top Posts - Hashtag Research

### ISSUE THREAD

**Issue by Haydardi** [LevPasha/Instagram-API-python#177]
Hi all, 
I'm working on a bot that gets to total likes of the 9 top posts within a specific tag. Here's the mig code

```
def findTag(itemMode):
    InstagramAPI.tagFeed(tagList[currentTag])
    #ranked_items for popular posts and items for recent ones
    global items
    items = InstagramAPI.LastJson[itemMode]
    global limit
    if len(items) <= limit:
        limit = len(items);

while loop:
        for x in range(0, limit):
            findTag("ranked_items")
            InstagramAPI.getMediaLikers(items[x]["id"])
            like = InstagramAPI.LastJson["users"]
            likes.append(len(like))
        for z in range(0, limit):
            average += likes[z]

        average /= len(likes)
        print (average)
       print(likes)
```

However it seems like the number of likes that I am getting from these codes do not correspond with the real number of likes the top post within the #design. Here's my print output:
```
Request return 429 error!
Login success!

Design
999.7777777777778
[1000, 1000, 1000, 1000, 999, 1000, 1000, 1000, 999]
```

it seems like it cannot go above 1000 (real number for the first one should be 4000 lol), is there some kind of a limit? Is it my code or Instagram? Any help would be greatly appreciated.

**Comment by Haydardi** [comment]
I've just read that instagram has a limit, means it only return the latest 1000 likers of a ranked media. Do anyone have a workaround for this? Sharing your code here will me much appreciated.

**Comment by ekremgurdal** [comment]
Do you want to get like count of a media_id (picture/post)?

**Comment by Haydardi** [comment]
Exactly, of the latest 9 posts. How do I do that?

**Comment by ekremgurdal** [comment]
Actually getMediaComments(Media_id) returns total like count of the post in json format. 

You can reach like count via: mediainfo['items'][0]['like_count']

**Comment by Haydardi** [comment]
Thank you very much, I will try that 👍 
I have another question, do you know how to like the latest media of specific user?
Here's my code:
```
InstagramAPI.login() # login
#InstagramAPI.tagFeed("cat") # get media list by tag #cat
InstagramAPI.searchUsers("belkadhitroupe")
InstagramAPI.getSelfUserFeed
media_id = InstagramAPI.LastJson # last response JSON
InstagramAPI.like(media_id["ranked_items"][0]["pk"]) # like first media
```
I hope I'm not asking too much :)

**Comment by ekremgurdal** [comment]
I didn't find user feed function on this repo but I'm trying this version: 

1) create json link: www.instagram.com/usernamehere/?__a=1
2) get this link via urllib 
3) parse json and get most recent post of this user

**Comment by Haydardi** [comment]
Nice, could you help med writing that in code? I'm new to python, I would really appreciate it!

**Comment by Haydardi** [comment]
@ekremgurdal I don't really know what you mean by media_id in the code: getMediaComments(Media_id)
Anyway here's what I've got:
```
for x in range(0, limit):
            InstagramAPI.getMediaComments(items[x]["id"])
            mediainfo = InstagramAPI.LastJson
            print(mediainfo)
```
and here's my output:

`{'comment_likes_enabled': True, 'comments': [], 'comment_count': 0, 'caption': 
{'pk': 17851675648030158, 'user_id': 1545310157, 'text': '#enti#zebti#eyyyyy#', 'type': 1, 'created_at': 1446397491, 'created_at_utc': 1446397491, 'content_type': 'comment', 'status': 'Active', 'bit_flags': 0, 'user': {'pk': 1545310157, 'username': 'biboca86', 'full_name': '', 'is_private': False, 'profile_pic_url': 'http://scontent-arn2-1.cdninstagram.com/t51.2885-19/10748361_1579176108968881_1082767596_a.jpg', 'is_verified': False}}, 'caption_is_edited': False, 'has_more_comments': False, 'has_more_headload_comments': False, 'preview_comments': [], 'status': 'ok'}`

There's no like_count? Did I misunderstood?

**Comment by Haydardi** [comment]
I really need this for my masters exam, I've read about pagination but I just don't know how to implement it. Any help would be appreciated

**Comment by Haydardi** [comment]
Figured it out, thanks anyway :)
