### ISSUE TITLE
Statuscode 400 in login/sendRequest

### ISSUE THREAD

**Issue by pablodalma93** [LevPasha/Instagram-API-python#178]
When I try to run the script I get statuscode 400 in the response, in the SendRequest method when called  by the line  / (self.SendRequest('accounts/login/', self.generateSignature(json.dumps(data)), True)) in the login method

**Comment by greg234234** [comment]
me too

**Comment by skawm** [comment]
Got the same error.. everytime

**Comment by ernests** [comment]
Had the same problem. It seems that it returns 400 if the account is not verified. It might be useful to raise appropriate error message for this.

**Comment by liberty123** [comment]
checkpoint_required What kind of verification is it?

**Comment by skawm** [comment]
It's  when you have a security checkpoint, asking to verify a Text Verification, for example @liberty123
