### ISSUE TITLE
getTotalFollowers method return only 7000 users

### ISSUE THREAD

**Issue by SergeyNaz** [LevPasha/Instagram-API-python#179]
LastJson does not have "next_max_id" key and "big_list" is True after first iteration.

**Comment by torlakfaruk** [comment]
Probably limits cause it. You can add a wait method for it. Like this:
`        if response.status_code == 403:
            time.sleep(600)
            self.getUserFollowers(self.usernameId,self.next_max_id)`

**Comment by SergeyNaz** [comment]
@torlakfaruk I cannot find "response" variable. Method getTotalFollowers has code below:
 ```
   def getTotalFollowers(self,usernameId):
        followers = []
        next_max_id = ''
        while 1:
            self.getUserFollowers(usernameId,next_max_id)
            temp = self.LastJson

            for item in temp["users"]:
                followers.append(item)

            if temp["big_list"] == False:
                return followers            
            next_max_id = temp["next_max_id"] 
```

**Comment by JandirkDortmundt** [comment]
Managed to get them all (45k+) using a wait and the original getUserFollowers:
`followers = []
next_max_id = ''
while True:
    API.getUserFollowers(usernameId, next_max_id)
    temp = API.LastJson
    for item in temp["users"]:
        followers.append(item)
    time.sleep(2)
    if not temp['big_list']:
        break
    next_max_id = temp["next_max_id"]`

**Comment by Haydardi** [comment]
Jandirk, I've tried your code but and I still can't get more than 7500 out of 26k+ 
How come?

**Comment by Haydardi** [comment]
Here's my solution, in case anyone is facing the same issues.
`next_max_id = True
    try:
        while next_max_id:
            InstagramAPI.getUserFollowers(user_id)
            temp = InstagramAPI.LastJson
            for item in temp["users"]:
                if followerCount > len(followers) and followersLim > len(followers):
                    followers.append(item['username'])
                    #print(len(followers))
                else:
                    next_max_id = False
            sleep(2)`

**Comment by makusu2005** [comment]
@Haydardi, @JandirkDortmundt unfortunately it's both not working for me. Can you share your whole code so I can check what I do wrong? I only got 7404 results.

**Comment by pursuitdaily** [comment]
How does this work in the whole code? Mine disappears when I try to run...

**Comment by supernova85** [comment]
Hi guys,
I'm using "getHashtagFeed(tag, next_max_id)" which I can not get the whole posts from a special hashtag. For example I just could get 5124 posts for the hashtag "milanfashionweek2016" from 8925. The code won't return all posts and for more popular hashtags such as "milanfashionweek" gets back 10k out of 550K posts. Any one could help me what should I do?

Thank you!

**Comment by rcolpo** [comment]
I also can't have more than 7500 users. The key "next_max_id" is apparently no longer available on the returned dictionary when the function getUserFollowers is used.
