### ISSUE TITLE
getUserFollowers Pagination isn't working anymore

### ISSUE THREAD

**Issue by h-2-0** [LevPasha/Instagram-API-python#18]
```
next_max_id =''
while True:
    InstaAPI.getUserFollowers(user_id, next_max_id)
    temp = InstaAPI.LastJson
    print(temp['users'][0])
    next_max_id = temp["next_max_id"]
```

Each iteration changes _next_max_id_ but still gets the same temp object.

Yesterday an user reported a pagination problem with getUserFollowings at the [Instagram PHP](https://github.com/mgp25/Instagram-API/) repo (which this repo is based from). The author fix it removing the sig_key_version and putting rank_token before max_id. I tried doing the same but applied to UserFollowers but didn't work. 

By the way, [Instagram PHP](https://github.com/mgp25/Instagram-API/blob/ee350234c0cb32702969578e552737a3d7213fb7/src/Instagram.php) latest getUserFollower seems exactly the same...

```
 public function getUserFollowers($usernameId, $maxid = null)
        {
        return new FollowerResponse($this->http->request("friendships/$usernameId/followers/?max_id=$maxid&ig_sig_key_version=".Constants::SIG_KEY_VERSION."&rank_token=$this->rank_token")[1]);
        } 
```

....as the one here:

```
def getUserFollowers(self, usernameId, maxid = ''):
    return self.SendRequest('friendships/'+ str(usernameId) +'/followers/?max_id='+ str(maxid)
            +'&ig_sig_key_version='+ self.SIG_KEY_VERSION +'&rank_token='+ self.rank_token)
```

EDIT:

Is it me or is there some else getting the same problem?

**Comment by ggpid** [comment]
me too

**Comment by b3mb4m** [comment]
@h-2-0  @ggpid  same as me.Is there any working one?

**Comment by chuonghd** [comment]
This is how I solved it:
`
def getUserFollowings(self, usernameId, maxid = ''):
        if maxid == '':
            return self.SendRequest('friendships/'+ str(usernameId) +'/following/?rank_token='+ self.rank_token)
        else:
            return self.SendRequest('friendships/'+ str(usernameId) +'/following/?rank_token='+ self.rank_token + '&max_id='+ str(maxid))
`

**Comment by chuonghd** [comment]
> def getUserFollowings(self, usernameId, maxid = ''):
>         if maxid == '':
>             return self.SendRequest('friendships/'+ str(usernameId) +'/following/?rank_token='+ self.rank_token)
>         else:
>             return self.SendRequest('friendships/'+ str(usernameId) +'/following/?rank_token='+ self.rank_token + '&max_id='+ str(maxid))

**Comment by chuonghd** [comment]
`    def getUserFollowings(self, usernameId, maxid = ''):
        if maxid == '':
            return self.SendRequest('friendships/'+ str(usernameId) +'/following/?rank_token='+ self.rank_token)
        else:
            return self.SendRequest('friendships/'+ str(usernameId) +'/following/?rank_token='+ self.rank_token + '&max_id='+ str(maxid))`

**Comment by chuonghd** [comment]
This is how I solved it:

    def getUserFollowings(self, usernameId, maxid = ''):
        if maxid == '':
            return self.SendRequest('friendships/'+ str(usernameId) +'/following/?rank_token='+ self.rank_token)
        else:
            return self.SendRequest('friendships/'+ str(usernameId) +'/following/?rank_token='+ self.rank_token + '&max_id='+ str(maxid))

**Comment by h-2-0** [comment]
@chuonghd 

Thanks. But What about getusersfollowers?  Have you tried it?

**Comment by chuonghd** [comment]
@h-2-0 
getusersfollowers also works. If the request returns an integer value of next_max_id (e.g. 200), it'll be fine. However I once get a user that always return some random next_max_id string, which will cause the loop. I tried the PHP lib for that user and also failed.

One thing to remember is, dont put "&maxid=" in your first request as it's always null. You'll always get the loop if you do that.

**Comment by 179skr** [comment]
@chuonghd how would you limit getuserfollowers to only display like 10/20 users? Ive tried everything.

**Comment by danielb1234** [comment]
@chuonghd Hey, 
I tried your solution for getUserFollowers, but I still get only 200 followers when using the getTotalFollowers function..

**Comment by h-2-0** [comment]
Based on @chuonghd  suggestions I made the following changes on InstagramAPI.py to Make the Pagination Work Great Again. Thanks, @chuonghd !

```
    def getUserFollowers(self, usernameId, maxid = ''):
        if maxid == '':
            return self.SendRequest('friendships/'+ str(usernameId) +'/followers/?rank_token='+ self.rank_token)
        else:
            return self.SendRequest('friendships/'+ str(usernameId) +'/followers/?rank_token='+ self.rank_token + '&max_id='+ str(maxid))
```

**Comment by h-2-0** [comment]
@danielb1234 

It works for me. See my post above.

**Comment by h-2-0** [comment]
@179skr 

temp['users'][0:10] or temp['users'][0:20]

**Comment by LevPasha** [comment]
@h-2-0 create pull

**Comment by h-2-0** [comment]
@LevPasha 

Done! :) But please review it as this is the first time I do a pull request. I hope everything is ok.
