### ISSUE TITLE
Direct Messaging

### ISSUE THREAD

**Issue by Haydardi** [LevPasha/Instagram-API-python#181]
Hello fellas,
Anyone had some good luck with implementing the ability to send direct messages to others? Let's say I want to send a direct message to myself when my bot crashes or return an execution error, so I can be alerted using my phone.

**Comment by Haydardi** [comment]
Very useful feature! Is it available?

**Comment by levlet** [comment]
`    def sendMessage(self, target_user, msgText):
        target_user = '[[{}]]'.format(','.join([target_user]))
        url = 'direct_v2/threads/broadcast/text/'

        data = {
            'text': msgText,
            '_uuid': self.uuid,
            '_csrftoken': self.token,
            'recipient_users': target_user,
            '_uid': self.username_id,
            'action': 'send_item',
            'client_context': self.generateUUID(True)}

        return self.SendRequest(url, data)`

**Comment by Haydardi** [comment]
Thanks alot my man <3

**Comment by levlet** [comment]
no problem

**Comment by JorritWegman** [comment]
I keep geetin this error:
AttributeError: InstagramAPI instance has no attribute 'sendMessage'

**Comment by jockonarock** [comment]
@levlet great work buddy! Any idea how to make url in direct message clickable? I explored some options such as adding a 'link_urls' param into your data but can't seem to get any link clickable at all.

Thanks in advance.

**Comment by BatuhanKahraman** [comment]
InstagramAPI.sendMessage(targetuserid,"hiii")   not working ??? Pls help.. i writing function in a core

**Comment by BatuhanKahraman** [comment]
links not working in DM...

**Comment by hadifarnoud** [comment]
new changes allow links in direct message. this could be helpful in writing a bot for Instagram

**Comment by neomh** [comment]
Any ideas how to use this direct messaging feature ? :)

**Comment by hadifarnoud** [comment]
for example, a bot can take orders via DMs. a lot of people sell over Instagram.

**Comment by levlet** [comment]
@neomh 
Ideas huh? Alright! Though some of them are "unconventional" i'll give you some for fun :P
- Auto dm script for when a new user follows you.
- Script that scrapes comments for a specific term such as "Looking for python coder" That dms them your github profile
- Script that monitors your photos for swear words that asks them to stop.
- Artificial intelligence script that attempts to communicate with humans
- Spamming
- Botnet communication
- Sending a message at a set time to be used as an alibi XD

**Comment by rcolpo** [comment]
Should I just add levlet code into my program? 

I keep getting this error:
AttributeError: InstagramAPI instance has no attribute 'sendMessage'

**Comment by Mohamedemad4** [comment]
@rcolpo  you should add the function to your InstagramAPI class

**Comment by Frostie2** [comment]
Is there also a way to read messages from a chat?
Like api.readMessages(user_id, n) --> list of the last n messages

**Comment by pasha76** [comment]
how can we add an url in the direct message? I think it can be done... any ideas?

**Comment by nachovoss** [comment]
Hey Levlet, could you tell me in wich file and line do i have to paste your code for it to work, sorry about my inexperience im learning on the go

**Comment by matievya** [comment]
Does anyone know how to add a new subscriber group in instagram through python to direct

**Comment by matievya** [comment]
кто нибудь знает как добавить в direct группу новых подписчиков пока в группе не станет максимально количество людей в языке python
