### ISSUE TITLE
Project fork

### ISSUE THREAD

**Issue by Julian-O** [LevPasha/Instagram-API-python#184]
Hi,

Thank you for the work you have been doing on this project.

In order to use this library in my bot, I needed to make some big changes to make it more robust. 

- I needed more control of the output. Printing errors to the screen isn't sufficient. I need the output to go to the logging module where it could be redirected to my email when something goes wrong.

- I needed safer code. When something fails, I need it to raise an exception, so it can't be quietly ignored.

- I needed code, that followed the industry coding standards, so it was easier to read and understand.

I have created a fork at https://github.com/Julian-O/Instagram-API-python

I would be ecstatic if you wanted to merge these changes back into your project, but because there are some breaking changes that might affect some existing clients (and I expect to do MORE such changes in the future), I completely understand if you choose not to.

You might like to look at the changes I have made (including "TODO" statements) to see where I have identified and fixed bugs in the existing code.

I still have plenty to do, but I wanted to bring this to your attention now in case you have any requests, suggestions or desires to merge the code.

Thank you again for providing a base for me to make the changes.

**Comment by h-2-0** [comment]
@Julian-O 

Awesome! I also integrated logging into my project. Could it be possible if you open an 'issues' tab in your fork so we can provide feedback/file issues, etc? Thanks!

**Comment by Julian-O** [comment]
Done. Thanks.

**Comment by h-2-0** [comment]
Thanks, @Julian-O ! It's Xmas in July!
