### ISSUE TITLE
Getting Users Media.

### ISSUE THREAD

**Issue by rsxgti** [LevPasha/Instagram-API-python#185]
How would you get user media?

**Comment by AmaHacka** [comment]
The same question.

**Comment by TJM4** [comment]
This will get the logged on users media:

`InstagramAPI.getUserFeed(InstagramAPI.username_id)
media_id = InstagramAPI.LastJson`

**Comment by TJM4** [comment]
This will get the logged on users media:
`
InstagramAPI.getUserFeed(InstagramAPI.username_id)
`
`
media_id = InstagramAPI.LastJson
`
