### ISSUE TITLE
no module named 'InstagramAPI'

### ISSUE THREAD

**Issue by JSieger** [LevPasha/Instagram-API-python#186]
I get a ModuleNotFoundError when i try to do `from InstagramAPI import InstagramAPI`

Also when i try to do the pip install this is what happens:
`!pip install -e git+https://github.com/LevPasha/Instagram-API-python.git#egg=InstagramAPI
Obtaining InstagramAPI from git+https://github.com/LevPasha/Instagram-API-python.git#egg=InstagramAPI
  Cloning https://github.com/LevPasha/Instagram-API-python.git to c:\users\sj\documents\instagram\src\instagramapi
  Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/LevPasha/Instagram-API-python.git C:\Users\SJ\Documents\instagram\src\instagramapi
Cannot find command 'git'`

Also I'm running windows 64 and python 3.6

**Comment by AmaHacka** [comment]
now import like this:
from InstagramAPI.InstagramAPI import InstagramAPI as FakeAPI

**Comment by kmushegi** [comment]
@JSieger your issue seems to be that the command `git` doesn't exist and thus installation might not be successful.

@AmaHacka I am still having the import error; I tried your way but that didn't work either. Any further leads?

**Comment by leoneckert** [comment]
@kmushegi i just wanted to get this to work quickly and ran into the same issue. I found a dirty solution. 
I moved everything from the dir InstagramAPI down to the root and renamed InstagramAPI.py to something else, e.g. InstagramAPI2.py
then, ```from InstagramAPI2 import InstagramAPI``` works for me....

**Comment by AmaHacka** [comment]
@kmushegi can you show structure of your project and a piece of code where you trying to import this module?

**Comment by leoneckert** [comment]
@AmaHacka just recreated this (with the whole structure and code precisely as cloned). Hope that helps to resolve 👍  (on that note: thanks for this project, it's great!)
#### structure:
```
.
├── InstagramAPI
│   ├── ImageUtils.py
│   ├── ImageUtils.pyc
│   ├── InstagramAPI.py
│   ├── InstagramAPI.pyc
│   ├── __init__.py
│   └── __init__.pyc
├── LICENSE
├── README.md
├── env
│   ├── bin
│   ├── include
│   ├── lib
│   └── pip-selfcheck.json
├── examples
│   ├── Example-BulkUpload.py
│   ├── __init__.py
│   ├── direct_share.py
│   ├── get_all_comments.py
│   ├── thread_download.py
│   ├── upload_video.py
│   └── user_followings.py
├── requirements.txt
├── response_example.json
├── setup.py
└── test.py
6 directories, 20 files
```

#### error:
```
(env) ➜  Instagram-API-python git:(master) ✗ python test.py
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from InstagramAPI import InstagramAPI
  File "/Users/leoneckert/Desktop/igapi/Instagram-API-python/InstagramAPI/__init__.py", line 1, in <module>
    from InstagramAPI.InstagramAPI import InstagramAPI
ImportError: No module named InstagramAPI
```

**Comment by imanalopher** [comment]
@leoneckert, Have you install the dependencies? If, Yes: `pip install -r requirements.txt`

**Comment by Loaderon** [comment]
You may end up here like I did, even by having 

    from InstagramAPI import InstagramAPI
and everything else correctly set I still got the error:

    ImportError: No module named InstagramAPI

I was stupid enough to have InstagramAPI installed in one venv and was using another venv to run my project... dah
