### ISSUE TITLE
404 error/429 error

### ISSUE THREAD

**Issue by Yesssaag** [LevPasha/Instagram-API-python#187]
from InstagramAPI import InstagramAPI
user,pwd = '---', '------'                           #your credentials
InstagramAPI = InstagramAPI(user,pwd)       
InstagramAPI.login()                        # login
username_id = InstagramAPI.searchUsername('grp_offical' ) # user_name to user_id
InstagramAPI.follow(InstagramAPI.LastJson)
I'm trying to follow this acount called grp_official but whenever I run this code I first get error 429 then I log in successfully and then I get error 404 twice, what is causing these errors

**Comment by Yesssaag** [comment]
I know what the 429 error is, but what is the 404?

**Comment by skawm** [comment]
404 is error Not found :/ I dont know more about

**Comment by khoshtip10** [comment]
I guess the username is not found, or does not exist anymore.

**Comment by davidwagn** [comment]
Is it possible you are looking for "grp_official"? "grp_offical" does not exist.
