### ISSUE TITLE
getTotalFollowers, getTotalFollowings fail on private accounts without authorization

### ISSUE THREAD

**Issue by popadiys** [LevPasha/Instagram-API-python#189]
The following error appears when getTotalFollowers is executed to a private account I don't have authorization to see:

_In [291]: followers = InstagramAPI.getTotalFollowers('some_pk_to_privateaccount')

KeyError                                  Traceback (most recent call last)
<ipython-input-291-2c7fbe299fcf> in <module>()
----> 1 followers = InstagramAPI.getTotalFollowers('some_pk_to_privateaccount')

/home/petko/Instagram-API-python/InstagramAPI/__init__.pyc in getTotalFollowers(self, usernameId)
    726                 followers.append(item)
    727
--> 728             if temp["big_list"] == False:
    729                 return followers
    730             next_max_id = temp["next_max_id"]_

KeyError: 'big_list'

The output of the JSON is the following:

_In [292]: InstagramAPI.LastResponse
Out[292]: <Response [200]>

In [293]: InstagramAPI.LastJson
Out[293]: {u'status': u'ok', u'users': []}_

An additional check has to be added to the getTotalFollowers/getTotalFollowings to see in an empty list is returned without "big_list" variable.

**Comment by Maziar110** [comment]
Hi,
Is there any solution for this issue? I'm facing that
