### ISSUE TITLE
How to stay logged in? 

### ISSUE THREAD

**Issue by skawm** [LevPasha/Instagram-API-python#196]
Hello, I have searched and tried some things for my scripts to stay connected but I can not get a successful solution.. As you can see, each time you log in its generating a new UUID, PhoneID, token, session id... So Instagram may think now I have like Two hundreds of differents phone xD .. 

How do you stay logged in ? I have tried the solution referenced in the #103 issue but I can't get it working for me and it seems that it s only saving the session..
Please help, I think many people are also searching for a solution

**Comment by skawm** [comment]
So, no one here, so here is what i did for persistent keys (see [https://github.com/mgp25/Instagram-API/blob/master/src/Settings/StorageHandler.php#L17](url) 
I generated a brand new DeviceID, UUID, PhoneID as in the PHP lib.. and rewritten some of the code of the lib for my personnal use.. Good luck

**Comment by popadiys** [comment]
I don't know if this is the appropriate way, but I retain the whole object InstagramAPI. For example:

```
import pickle
from InstagramAPI import InstagramAPI
InstagramAPI = InstagramAPI("user", "pass")
```
and then:
```
with open('/mnt/c/Temp/session.txt', 'wb') as fp:
	pickle.dump(InstagramAPI, fp)
fp.close()
```
To restore the session after python restart:
```
with open('/mnt/c/Temp/session.txt', 'r') as fp:
    InstagramAPI = pickle.load(fp)
fp.close()
```

**Comment by skawm** [comment]
Cool thanks! Thanks for sharing your solution

**Comment by jjboi8708** [comment]
How would you execute tasks? I keep getting the error "EOFError: Ran out of input."
