### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by jmiller0** [LevPasha/Instagram-API-python#199]
Has anyone seen this error?  Clean compile and install, test.py is failing.

~/src/Instagram-API-python# python test.py

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    InstagramAPI = InstagramAPI("login", "password")
TypeError: 'module' object is not callable

**Comment by badjano** [comment]
bump

**Comment by badjano** [comment]
@jmiller0 I tried this and it worked:
import InstagramAPI
from InstagramAPI.InstagramAPI import InstagramAPI
it seems that there is yet another InstagramAPI inside InstagramAPI ( lol )
but I wasn´t able to upload an image though, got a bad request code!
