### ISSUE TITLE
urllib.parse.quote(data)

### ISSUE THREAD

**Issue by yrcnv** [LevPasha/Instagram-API-python#2]
Did it work when u tested? Because for me it crashes. The reason is: in line 432 u use `urllib.parse.quote(data)` but there is no method `parse`, so just delete it and leave it to `urllib.quote(data)`. It works for me this way for python v2.7.11 and v3.5.1.

**Comment by LevPasha** [comment]
@yrcnv I test functions that write in example on python 3.4.3.

**Comment by yrcnv** [comment]
@LevPasha Hmm, then it's strange, but my best guess it's about python versions.
Anyway, I have another thing to say: the functions doesn't do anything really, because in line 476 u have `return True` instead of `return self.LastJson`. Well, again, it works for me :)

**Comment by LevPasha** [comment]
@yrcnv it return `true` or `false` - but save `self.LastJson`. Look for example:
```
InstagramAPI.tagFeed("cat") # get media list by tag #cat
media_id = InstagramAPI.LastJson # media id of first media
```
