### ISSUE TITLE
No module named InstagramAPI

### ISSUE THREAD

**Issue by jmurphy45** [LevPasha/Instagram-API-python#204]
I installed everything and change username and password in test.py and I am getting this error.

`__init__.py", line 1, in <module>
    from InstagramAPI.InstagramAPI import InstagramAPI
ImportError: No module named InstagramAPI`

**Comment by tjleininger** [comment]
I had the same error. I changed `InstagramAPI/__init__.py` to read
```
from InstagramAPI import InstagramAPI
```
instead of 
```
from InstagramAPI.InstagramAPI import InstagramAPI
```
and now `test.py` works. Don't have time to dig in more right now but thought I'd pass it on.

**Comment by odadoun** [comment]
Yes, it works now ! 
Thanks

**Comment by chozzz** [comment]
Setting this works for me `export PYTHONPATH=$HOME/dirWithScripts/:$PYTHONPATH`

Source: https://stackoverflow.com/questions/4383571/importing-files-from-different-folder

**Comment by tolikkansk** [comment]
for me doesn't work

**Comment by HenrySaba** [comment]
@tolikkansk you might have skipped a step in the setup process. Try the following in your terminal:

1) Navigate to Instagram-API-python
2) Run this: pip install InstagramApi

**Comment by sergylog** [comment]
I have gone through the setup process, however
`from InstagramAPI.InstagramAPI import InstagramAPI`
as well as
`import InstagramAPI`
do not work for me. Does InstagramAPI support Python 3.x?
I am getting the same `ModuleNotFoundError: No module named 'InstagramAPI'`

**Comment by Himawariii** [comment]
Same problem and tried multiple approaches with no result. Help!

**Comment by Loaderon** [comment]
You may end up here like I did, even by having 

    from InstagramAPI import InstagramAPI
and everything else correctly set I still got the error:

    ImportError: No module named InstagramAPI

I was stupid enough to have InstagramAPI installed in one venv and was using another venv to run my project... dah
