### ISSUE TITLE
LastJson potential error

### ISSUE THREAD

**Issue by jmurphy45** [LevPasha/Instagram-API-python#206]
I have been trying to develop an command line script with this package and I seem to always get this error `AttributeError: 'bool' object has no attribute 'LastJson'`. I have had this error come up running one of the examples too.

`class Instagram:

	def __init__(self, username, password,user_id):
		self.username = username
		self.password = password
		self.user_id = user_id
		self.API = InstagramAPI(self.username,self.password)

	def api_login(self):
		self.API.login()

	def getSelfInfo(self):
		info = self.API.getSelfUsernameInfo()
		return info.LastJson`

`Request return 429 error!
Login success!

Traceback (most recent call last):
  File "insta.py", line 23, in <module>
    print(insta.getSelfInfo())
  File "insta.py", line 18, in getSelfInfo
    return info.LastJson
AttributeError: 'bool' object has no attribute 'LastJson'`

**Comment by davidwagn** [comment]
getSelfUsernameInfo() does not return an actual response. It returns True if the request was successful, False otherwise. Thus you can't call LastJson on info.

Try and see if 
`return self.API.LastJson`
works
