### ISSUE TITLE
[Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by roxly2** [LevPasha/Instagram-API-python#210]
I don't know why but when i launch exactly the same script i got on my computer to my VPS, i got that few minutes later :

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/media/1586292372102029633_679557859/like/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fecde07ea20>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
`
I even tried to use a proxy to see if it was the ip that was "banned" but i got same result..

Any clue?

**Comment by khoshtip10** [comment]
This is very odd. I happen to get it frequently. The workaround is to put it inside an exception handler.

**Comment by bongster** [comment]
@roxly2 @khoshtip10 
I also has a this issue. so this issue are solved?

**Comment by rgaldieri** [comment]
I just started messing up with the API and I have the same problem from often to often. The same script, with the same login credentials, works whenever it wants  to. Sometimes it returns this error while logging in, sometimes it just stop responding while calling the api. It never happened before, I am thinking this could be related to the unconfirmed account, but I can't be sure.
