### ISSUE TITLE
InstagramAPI.follow(self, userId): Fails with 'Request return 429 error!'

### ISSUE THREAD

**Issue by marcoramires** [LevPasha/Instagram-API-python#211]
InstagramAPI.follow(self, userId): Fails with 'Request return 429 error!' after following 40 users with 5 seconds interval. The multiple 'if' statements are simply there to avoid marking users as followed when the API returns 429 as an example.

    API = InstagramAPI(username, pwd)
    API.login()

    count = 0
    for i in bar(range(50)):
        user_id = instagram_leads[i]['pk']
        user = instagram_leads[i]['username']

        API.searchUsername(user)
        user_detail = API.LastJson.get('user', '')
        
        # Check if user still exists - returns 404 if not and removes it from MongoDb
        if "username" in user_detail:
            API.follow(user_id)

            # Check if follow() worked
            API.userFriendship(user_id)
            user_friendship = API.LastJson.get('following', '')

            if user_friendship is True:
                # Add to MongoDb
                instagram_leads_collection.update({'pk': user_id},
                                                  {'$set': {'followed': True,
                                                            'followed_at': datetime.datetime.utcnow()}}, upsert=True)
                count += 1
            else:
                print('Following failed: do nothing...')
        else:
            instagram_leads_collection.remove({'username': user})

        time.sleep(5)

    API.logout()

    print("======= Followed leads ========")
    print(count)

**Comment by davidwagn** [comment]
See https://httpstatuses.com/429

HTTP 429 means too many requests. This is an instagram limit, has nothing to do with the api. Increase the delay between followings.

Also see https://www.instagram.com/developer/limits/

**Comment by marcoramires** [comment]
Sure. Yes... Increasing the delay won't help much. I am working on a multi signature mode allowing login/logout in between requests. The limits mentioned above are related to the 'OAuth Client' authentication. This API is a lot simpler and uses the 'accounts/login/' which mimics a device user-agent.
