### ISSUE TITLE
400 after successful login and 429

### ISSUE THREAD

**Issue by completelyAbsorbed** [LevPasha/Instagram-API-python#213]
***
python postOne.py

Request return 429 error!
Login success!

Request return 400 error!
***

I took the login portion from the given test script, and added a single line to post a single picture.

Other issues like this seem to focus on adding a delay but that doesn't make sense to me here, I only make two calls to the api, and the first 429 comes after the call to login to the api.

I have confirmed that this is not a verification issue by logging in via browser on the box this script lives on.

thanks!

**Comment by completelyAbsorbed** [comment]
made a new account in case the old one was somehow flagged, no 429, still getting the 400 though
***
root@localhost:/bots/Instagram-API-python# python postOne.py
Login success!
***
Request return 400 error!

**Comment by completelyAbsorbed** [comment]
when I tried a second time 10 minutes later with the new account it's back to the 429's

**Comment by z1feR** [comment]
Same problem here. In my opinion it's not related to your location, because i run it on my raspberry pi (germany).

**Comment by z1feR** [comment]
Okay, so i got it. Its related to the type of image you use. Try to use an jpg image. Don't only change the image extension. I use OpenCV to save Images from my webcam.

**Comment by completelyAbsorbed** [comment]
changing the art I was generating, and all relevant references, from .png to .jpg fixed it also

**Comment by Justin-Chaschowy** [comment]
Wow thanks so much guys. jpg is the answer.
