### ISSUE TITLE
Is direct_share() working?

### ISSUE THREAD

**Issue by keromero86** [LevPasha/Instagram-API-python#216]
Hi,

I am trying to send a direct message to one of my test accounts. But, this doesn't work for me.

Can you please help me since this issue is very important for me.

I got this error message:
```
XANTO:InstagramAPI KerimGLC$ python test.py
Request return 429 error!
Login success!

<Response [500]>
Request return 500 error!
```

The code I am running is below:
```
InstagramAPI = InstagramAPI(user,pwd)       
InstagramAPI.login()                        # login
mediaId='1594513286425214984_5851043115'    #a media_id
recipients = ['micefx']                             #array of user_ids. They can be strings or ints
InstagramAPI.direct_share(mediaId, recipients,text='Test 123')
```

If I can get this to work,  I am willing to donate for the project.

Thanks!

**Comment by chiragshah1312** [comment]
the reciepients should be a list of user_id and not username.
I tried direct messaging it doesn't works. 
says : Thread does not exists
anybody having any luck on this piece?

**Comment by LevPasha** [comment]
@keromero86 do you have solution?
