### ISSUE TITLE
How to follow 

### ISSUE THREAD

**Issue by amk11** [LevPasha/Instagram-API-python#22]
Hi I use the following code to get followers of a user.

```
InstagramAPI = InstagramAPI("login", "password")
InstagramAPI.login() # login```
InstagramAPI.getUserFollowers(target_id, next_max_id)
temp = InstagramAPI.LastJson
temp['users'][0] # this gets the latest follower

```
how would i follow each user it has got?

**Comment by LevPasha** [comment]
@amk11 use loop for this (study python).

**Comment by 179skr** [comment]
I have used a loop but it doesnt seem to work. i used 

for f in temp:
      Bot.follow('users')

**Comment by LevPasha** [comment]
@179skr Bot.follow('users_id')

**Comment by 179skr** [comment]
Already tried that it didnt work is it something wrong with my code or the bot my code is below.

InstagramAPI = InstagramAPI("login", "password")
InstagramAPI.login() # login```
InstagramAPI.getUserFollowers("nameofperson")
temp = InstagramAPI.LastJson
temp['users'][0] # this gets the latest follower
for f in temp:
    InstagramAPI.follow('users')

**Comment by 179skr** [comment]
InstagramAPI.follow('users_id')

**Comment by ahmdrz** [comment]
@amk11  @179skr This is python :100: 
>InstagramAPI.getUserFollowers("nameofperson") 

This is not nameofperson , This should contains person id !

> temp = InstagramAPI.LastJson
temp['users'][0] # this gets the latest follower
for f in temp:
InstagramAPI.follow('users')

`for` for what ?
Change it to `for f in temp['users']:

And finally !
>InstagramAPI.follow('users')

According to [this](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI.py#L434) line , follow argument is userid !
So fill it correctly. 

I think pk is usernameid , so i wrote a script but i didn't test it ...
```python
insta = Instagram(username,password)
insta.login()
insta.getUserFollowers(insta.username_id)
temp = insta.LastJson
for f in temp['users']:
    insta.follow(temp['pk'])
```

This script will follow all your followers !!! :face_with_head_bandage: 
Really ? :face_with_thermometer: 
:smile:

But if you know your target usernameid , change it from

>insta.getUserFollowers(insta.username_id)
to 

>insta.getUserFollowers({{your target usernameid}})

> sorry my friends for my english , best regards.

**Comment by 179skr** [comment]
Thank you for the code it has helped me learn alot about python. I keep getting 

Traceback (most recent call last):
File "test.py" , line 18, in <module>
   Insta.follow(temp['pk'])
KeyError: 'pk' 

I am using the code you gave me below

insta = Instagram(username,password)
insta.login()
insta.getUserFollowers(insta.username_id)
temp = insta.LastJson
for f in temp['users']:
    insta.follow(temp['pk'])

**Comment by ahmdrz** [comment]
@179skr  sorry
>I think pk is usernameid , so i wrote a script but i didn't test it ...

change it to :
```python
insta = Instagram(username,password)
insta.login()
insta.getUserFollowers(insta.username_id)
temp = insta.LastJson
for f in temp['users']:
    insta.follow(f['pk'])
```

**Comment by 179skr** [comment]
@ahmdrz How do you limit the results of Instagram API.getUserFollowers("id",next_max_id) to like 10? I don't know how to assign a value to next_max_id

**Comment by ahmdrz** [comment]
@179skr after you called getUserFollowers , result have next_max_id , so you have to get it and pass it to getUserFollowers again for next page.

somthing like this 

https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI.py#L544

**Comment by 179skr** [comment]
@ahmdrz sorry i said that wrong. I mean how would you get like only the last 10 followers of a user. Getuserfollowers() currently gets the last 200 users but i only want 10 users.

**Comment by ahmdrz** [comment]
Ok , It's a list !
If you made a list like :
a = [1,2,3,4,5,6,7,8,9,0]
print(a[:5])

Note : 
Be sure about index out of range. 


See : https://github.com/ahmdrz/instagram-statistics/blob/master/main.py#L120

**Comment by ahmdrz** [comment]
Is it enough ? Do yo want pagination for each 10 users ?

**Comment by goodillla** [comment]
I've added to getTotalFollowers deep parameter not to get all the followers if you need just some of them.

`    def getTotalFollowers(self,usernameId, deep = ''):
        followers = []
        next_max_id = ''
        n = 0
        while 1:
            self.getUserFollowers(usernameId,next_max_id)
            temp = self.LastJson
            #print (temp['big_list'])
                        
            for item in temp["users"]:
                followers.append(item)
                n += 1
                #print (len(followers))
                if deep != '':
                    if n >= deep:
                        return followers

            try:
                if temp["big_list"] == False:
                    return followers            
            except:
                return followers
                
            next_max_id = temp["next_max_id"] `
