### ISSUE TITLE
getting number of likes of a specific post

### ISSUE THREAD

**Issue by completelyAbsorbed** [LevPasha/Instagram-API-python#220]
I want to get the number of likes on a specific post my bot has made, for analytics. I imagine the mediaInfo() function is the way to go, but I'm not sure how to provide the correct media_id? Is this something I can save when generating the post? If I used unique hashtags could I retrieve that way?

Thanks

**Comment by Haydardi** [comment]
I would do the following: Have your bot type a specific tag/letter/hashtag on the caption. Then get all the media you've posted, filter those medias by their caption to get the ones that are posted by your bot, and finally get their total likes.

`#get user id
InstagramAPI.searchUsername('YourUserNameHere')
username_id = info['user']['pk']
#get medias
InstagramAPI.getUserFeed(username_id)
info = self.InstagramAPI.LastJson
print(info["items"][0]) #you'll find the latest media info, incl caption and total likes
`
