### ISSUE TITLE
Q: What is the difference between this and official api?

### ISSUE THREAD

**Issue by iounas** [LevPasha/Instagram-API-python#222]
Are there any technical differences between this and https://github.com/facebookarchive/python-instagram?
Why and when should you use one or the other? Are request limits different or anything else?

**Comment by chandrakanth527** [comment]
A lot of difference. This one is unofficial and works without access token so no possible rate limit but you can get banned if you misuse.
Official API does not support uploading pics or videos or send direct messages to people
