### ISSUE TITLE
getSelfUserFollowers returns only 200 records?

### ISSUE THREAD

**Issue by narbehaj** [LevPasha/Instagram-API-python#224]
Hey, 
I have more than 200 followers but it seems in the newer version of this API, Instagram returns only 200 records. It also has page_size parameter in the response which might help us.

Is it possible to fetch all the records once? Or how to fetch the next page's records?

Thanks

**Comment by BatuhanKahraman** [comment]
Hi friend. Please use "next_max_id" in json data for next call.

First Call:
InstagramAPI.getSelfUserFollowers(userid)

Next Calls:
InstagramAPI.getSelfUserFollowers(userid,next_max_id)

**Comment by narbehaj** [comment]
@BatuhanKahraman Thanks buddy but the method has only self and does not have second input.
And what is next_max_id here?

**Comment by BatuhanKahraman** [comment]
Hi again. getSelfUserFollowers is call getUserFollowers with your user id. You dont need use getSelfUserFollowers for your follower. Use main funtion is getUserFollowers ...  getUserFollowers is accept your second paramater ( optional ) sample : 

InstagramAPI.getUserFollowers(youruserid,next_max_id (optional))
LastJsonData = InstagramAPI.LastJson

**Comment by narbehaj** [comment]
@BatuhanKahraman Thank you buddy, works!
