### ISSUE TITLE
There is no uploadAlbum feature

### ISSUE THREAD

**Issue by CityAceE** [LevPasha/Instagram-API-python#229]
It's impossible to use timeline album (aka carousel aka sidecar) feature of Instagram, This feature was launched on February 22nd, 2017 and already released in Instagram-PHP-API. This allows to upload the batch of 2-10 photos to one Instagram post.

https://github.com/mgp25/Instagram-API/blob/master/examples/uploadAlbum.php

Can anybody of developers to realise this feature in Instagram-API-python?

**Comment by xecgr** [comment]
I could code it, but I don't know when. As soon as I have enough time I'll code it (maybe next week?)

**Comment by CityAceE** [comment]
Thank you very much! I will wait for this feature.

**Comment by xecgr** [comment]
I've commited this feature in my master branch     
But, I haven't been able to upload a video in the album: a weird `u'{"message": "Other media configure error: b\'E3v4zLVnwi\'", "status": "fail"}''` is thrown, and I haven't found any documentation about this issue.     
Another known issue is that I pass a valid `usertags` config, but it doesn't seem to work    
Have a look and tell me if you find something else

**Comment by CityAceE** [comment]
Dear Francesc, thank you so much! It's really important feature personal for me. I'll integrate the using of this feature into my script next week. I'll let you know about bugs if I'll found them. Thanks again!

**Comment by CityAceE** [comment]
> Have a look and tell me if you find something else

I've tested it. As for me, I need only 2-10 photos per one post (no videos, no tags). And it works for me! Thank you very much!

But every time I get message "Request return 429 error!" just before message "Login success!" I don't know if it's problem of your branch or it's general problem.

**Comment by xecgr** [comment]
This "warning" is thrown in login process and I think it raises when previous sessions has found. Don't worry about it

**Comment by xecgr** [comment]
@LevPasha, could you close the issue?

**Comment by liberty123** [comment]
How do you upload multiple photos?  Forgive me for not finding a way

**Comment by xecgr** [comment]
have a look to: https://github.com/LevPasha/Instagram-API-python/blob/master/examples/upload_album.py

**Comment by liberty123** [comment]
I'm trying, thank you

**Comment by CityAceE** [comment]
As this feature was integrated into Instagram-API-python then README.md should be upated.
