### ISSUE TITLE
instagram feed liker

### ISSUE THREAD

**Issue by virginsince1997** [LevPasha/Instagram-API-python#23]
hello can i get a script to like my instagram  feeds @LevPasha

**Comment by ahmdrz** [comment]
@virginsince1997 You said @LevPasha . But I think @LevPasha is busy.
So I think I can help you.

Yes you can. Just you need to do these works :
1. Login
2. getTotalSelfUserFeed
3. Get MediaID of each feeds.
4. Like using MediaID.

If you have question you can ask me.
Excuse me , I just want to help you.

**Comment by virginsince1997** [comment]
Okay thank you bro, can I have your email, I have one but it's not running,

**Comment by ahmdrz** [comment]
Of curse, My email address is in my Account information. 
[ahmadrezazibaei@hotmail.com](mailto:ahmadrezazibaei@hotmail.com)

I think it will be better if you share your code here. Because more people will see this issue.

**Comment by virginsince1997** [comment]
Okay thanks, I emailed you already

**Comment by Haydardi** [comment]
Did you solve this? Would you please share your code?
