### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Funktiona** [LevPasha/Instagram-API-python#234]
I have worked with this API for a while and I like it really much. Huge thanks to the people who have been involved with this project! :+1: I hope I one day can be a helping hand.   It has everything except set profile picture but that is not a deal breaker. But I have a few questions someone maybe can help me with.

1. Is there a chance Instagram can detect this as not a real phone? I think of instagram might send some 'secret' packages that this API does respond wrong to or not respond at all to making instagram suspicious? For example if I use the real app and search for a user for each new character I input instagram will make suggestions on users I might mean. The app must for each character send a package to instagram so it can send back a list of users i might think of. But when using this and search for a user it will send the name in one package. 

2. I understand this is a 100% private API and in no way helped by instagram. I have seen instagram have their own API but with limited features. Would it be wise to try to combine these two so I use their API for simple stuff like: like/commend/follow. Or is this just unnecessary?

**Comment by MrJarnould** [comment]
2. My guess is that Instagram's Terms and Conditions state that you cannot combine both the official and unofficial API.

**Comment by Funktiona** [comment]
If both the official and unofficial API is in their Terms and Conditions. Does that mean they are okey with the the use of the unofficial API?

**Comment by MrJarnould** [comment]
> If both the official and unofficial API is in their Terms and Conditions

I never said that.

**Comment by MrJarnould** [comment]
_My guess_ is that there is a provision in Instagram's Terms and Conditions of their API that states that you cannot use both the official and unofficial API.
