### ISSUE TITLE
Need help with comment api

### ISSUE THREAD

**Issue by MattPlaysYT** [LevPasha/Instagram-API-python#235]
I'm trying to figure out a code where it uploads a picture, and puts a comment on the picture and just keeps doing it to the application is closed. Any ideas?

**Comment by pxlline** [comment]
Well, you have an Upload function and a Comment function.
It's just important that you get the mediaID of your uploaded photo.

So the pseudocode is something like:

```
API.uploadPhoto(photo)
API.getUserFeed(userID) 
user_feed = API.LastJson # returns the first posts of your user
mediaID = user_feed[0]["pk"] # gives the mediaID of your recent uploaded photo
API.comment(mediaID, comment_text)
```
