### ISSUE TITLE
Upload multiple photos to one post

### ISSUE THREAD

**Issue by dontsovcmc** [LevPasha/Instagram-API-python#237]
What about upload multiple photos into one post? 
Maybe smbd can helps you to code it? Do you have sniffered requests of it?

Thanks

**Comment by liberty123** [comment]
I have encountered this problem, may I ask you to solve it?

**Comment by CityAceE** [comment]
**xecgr** already integrated this feature into his branch:
https://github.com/LevPasha/Instagram-API-python/issues/229
