### ISSUE TITLE
Can we accept multiple friend follow requests from single Api

### ISSUE THREAD

**Issue by hsingla94** [LevPasha/Instagram-API-python#239]
Can we accept multiple friend follow requests from single Api

      def approve(self, userId):
        data = json.dumps({
                            '_uuid'         : self.uuid,
                             '_uid'          : self.username_id,
                            'user_id'       : userId,
                            '_csrftoken'    : self.token })
        return self.SendRequest('friendships/approve/'+ str(userId) + '/', self.generateSignature(data))

Thanks in Advance

**Comment by LevPasha** [comment]
@hsingla94 do you find solution?

**Comment by AkkiBond** [comment]
did you find the solution ?
