### ISSUE TITLE
Download Images?

### ISSUE THREAD

**Issue by jrbtaylor** [LevPasha/Instagram-API-python#24]
Can this be used to download images? I want to search for some tags (and possibly filter by likes or number of followers) and download all the images to create a dataset for research purposes. Is that possible with this API?

**Comment by LevPasha** [comment]
Yes.

**Comment by jrbtaylor** [comment]
I see functions for uploading but nothing for downloading.

**Comment by LevPasha** [comment]
@jrbtaylor sorry! My mistake. No.

**Comment by ahmdrz** [comment]
@jrbtaylor It's not hard , because in each items , we have `image_versions2` that have many urls for download images.

> I created a repository one month ago to check liked photos... but i didn't continue...

check it [here](https://github.com/ahmdrz/instagram-vision/blob/master/main.py#L58) to see how to get urls
