### ISSUE TITLE
Question: Using API in production / risk of bans

### ISSUE THREAD

**Issue by pythonios** [LevPasha/Instagram-API-python#240]
Is anyone using the inofficial API in production or with a rather big account?
Currently contemplating to use the API to automate posting (wouldn't be overused, max 1 per day). Has anyone been fully banned or shadowbanned for using this API?

thanks in advance

**Comment by CityAceE** [comment]
This API was blocked for my account: https://github.com/LevPasha/Instagram-API-python/issues/152#issuecomment-338345702

**Comment by gooflo** [comment]
would also be interested in this question. API worked for me for downloading 7000+ posts, but now it hangs at different calls. Tried it already with different accounts.

**Comment by geraldstanje** [comment]
hi could you reply to the question?

**Comment by LevPasha** [comment]
No one knows...
