### ISSUE TITLE
Follow and unfollow a specific user

### ISSUE THREAD

**Issue by rootm0s** [LevPasha/Instagram-API-python#241]
hi gals and gents,

How do I use the api for follow/unfollow a user? The following is a snippet, it's not working cuz I have no idea how to obtain the userId from given user.. Any ideas?
```
user1 = testInstaUser1
user2 = testInstaUser2

def follow(user1):
	InstagramAPI.follow(user1)
	
def unfollow(user2):
	InstagramAPI.unfollow(user1)

follow(user1)
unfollow(user2)
```

**Comment by pxlline** [comment]
1. You can get the userID over the username search function of the API:


```
def get_userID(username):
    InstagramAPI.searchUsername(username) 
    try:
        return InstagramAPI.LastJson["user"]["pk"]
    except Exception:
        print("username doesn't exist") 
        return False
```


2. Go to the following website to fiddle around a little and get userIDs of specific usernames:

[https://smashballoon.com/instagram-feed/find-instagram-user-id/](url)

**Comment by rootm0s** [comment]
@pxlline thanks will look into it!

**Comment by rootm0s** [comment]
Solved it.
