### ISSUE TITLE
fetching more tag results

### ISSUE THREAD

**Issue by afidegnum** [LevPasha/Instagram-API-python#242]
Hi guys, i m playing with https://github.com/LevPasha/Instagram-API-python and noticed it fetches just small result (8-10) of `api.tagFeed("android")` 
is there a way to fetch more media out of it? i m looking at the php version of it and they have this snippet::

```
$ids = [];
do {
    $search = $i->hashtag->search($tag, $ids);

    foreach ($search->getResults() as $result)
    {
        $ids[] = $result->getId();
    }
} while($search->getHasMore());
```

how can we integrate in this API ?

**Comment by pxlline** [comment]
```
def get_tag_feed(tag, next_max):
    feed = []
    next_max_id = ''
    for n in range(next_max):
        InstagramAPI.getHashtagFeed(tag,next_max_id) 
        temp = InstagramAPI.LastJson
        for post in temp["items"]:
            feed.append(post)
        try:
            next_max_id = temp["next_max_id"]     
        except Exception:
             print("error next_max. Tag: ", tag)
    return feed

next_max = 1 #amount of tag pages which are loaded: 1 equals approx. 80 posts
def get_tag_feed('anroid', next_max)

```

**Comment by afidegnum** [comment]
thanks for your reply but this does not like the posts... 

here is my modified code. 

```
def get_tag_feed(tag, next_max):
    feed = []
    next_max_id = ''
    for n in range(next_max):
        api.getHashtagFeed(tag,next_max_id) 
        temp = api.LastJson
        for post in temp["items"]:            
            if post["has_liked"] == False:
                print post["pk"]
                api.like(post["pk"])
                time.sleep(randint(3, 12))
                print post["has_liked"]
                print post["pk"]
            # feed.append(post)
        try:
            next_max_id = temp["next_max_id"]     
        except Exception:
             print("error next_max. Tag: ", tag)
    return feed
next_max = 1 #amount of tag pages which are loaded: 1 equals approx. 80 post
get_tag_feed('print', next_max)

```

**Comment by Arseka44** [comment]
> ```
> def get_tag_feed(tag, next_max):
>     feed = []
>     next_max_id = ''
>     for n in range(next_max):
>         InstagramAPI.getHashtagFeed(tag,next_max_id) 
>         temp = InstagramAPI.LastJson
>         for post in temp["items"]:
>             feed.append(post)
>         time.sleep(2) 
>         try:
>             next_max_id = temp["next_max_id"]     
>         except Exception:
>              print("error next_max. Tag: ", tag)
>     return feed
> 
> next_max = 1 #amount of tag pages which are loaded: 1 equals approx. 80 posts
> def get_tag_feed('anroid', next_max)
> ```

I`ve got a problem with your code...


Traceback (most recent call last):
  File "/home/ars1tazit1tazit/Рабочий стол/Instagram-API-python/InstagramAPI/hz.py", line 1077, in <module>
    get_tag_feed('anroid', next_max)
  File "/home/ars1tazit1tazit/Рабочий стол/Instagram-API-python/InstagramAPI/hz.py", line 1065, in get_tag_feed
    InstagramAPI.getHashtagFeed(tag,next_max_id)
  File "/home/ars1tazit1tazit/Рабочий стол/Instagram-API-python/InstagramAPI/hz.py", line 658, in getHashtagFeed
    return self.SendRequest('feed/tag/' + hashtagString + '/?max_id=' + str(
AttributeError: 'str' object has no attribute 'SendRequest'

Process finished with exit code 1

**Comment by pxlline** [comment]
The code does work. But it's only a snippet. It requires you to login in of course. Here is a functional program which imports approx. 100 posts from the tag "android". By increasing the number of next_max you can pull even more posts. It works for tags, userfeeds and any other feeds.


[get_tag.zip](https://github.com/LevPasha/Instagram-API-python/files/2835901/get_tag.zip)
