### ISSUE TITLE
Segmentation fault when import 

### ISSUE THREAD

**Issue by oyvsyo** [LevPasha/Instagram-API-python#243]
After instaling via pip or manually download files `import InstagramAPI` or `from InstagramAPI import InstagramAPI` occurs a Segmentation fault.
gdb:
I made a script.py:
```
import InstagramAPI

print "ok"
```
Then run gdb python:
```
$ gdb python
(gdb) run script.py
Starting program: /usr/bin/python script.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff1aea700 (LWP 14606)]
[Thread 0x7ffff1aea700 (LWP 14606) exited]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff7de373c in elf_machine_rela (skip_ifunc=0, 
    reloc_addr_arg=0x7fffdfc34f40, version=0x48, sym=0x7fffdf9294c0, 
    reloc=0x7fffdf93e640, map=0x1529230) at ../sysdeps/x86_64/dl-machine.h:301
301	../sysdeps/x86_64/dl-machine.h: No such file or directory.
(gdb) list
296	in ../sysdeps/x86_64/dl-machine.h
```
Is it problem with API or my machine?
Running Linux  4.4.0-97-generic  x86_64 GNU/Linux (Ubuntu 16.04 LTS upgraded from 14.04 LTS)

```
$ ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu9) 2.23
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
I have no file **dl-machine.h** on my computer

Thanks in advice!

**Comment by pxlline** [comment]
I think it's a problem with your python installation. Does any other python script work w.o. the InstagramAPI module?

Or try to use an IDE like spyder.

**Comment by oyvsyo** [comment]
All of other scripts work correctly. Problem is in my system.
I successfully instaled InstagramAPI in a docker container based on ubuntu:latest image.
