### ISSUE TITLE
API does not work any more - code did not change

### ISSUE THREAD

**Issue by gooflo** [LevPasha/Instagram-API-python#245]
Used the API for a download of 7000+ posts, which worked very well and I was greatful to build on this API. But now either login already fails oder any other step. Sometimes the first few posts can be downloaded, but then after the first few my program hangs during download of the image. My guess: my account was limited or something similiar. However, I already have two accounts, both do not work. I might try a third one, but wanted to ask: anybody having the same issues currently?

**Comment by rootm0s** [comment]
You could split the downloading between more than 2 accounts and use proxies. Also make sure to limit the downloads a bit so you don't download 3000 pictures within seconds.  

I use it to download tons of pictures, all of my bots are working.

**Comment by gooflo** [comment]
@rootm0s : thanks! I think using proxies is a very good idea. Could you recommend a package for automatic proxy selection or how are you using proxies? Manually? I also already included random sleeps ... what's your experience how many requests / downloads per minute are ok/working?

**Comment by rootm0s** [comment]
Also there's a API for removing/creating new Droplets from Python which I use:
https://github.com/koalalorenzo/python-digitalocean
