### ISSUE TITLE
How to test the login status?

### ISSUE THREAD

**Issue by afidegnum** [LevPasha/Instagram-API-python#248]
after api.login()

how do i later test if the user is still logged in or not? 

this code always return false.

`>>> if api.login() == True:
...     print "True"
... else:
...     print "False" 
False`
I want to be able to also test the response status from the server. i.e how do i catch the 429 status and test, in order to switch user if there is many request from this account?

InstagramAPI.isLoggedIn always returns true even if the use is logged out. how do i test if a user session is active or not ?

**Comment by pxlline** [comment]
Hmm. Maybe just send a random request and see whether LastJson replies with an error message.

**Comment by LevPasha** [comment]
Are you sure? api.login() should return True on success login. Try last version.
