### ISSUE TITLE
Your version of Instagram is out of date. Please upgrade your app to log in to Instagram.

### ISSUE THREAD

**Issue by andreyzhadan** [LevPasha/Instagram-API-python#250]
{"message": "Your version of Instagram is out of date. Please upgrade your app to log in to Instagram.", "status": "fail", "error_type": "needs_upgrade"}
{"message": "login_required", "logout_reason": 2, "status": "fail"}

**Comment by pxlline** [comment]
Can you log in via your smartphone or Bluestacks?

**Comment by andreyzhadan** [comment]
@pxlline yes, I'm able to login with my smartphone, but yesterday using your API I've received that errors.

**Comment by pxlline** [comment]
I am just using the API. Try to change the User_agent:

`USER_AGENT = 'Instagram 10.0.1 Android ({android_version}/{android_release}; 320dpi; 720x1280; {manufacturer}; {model}; armani; qcom; en_US)'.format(**DEVICE_SETTINTS)`

**Comment by andreyzhadan** [comment]
@pxlline After some time works for me as well.

**Comment by DenisSouth** [comment]
i'v got same problem with USER_AGENT. its out of date

`DEVICE_SETTINTS = {'manufacturer': 'Xiaomi',
                       'model': 'HM 1SW',
                       'android_version': 18,
                       'android_release': '4.3'}
    USER_AGENT = 'Instagram 10.26.0 Android `

do you have any issue?
