### ISSUE TITLE
Using Old Logined TOKEN ???

### ISSUE THREAD

**Issue by BatuhanKahraman** [LevPasha/Instagram-API-python#251]
I suggest one idea... Api users have more 429 error .. Because this api call token request in login function per process. Api already have token before last request. what we need relogin for all ?  

My dream is  : 
InstagramApi.LoginFromToken('last_token_from_last_login')

This idea may be will prevent account blocked or 429 errors...

thnks...

**Comment by n0thingness** [comment]
The csrf token can be cached, but to my understanding you would need to pickle and unpickle the request.Session() object in order to save and resume a session. However, I stopped examining this possibility when I learnt that the session object is most likely not thread safe.

**Comment by burkass** [comment]
Hi, but what if i generated cookie from selenium as mobile driver. I got csrf token from api.instagram.com and www.instagram.com. Can you use this token instead of insert password.
Why i did it? It's because i want to login without using password and using cookie file.

**Comment by LevPasha** [comment]
https://github.com/LevPasha/Instagram-API-python/issues/309
