### ISSUE TITLE
Upload bulk pictures with unique captions

### ISSUE THREAD

**Issue by ato09** [LevPasha/Instagram-API-python#255]
Is there any scripts that allow us to upload different pictures with different captions? Ask the script to use the captions stored in that list/file in-order in accordance to the name of the picture?

example:

List of pictures to upload in a folder: (e.g Desktop/IGPictures)

pic01.jpg
pic02.jpg
pic03.jpg

File for the caption contains this info. (e.g Pic-Caption.txt or any files type)

*picture's name        *caption for the picture
pic01.jpg                        Caption picture 01.
pic02.jpg                        Caption picture 02.
pic03.jpg                        Caption picture 03.

So the script will be something like this(?):

```
import os
import time
import random
from os import listdir
from os.path import isfile, join
from random import randint
from InstagramAPI import InstagramAPI

PhotoPath = "~/igphoto/" # Change Directory to Folder with Pics that you want to upload
IGUSER    = "IGUsername" # Change to your Instagram USERNAME
PASSWD    = "IGPassword" # Change to your Instagram Password
#Change to your Photo Hashtag
IGCaption = "**Get caption list from Pic-Caption.txt**"

os.chdir(PhotoPath)

ListFiles = [f for f in listdir(PhotoPath) if isfile(join(PhotoPath, f))]
print ("Total Photo in this folder:" + str (len(ListFiles)))

#Start Login and Uploading Photo
igapi = InstagramAPI(IGUSER,PASSWD)
igapi.login() # login

for i in range(len(ListFiles)):
    photo = ListFiles[i]
    print ("Progress :" + str([i+1]) + " of " + str(len(ListFiles)))
    print ("Now Uploading this photo to instagram: " + photo)
    igapi.uploadPhoto(photo,caption=IGCaption,upload_id=None)
    # sleep for random between 600 - 1200s
    n = randint(600,1200)
    print ("Sleep upload for seconds: " + str(n))
    time.sleep(n)
```

**Comment by RPSPandora** [comment]
I made this script, upload random image in folder using same caption.

try edit script using :

IGCaption = "**Get caption list from Pic-Caption.txt**"
==>
IGCaption = ListFiles[i]

It should add caption based on your image filename. Cmiiw.

**Comment by RPSPandora** [comment]
You can use regex to automatically delete the .jpg extension. 

Example, im using regex to include only "@username" in caption from an image file template "@username---random.jpg" : https://github.com/RPSPandora/InstaBulkUpload.py

**Comment by ato09** [comment]
I believe it would worked if the captions are short and have no unallowed character for naming files. Can't the scripts read from a file that list the image name and the captions and reproduce the image name into: 

`PhotoPath = "~/igphoto/imagename.jpg"`

and the reproduce the corresponding captions of the image into:

`IGCaption = "**Get caption list from Pic-Caption.txt**"`

I've read about python read and write function but I can't wrap my head around this as I've very limited knowledge of python. Anyway, thank you for your time in giving your thought. I hope I'm not asking too much.
