### ISSUE TITLE
IP BAN

### ISSUE THREAD

**Issue by p30arena** [LevPasha/Instagram-API-python#257]
Does Instagram Flag and Ban an IP address for using multiple accounts?
_

**Comment by Ebanchous** [comment]
I have the same troubles, IG blocks account after first like

**Comment by rootm0s** [comment]
They probably do, so make sure you run proxies or a VPS. My setup is 3x bots on 3x different servers in different locations, no ban yet! 👍

**Comment by torlakfaruk** [comment]
I'm using at least 50 accounts on a server more than 1 year and nothing happened. But i'm using just follow, unfollow and share codes. Not like or comment.

**Comment by h-2-0** [comment]
@torlakfaruk 

What is or what do you mean by  'share codes'? Thanks.

**Comment by LevPasha** [comment]
No one knows how IG ban accounts. Try to change ip\proxy\useragent\new sig key.
