### ISSUE TITLE
Story feature?

### ISSUE THREAD

**Issue by stefanerben** [LevPasha/Instagram-API-python#258]
I think I saw in the PHP API that it is possible to post Stories :) anyone able to integrate this in the python API? It would really help me.

**Comment by AndreasMTS** [comment]
Would be nice if the story feature also works in python. I think there is already the feature working
in the php InstagramAPI. Maybe someone can port this feature to the python users!

**Comment by 01E0E1** [comment]
I won't make PR, but you can see how it's done here: [https://github.com/01E0E1/Instagram-API-python/commit/fcb040e9540c8424732d580832ce27c1b8f37516](url)

**Comment by stefanerben** [comment]
@01E0E1 Thank you for your answer, in the meantime I programmed it by my own, but your code is way cleaner :)

**Comment by LevPasha** [comment]
@01E0E1 can you make pull request?

**Comment by 01E0E1** [comment]
Ok, made PR #308
