### ISSUE TITLE
Please use travis-ci

### ISSUE THREAD

**Issue by ahmdrz** [LevPasha/Instagram-API-python#26]
Hello , If you can please tell travis-ci to check your repository.
For each PR , We need to know confilicts and etc...

**Comment by LevPasha** [comment]
what?

**Comment by ahmdrz** [comment]
travis-ci.org

**Comment by LevPasha** [comment]
@ahmdrz what is this shit? )) 
You can ask to test my repo anyone. I don't know what is this?
