### ISSUE TITLE
Bot dont follow anymore

### ISSUE THREAD

**Issue by Sergei-tbb** [LevPasha/Instagram-API-python#261]
Hi! Thanks for your API,it  is really cool.
I use 3 instagram accounts for follow/ufollow actions. 
I started use your API 6 days before, and everything was fine, but now I cant follow people.  
There is my code
`client = InstagramAPI('login', 'pass')`
`client.Login()`
`client.follow(5459722468) `

`client.follow(5459722468)` - return True 
and `self.client.LastResponse.text` looks good
`'{"friendship_status": {"following": false, "followed_by": false, "blocking": false, "is_private": false, "incoming_request": false, "outgoing_request": false, "is_bestie": false}, "status": "ok"}'`
and `self.client.LastResponse.status_code` get 200

But if I go on instagram page - I dont see this user on my following list.
First its happened in my first account, and after 1 day - its happened in my second account.  maybe it happened because I didnt use proxy, and instagram  block me? But I dont have any errors in LastJson, and my unfollow function works fine
Can you help me?

PS. Sorry about my english

**Comment by cdotv** [comment]
I fixed this issue by connecting my instagram with facebook.
