### ISSUE TITLE
 Media likes of public profile

### ISSUE THREAD

**Issue by arslanhashmi** [LevPasha/Instagram-API-python#262]
Hi, i want to make an app in python which will monitor the like on my company accounts these are 5 in number, i just want to know likes on my recent account, can i do this with your api?

**Comment by pxlline** [comment]
Yes. That's possible to do. There is not even a restriction of the number of likes you can read from one of your posts.

**Comment by kono10** [comment]
can you provide an example of this?

**Comment by arslanhashmi** [comment]
i am having a loop to monitor my last loop that works with a sleep of 1
minute.

Wa Salam!
Muhammad Arslan
