### ISSUE TITLE
Uploading photo from url

### ISSUE THREAD

**Issue by omerb124** [LevPasha/Instagram-API-python#266]
Hey,
I'm trying to upload photo from url, and get an error. 
Does it need to be like that, or I did something wrong?

**Comment by pxlline** [comment]
Maybe you should post your code and the error.

**Comment by omerb124** [comment]
Hey, I used the test code, didn't change anything, just the user & pass & file path.
Do you know if it's possible to upload photo from url (and not from file which hosted on computer)?
