### ISSUE TITLE
Direct messages

### ISSUE THREAD

**Issue by nazimus** [LevPasha/Instagram-API-python#267]
Hello everyone, I was wandering if there is an option to collect messages received from direct messages ( I have spent the past hour search and I found nothing so far )

**Comment by jockonarock** [comment]
Hey you can do this with getv2Inbox(). Check the API documentation

**Comment by neomh** [comment]
Hello

were you able to send direct messages, i added this code to the init script 

    def sendMessage(self, target_user, msgText):
        target_user = '[[{}]]'.format(','.join([target_user]))
        url = 'direct_v2/threads/broadcast/text/'
        data = {
        'text': msgText,
        '_uuid': self.uuid,
        '_csrftoken': self.token,
        'recipient_users': target_user,
        '_uid': self.username_id,
        'action': 'send_item',
        'client_context': self.generateUUID(True)}
        return self.SendRequest(url, data)

In my script 

API = InstagramAPI(username,pwd)
API.login()    
user= 'toto'
messg = 'blabla'
API.sendMessage(user,messg)

Getting a 400 error message. Any ideas ?

**Comment by neomh** [comment]
@nazimus Thanks a lot it works now :)

**Comment by jockonarock** [comment]
Does anyone of you know how to include a hyperlink web address in the message content?

Thanks in advance.

**Comment by LevPasha** [comment]
@neomh or @nazimus plz make pull request.

**Comment by AtotheY** [comment]
@neomh's code works well, is there any way we can merge it into the existing library?

**Comment by FlameShotBow** [comment]
@neomh Your code works great for sending messages. Any chance of modifying it to send photos as well?

**Comment by swagner2** [comment]
> @neomh's code works well, is there any way we can merge it into the existing library?

was this ever pulled into the main repo?
