### ISSUE TITLE
Get all specific (public) user followers

### ISSUE THREAD

**Issue by testingInsta** [LevPasha/Instagram-API-python#268]
Hello! 
Some can help me with an code example for getting all usernames that follows a specific user.

Thanks !

**Comment by nazimus** [comment]
This should work :)

`def followers_usernames():
	x = InstagramAPI("username", "password")
	x.login(force = True)
	x.getUserFollowers(user_id) #replace user_id with the id of the person you want to get the followers of
	logs = x.LastJson
	users = []
	for people in logs["users"]:
	  users.append(people["username"])
	return users`

**Comment by nazimus** [comment]
sorry I wasn't able to format the code in the comment :/

**Comment by testingInsta** [comment]
@nazimus Hey! Thanks for your help!

for some reason im getting this error:
File "C:\Python27\Instagram-API-python-master\getuserfollowers.py", line 10, in <module>
    users_fo.append(people["username"])
TypeError: string indices must be integers

I dont know why, but if you use getSelfUserFollowers you can do people["username],, but for other userfollower you cant.

any idea why?
