### ISSUE TITLE
How to print the return value of methods?

### ISSUE THREAD

**Issue by alexcheninfo** [LevPasha/Instagram-API-python#27]
I tried stuff like this:

```
print(InstagramAPI.getSelfUserFollowers())
print(InstagramAPI.getProfileData())
```
But nothing is being logged in the terminal.

Sorry, my background is JavaScript, so maybe I'm doing something wrong.

(By the way, thanks a lot for this API. Everything works perfectly.)

**Comment by ahmdrz** [comment]
@alexcheninfo In this Library , methods doesn't return the result of API , the methods return result of SendRequest method. The result is in `LastJson` ...
So if you want to see result of `InstagramAPI.getSelfUserFollowers()` change it to :
```python
InstagramAPI.getSelfUserFollowers()
print(InstagramAPI.LastJson)
InstagramAPI.getProfileData()
print(InstagramAPI.LastJson)
```

**Comment by alexcheninfo** [comment]
@ahmdrz Thanks man, you saved my life!
