### ISSUE TITLE
getHashtagFeed(tag, next_max_id) can not return all posts

### ISSUE THREAD

**Issue by supernova85** [LevPasha/Instagram-API-python#270]
Hi guys,
I'm using "getHashtagFeed(tag, next_max_id)" which I cann't get the whole posts from a special hashtag. For example I just could collect 5124 posts for the hashtag "milanfashionweek2016" from the whole posts with 8925. The code won't return all posts and for more popular hashtags such as "milanfashionweek" is worse only gets back 10k out of 550K posts. Any one could help me what should I do?

Thank you!

**Comment by BerkBaytar** [comment]
Hi, I am facing with the same problem. next_max_id is not working, it returns as null for getUserFollowers function.
Thanks.

**Comment by supernova85** [comment]
for me as the obtained results, for the lower values of next_max_id it works well however for next_max_id greater than 1000 number of records is not as expected. for example it will return around 800 or something like that.

**Comment by LevPasha** [comment]
Someone have solution?

**Comment by dliliya** [comment]
Has anyone found a solution?
Anybody knows how get count all post for a special hashtags (I need just a number)?
