### ISSUE TITLE
Upload Image

### ISSUE THREAD

**Issue by arslanhashmi** [LevPasha/Instagram-API-python#272]
{'message': "Uploaded image isn't in the right format", 'status': 'fail'}
what should be the exact format?

**Comment by gumdropsteve** [comment]
> 
> 
> This error mean one or all problems:
> 
>     1. Wrong size. Check image sizes (I always upload 800x800, JPG).
> 
>     2. If size is correct, check path of uploaded image (only full OS path required, like `/var/www/example.com/public_html/uploads/...`).
> 
>     3. If 1 and 2 correct, you're using wrong function to open image in your views. Simply rewrite `open()` function to `urlopen()` (use [urllib.request](https://docs.python.org/3/library/urllib.request.html#module-urllib.request) Python 3.x package).



> 
> 
> This error mean one or all problems:
> 
>     1. Wrong size. Check image sizes (I always upload 800x800, JPG).
> 
>     2. If size is correct, check path of uploaded image (only full OS path required, like `/var/www/example.com/public_html/uploads/...`).
> 
>     3. If 1 and 2 correct, you're using wrong function to open image in your views. Simply rewrite `open()` function to `urlopen()` (use [urllib.request](https://docs.python.org/3/library/urllib.request.html#module-urllib.request) Python 3.x package).

Any chance you could help with  #506 @koddr ? Thanks.
