### ISSUE TITLE
Upload non-square pictures

### ISSUE THREAD

**Issue by emiura** [LevPasha/Instagram-API-python#274]
Instagram now allows upload of rectangular pictures, but I can't find a config to do it on this code.

**Comment by emiura** [comment]
Actually, invalid issue.

**Comment by Alzy** [comment]
Hello, I use the InstagramAPI to upload pictures as well though it seems like I can't upload non square pictures... how did you overcome this issue? Does it have something to do with file size?

**Comment by Alzy** [comment]
> Actually, invalid issue.

@emiura Were you able to upload non-square images by default? Mine seems to fail when attempting to upload non square images
