### ISSUE TITLE
Some functions not working anymore

### ISSUE THREAD

**Issue by ekremgurdal** [LevPasha/Instagram-API-python#275]
Last two days, due to Instagram, gettotaluserfollowers and gethashtagfeed functions not working anymore. Does anybody face this problem?

**Comment by n0thingness** [comment]
What are the values of api.LastResponse and api.LastJson that you recieve?

**Comment by ekremgurdal** [comment]
Here is the response: 

Request return 404 error!
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-18-0daa99ab93c8> in <module>()
----> 1 API.getTotalFollowers(str(i))

~/InstagramAPI/__init__.py in getTotalFollowers(self, usernameId)
    724             temp = self.LastJson
    725 
--> 726             for item in temp["users"]:
    727                 followers.append(item)
    728 

KeyError: 'users'

**Comment by ekremgurdal** [comment]
Sorry for bothering everyone. 
The solution is changing user agent to : USER_AGENT = 'Instagram 9.2.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)'

in InstagramAPI.
