### ISSUE TITLE
Rewrite all api method names in a pythonic way 

### ISSUE THREAD

**Issue by moacirmoda** [LevPasha/Instagram-API-python#28]
I suggest that you rewrite all the method names following the PEP8 indication.

Example: Instead **getTotalSelfUserFeed**, the correct way to write this is **get_total_self_user_feed**.

If you accept, I can make a pull request.

**Comment by LevPasha** [comment]
@moacirmoda i don't think we need it (i want to save name from php api, that i copy). If people want if - we can do it. THX!

**Comment by h-2-0** [comment]
@moacirmoda, @LevPasha 

Thanks! it's always a good idea to keep with the Python tradition. However Instagram-API-python is still under construction (just see the TO-DO list) as it is based on a PHP repo. All the functions, names and referenced in the TO-DO list refer to the PHP repository. For me it is easy to check the PHP repo when I am checking the TO-DO list. SO if names are changed here it would be very difficult to keep track of the PHP repo. That's what I think anyway.
