### ISSUE TITLE
How do you get the media_id of an uploaded post

### ISSUE THREAD

**Issue by bs7280** [LevPasha/Instagram-API-python#285]
I am trying to comment on my own post but can not figure out how to get the media_id for a post. My next approach would be to get the most recent posts of a user but I also can't figure out how to get the user_id of a user.

**Comment by Haydardi** [comment]
`#get user_id
InstagramAPI.searchUsername(user)
info = InstagramAPI.LastJson
username_id = info['user']['pk']

InstagramAPI.getUserFeed(username_id)
info = InstagramAPI.LastJson['items']
# comment on latest post
InstagramAPI.comment(info[0]["pk"], 'your comment here')`

**Comment by LevPasha** [comment]
@Haydardi plz make pull request with your example. THX!
