### ISSUE TITLE
How to work around error 429 too many request

### ISSUE THREAD

**Issue by giridharinteg** [LevPasha/Instagram-API-python#287]
I have around 30,000 instagram media and i am getting all user infiormation for the 30k media, So i come around 429 a lot. Please let me know how to work around it.

**Comment by LevPasha** [comment]
Use `time.sleep()` between requests

https://www.tutorialspoint.com/python/time_sleep.htm

**Comment by XGBXGB** [comment]
@LevPasha  Hi, how long does it usually need?
