### ISSUE TITLE
Does anyone know how to skip lines when posting through the API?

### ISSUE THREAD

**Issue by anthonysette** [LevPasha/Instagram-API-python#288]
I have been trying for quite some time with "\n" and other various methods but can't get the caption to have line breaks. Anyone have success, or anyone have any ideas?

**Comment by bs7280** [comment]
Try using %0A instead

https://stackoverflow.com/questions/3871729/transmitting-newline-character-n

**Comment by rikowars** [comment]
How i have to put %0A in my caption to get a newline?
