### ISSUE TITLE
400 while login

### ISSUE THREAD

**Issue by abesmon** [LevPasha/Instagram-API-python#29]
in the beginning i have got some 400 errors and all of them i solved with proving myself in the mobile app. but now i'm receiving 400 error from script and mobile app give no proving notes :(

response from script:
`{u'status': u'fail', u'lock': True, u'message': u'checkpoint_required', u'checkpoint_url': u'https://i.instagram.com/integrity/checkpoint/?next=instagram%3A%2F%2Fcheckpoint%2Fdismiss'}`

i don't know what to do ;( also, this error returned only when i call script from server (which is in USA, while i'm in Russia) and script work perfectly on my local machine.

**Comment by LevPasha** [comment]
Look like instagram block login from other contry. Use Russian proxy from US server, or make one login to your account with US proxy and you will see warning (that you login from other country).

**Comment by abesmon** [comment]
Thanks for your answer so fast!)

Problem is:
just few minutes ago i used proxy on my script and used same proxy on my phone (iOS, if it make any sense), and again i got 400 with checkpoint_required but no warning signs on my phone at all :'( I'm really confused. 

Is it possible, that Instagram made some kind for ban my chain of username+user-agent that is written in python script?

**Comment by LevPasha** [comment]
@abesmon думаю можно по нашенски. Возможно ИГ думает что тебя взломали (много входов с разных ip). Посмотри там где-то бывает вылезает что заходили с неизвестных мест.

**Comment by abesmon** [comment]
@LevPasha можно и так) просто подумал - вдруг кому еще осью пригодится =/

ИГ точно думает, что меня кто-то или ломает или что кто-то уже успешно использует меня и из-за этого такая кутерьма. Я просто не могу добиться, чтобы мне эта чертова плашка вылезла

**Comment by abesmon** [comment]
update из мира сломанных ботов: бот просто внезапно начал работать через 3 дня. Подозреваю, что с него было слишком много запросов/лайков, поэтому его забанили

**Comment by h-2-0** [comment]
@LevPasha , @abesmon 

It would be better if you can write in English so we can all learn in here :) Thanks! :+1:

**Comment by LevPasha** [comment]
@h-2-0 we talk with @abesmon about vodka, balalaika and our tame bear))

**Comment by h-2-0** [comment]
@LevPasha 

hahahahahaha! :rofl:

**Comment by spacerest** [comment]
)))
