### ISSUE TITLE
Running in Linux

### ISSUE THREAD

**Issue by eduaero** [LevPasha/Instagram-API-python#290]
Thank you for such an amazing project!!

I am trying to run it in Linux in order to upload pictures automatically to my Instagram account.
However, I get the following error:

 imageio.core.fetching.NeedDownloadError: Need ffmpeg exe. You can download it by calling: imageio.plugins.ffmpeg.download()

However, because I am running in a Linux envirnoment, I believed that I cannot run the .exe that it is asking for. Does anyone know a different solution to solve it?

Thank you very much beforehand!!

Edu

**Comment by LevPasha** [comment]
Hi. Check new version.

**Comment by eduaero** [comment]
Thank you very much for your answer @levPasha
The new version is not the one in GitHub? I downloaded just today

**Comment by LevPasha** [comment]
@eduaero i don't sure what version you use. If problem in last one - we will mark it as bug, and try to find solution. Today latest version is https://github.com/LevPasha/Instagram-API-python/commit/b7c8d9c6e964739c3424a2a197d65287e4aaed3d

**Comment by eduaero** [comment]
For me it was because I didn't install the repertory properly.
Now it is working perfectly for me. So I guess that there is no bug

Thank you very much :)

**Comment by eduaero** [comment]
For me it was because I didn't install the repertory properly.
Now it is working perfectly for me. So I guess that there is no bug

Thank you very much :)

**Comment by ri7nz** [comment]
@LevPasha  maybe my pull request can solving this problem ? https://github.com/LevPasha/Instagram-API-python/pull/296

**Comment by ekremgurdal** [comment]
https://stackoverflow.com/a/43926264/7291234
