### ISSUE TITLE
Python quit unexpectidly

### ISSUE THREAD

**Issue by arslanhashmi** [LevPasha/Instagram-API-python#292]
on this like in login process, my python 3.6 stops working, previously it was working properly now it is a new problem, 
if (self.SendRequest('si/fetch_headers/?challenge_type=signup&guid=' + self.generateUUID(False), None, True)):

**Comment by LevPasha** [comment]
PLZ send full trace-back.

**Comment by arslanhashmi** [comment]
i can't login through the API.
on this line my code stops.

response = self.s.get(self.API_URL + endpoint) # , verify=False


Wa Salam!
Muhammad Arslan

**Comment by arslanhashmi** [comment]
i am doing the login process in another process, otherwise login is working.

Wa Salam!
Muhammad Arslan

**Comment by arslanhashmi** [comment]
In different process it gives error.

Wa Salam!
Muhammad Arslan

**Comment by LevPasha** [comment]
I can't help you before you show me your code or trace-back.
