### ISSUE TITLE
Exception 

### ISSUE THREAD

**Issue by arslanhashmi** [LevPasha/Instagram-API-python#293]
Why do we get this exception ''InstagramAPI' object has no attribute 'username_id''?

**Comment by LevPasha** [comment]
Show me full trace-back.

**Comment by Joeffison** [comment]
@arslanhashmi It might be that your login failed and you tried to get username_id or to call any method that uses it internally (perhaps, a method with 'Self' in its signature), what would cause the code to raise the exception **AttributeError**. Please, check the credentials you entered. 

If you couldn't fix your problem yet, please share a link to your code.
