### ISSUE TITLE
Fail to import moviepy

### ISSUE THREAD

**Issue by idkaname2use** [LevPasha/Instagram-API-python#294]
Whenever i goto run the test python I automatically get an error telling me it failed to import the moviepy
this is the error:
Fail to import moviepy. Need only for Video upload.
and then it continues to load in my terminal

**Comment by LevPasha** [comment]
@idkaname2use yes. I add this. "moviepy" need only for video upload, so ignore this msg or install "moviepy".

**Comment by idkaname2use** [comment]
I was wondering, because nothing comes up in the terminal after the msg about the moviepy failing to load and I didnt know if that was normal for the terminal to not have anything else in there after.

**Comment by Ethanderson03** [comment]
I have installed moviepy but am still receiving the above error, when I attempt to install moviepy again I get 

Requirement already satisfied: moviepy in /Library/Python/2.7/site-packages (0.2.3.2)
Requirement already satisfied: imageio==2.1.2 in /Library/Python/2.7/site-packages (from moviepy) (2.1.2)
Requirement already satisfied: tqdm==4.11.2 in /Library/Python/2.7/site-packages (from moviepy) (4.11.2)
Requirement already satisfied: numpy in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from moviepy) (1.8.0rc1)
Requirement already satisfied: decorator==4.0.11 in /Library/Python/2.7/site-packages (from moviepy) (4.0.11)
Requirement already satisfied: pillow in /Library/Python/2.7/site-packages (from imageio==2.1.2->moviepy) (5.2.0)

**Comment by ab5olute** [comment]
> I have installed moviepy but am still receiving the above error, when I attempt to install moviepy again I get

- **First**": (sudo) _pip install imageio_, if necessary.
- **Now**: _import imageio_ and then _imageio.plugins.ffmpeg.download()_

That's it.
