### ISSUE TITLE
Auto Following

### ISSUE THREAD

**Issue by idkaname2use** [LevPasha/Instagram-API-python#295]
Hi, sorry to ask questions that are a little on the dumb side, but I have been toying with this python script and editing it with my  own # and have not been able to get the script to auto follow people under the # and was wondering if it was possible that someone could help me just fix it so it will run for me! thank you for your time.

**Comment by dunky11** [comment]
Heres an example, its my function which follows followActions people under the hashtag

import random
import time
from InstagramAPI import InstagramAPI

instaApi = InstagramAPI(yourUsername, YourPassword)
instaApi.login()


def followHashtag(hashTag, followActions, timeBetween):
    
    if(hashTag[0] == "#"):
        print("Error, please dont use a hashtag.")
        return
    
    instaApi.getHashtagFeed(hashTag, "")
    tagFeedJson = instaApi.LastJson["items"]
    
    lenTagFeed = len(tagFeedJson)
    
    if(followActions > lenTagFeed):
        followActions = lenTagFeed

    i = 0
    while(i < followActions):
        
        username = tagFeedJson[i]["user"]["username"]
        userPk = tagFeedJson[i]["user"]["pk"]
        
        instaApi.userFriendship(userPk)
        if(instaApi.LastJson["following"]):
           print("Already following instagram.com/", username, ", getting next user.", sep="")
           
           if(followActions < lenTagFeed):
               followActions += 1
               
        else:
           instaApi.follow(userPk)
           print("Following: instagram.com/", username, sep="")
           
        sleeptime = random.uniform(5, 5 + timeBetween)
        print("Sleeping for", sleeptime, "seconds.")
        print()
        time.sleep(sleeptime)
        i += 1
