### ISSUE TITLE
getUserFollowers returns 404 error

### ISSUE THREAD

**Issue by rcolpo** [LevPasha/Instagram-API-python#299]
I could successfully use "getSelfUserFollowers" but when I try to get the Instagram followers of any other public profile, with getUserFollowers, I always get the error below:

"Request return 404 error!
False"

OR

"Except on SendRequest (wait 60 sec and resend): ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
Request return 404 error!
False"

The code I'm using is:

api = InstagramAPI("username", "password")  # my username and password
api.login()
api.getUserFollowers("ladygaga") # for instance. but could be any other public profile, even with very little followers.

I'm using Python 2.7.12 on the interactive shell idle. I'm using Ubuntu and am simultaneously accessing Instagram on internet browser. Does any of this have any effect on the error message I'm receiving, or is the script above wrong?

Thanks.

**Comment by dunky11** [comment]
i get "Request return 404 error! False" too.

To call the function getUserFollowers() you need the pk (i think it means private key) of the user.
Whenever calling a function its return gets stored in api.LastJson, there are functions out there to print Json data, you can use the one i found below.

Try;

import Json
from InstagramAPI import InstagramAPI

def printJsonDict(json_object):
    print(json.dumps(json_object, sort_keys=True, indent=4, separators=(',', ': ')))

api = InstagramAPI("username", "password") # my username and password
api.login()
api.searchUsername("ladygaga")
usernameJson = instaApi.LastJson    #LastResponseJson
printJsonDict(usernameJson)    #printJsonData



searchUsername() takes the string of the Username, not the privateKey, to thats the way to go for you

**Comment by rcolpo** [comment]
Thank you a lot dunky11,

Your code had some typos, but was excellent! Thank you so much. I'm leaving bellow an adapted and extended version of your code, just for the record, in case some else has the same doubt I had. 

import re
from InstagramAPI import InstagramAPI

api = InstagramAPI("myUsername", "myPassword")  # my username and password
api.login()
api.searchUsername("ladygaga")  # the InstagramUserID you want to know the followers
usernameJson = api.LastJson
pkString = re.findall("(?<=pk\'\: )[0-9]*", str(usernameJson))[0] # finds the pk numeral code

api.getUserFollowers(int(pkString))
followers = api.LastJson

followersList = re.findall("(?<=username\'\: u\').*?(?=\',)", str(followers)) # finds the UserID of the followers and creates a list
len(followersList)
