### ISSUE TITLE
mathod getSelfUsersFollowing return json only 200 users

### ISSUE THREAD

**Issue by buzzo123** [LevPasha/Instagram-API-python#3]
the method getSelfUsersFollowing return a json with only the first 200 users, how can i take all the followings? thanks

**Comment by LevPasha** [comment]
@buzzo123 hi! I don't use this api, i just make php->json. Try to find some info on php version.

**Comment by kaxil** [comment]
Hi @LevPasha , I have the same issue, the maxid parameter isn't working, have you fixed this error !!

**Comment by torlakfaruk** [comment]
@buzzo123 @kaxil firstly you need to get "next_max_id" and put it on next_id
And you need to change codes like this: InstagramAPI.getUserFollowers(self,usernameId=user_id,maxid="PUT_NEXT_MAXID")
and
return self.SendRequest('friendships/'+ str(usernameId) +'/followers/?max_id='+ str(maxid)
            +'&ig_sig_key_version='+ self.SIG_KEY_VERSION +'&rank_token='+ self.rank_token,user_id=usernameId)

I use this and can get all followers. But sometimes instagram doesn't give more than 50.000 accounts.

**Comment by kaxil** [comment]
@torlakfaruk Thanks buddy.. I forget to update it.. I tried it couple of days back & it worked..

**Comment by ahmdrz** [comment]
Hi everyone , 
I wrote this code and successfully worked for me , thanks @torlakfaruk 

```python
def getTotalFollower(self,usernameId):
        followers = []
        next_max_id = ''
        while 1:
            self.getUserFollowers(usernameId,next_max_id)
            temp = self.LastJson

            for item in temp["users"]:
                followers.append(item)
            
            if temp["big_list"] == False:
                return followers            
            next_max_id = temp["next_max_id"]  
```

**Comment by LevPasha** [comment]
@ahmdrz thx, please make pull request!

**Comment by buzzo123** [comment]
i change to this, so if for some reason the code can't read the page, the program retry until works (and wait 3 min every error captured):

`def getTotalFollowersID2(self,usernameId):
        followers = []
        next_max_id = ''
        temp = []
        g = self.getUserFollowers(usernameId,next_max_id)
        temp = self.LastJson
        while 1:
            while g==False:
                print("wait")
                time.sleep(3*60)
                g = self.getUserFollowers(usernameId,next_max_id)
                temp = self.LastJson


            for item in temp["users"]:
                followers.append(item)

            if temp["big_list"] == False:
                return followers
            next_max_id = temp["next_max_id"]
            g = self.getUserFollowers(usernameId,next_max_id)
            temp = self.LastJson`

**Comment by aaisataev** [comment]
My command looks like this:

```
from InstagramAPI import InstagramAPI

InstagramAPI = InstagramAPI("login", "pass")
InstagramAPI.login() # login
InstagramAPI.getTotalFollowers("15xxx02")
print(InstagramAPI.LastJson)
```

And it still returns me 200 followers. What am I doing wrong?

**Comment by danilobrandao** [comment]
@aaisataev I am having the same problem, although I am getting only 136 followers when the right number should be 329.
