### ISSUE TITLE
ImportError: No module named requests with python 2.7 

### ISSUE THREAD

**Issue by Tolmino** [LevPasha/Instagram-API-python#303]
hi, i have installed today and i have copy the InstagramAPI directory in my site '/usr/lib64/python2.7/site-packages', and i have too this error:

./test.py
Traceback (most recent call last):
File "./test.py", line 6, in
from InstagramAPI import InstagramAPI
File "/usr/lib64/python2.7/site-packages/InstagramAPI/init.py", line 2, in
from . import InstagramAPI
File "/usr/lib64/python2.7/site-packages/InstagramAPI/InstagramAPI.py", line 4, in
import requests
ImportError: No module named requests

i have tried to modify File "/usr/lib64/python2.7/site-packages/InstagramAPI/init.py", with all suggested import string that i have found but i haven't had success .
where i'm wrong ?

**Comment by ri7nz** [comment]
before you run test.py , are you sure has been install all of requirement.txt ?

if no, 
```
$ pip install -r requirement.txt # or
$ pip install requests or
$ pip install requests --user
```
thanks you very much

**Comment by Tolmino** [comment]
yes,
and if i relaunch i have:

pip install -r requirements.txt 
Requirement already satisfied: requests==2.11.1 in /usr/lib/python3.4/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: requests-toolbelt==0.7.0 in /usr/lib/python3.4/site-packages (from -r requirements.txt (line 2))
Collecting moviepy==0.2.2.11 (from -r requirements.txt (line 3))
  Using cached moviepy-0.2.2.11.tar.gz
Requirement already satisfied: numpy in /usr/lib64/python3.4/site-packages (from moviepy==0.2.2.11->-r requirements.txt (line 3))
Requirement already satisfied: decorator in /usr/lib/python3.4/site-packages (from moviepy==0.2.2.11->-r requirements.txt (line 3))
Requirement already satisfied: imageio in /usr/lib/python3.4/site-packages (from moviepy==0.2.2.11->-r requirements.txt (line 3))
Requirement already satisfied: tqdm in /usr/lib/python3.4/site-packages (from moviepy==0.2.2.11->-r requirements.txt (line 3))
Requirement already satisfied: pillow in /usr/lib64/python3.4/site-packages (from imageio->moviepy==0.2.2.11->-r requirements.txt (line 3))
Installing collected packages: moviepy
  Found existing installation: moviepy 0.2.3.2
    Uninstalling moviepy-0.2.3.2:
      Successfully uninstalled moviepy-0.2.3.2
  Running setup.py install for moviepy ... done
Successfully installed moviepy-0.2.2.11

**Comment by Perados** [comment]
@Tolmino your pip defaults to python 3.4 : Requirement already satisfied: requests==2.11.1 in /usr/lib/**python3.4**/site-packages (from -r requirements.txt (line 1)) ...

**Comment by Tolmino** [comment]
right....
i'haven't noticed it before

**Comment by Tolmino** [comment]
in fact i have a symbolic link /usr/bin/python --> python2.7

/usr/bin/python3.4 test.py 
Request return 400 error!
{'status': 'fail', 'message': 'Sorry, there was a problem with your request.', 'error_type': 'sentry_block'}
Can't login!

Now i can call it
