### ISSUE TITLE
uploadPhoto : 500 Error "Unknown Server Error"

### ISSUE THREAD

**Issue by makevalues** [LevPasha/Instagram-API-python#306]
Hello everyone

When I perform uploadPhoto after login, I get 500 Error {'message': 'Unknown Server Error.', 'Status': 'fail'}. Of course not uploaded. What causes it?
I uploaded well until yesterday, but I can not run it today.
The sample in the "examples" directory (upload_photo.py) also generates the same error.

Thank you very much in advance for your answer.

**Comment by bisak** [comment]
I have the exact same issue.

**Comment by hanachan1026** [comment]
Same issue here. Any ideas?

**Comment by mekevalues** [comment]
This seems to be related to EXIF.
I removed the EXIF value and the problem is resolved.

**Comment by LevPasha** [comment]
@makevalues @bisak @hanachan1026 guys, make a pull if you have a solution. Thx!

**Comment by aaron-michaux** [comment]
I've got the same problem. btw, there's no "one" EXIF value.

**Comment by bisak** [comment]
Can't remember exactly what I did to resolve the issue since I was fiddling with it a long time ago. As far as I recall I used something like Paint.NET to convert the pictures to .jpg and did some minor resizing (that also corrects the EXIF data to some extend). There's bulk actions plugin that comes in handy.

**Comment by usamaejaz** [comment]
Just a note: This error also happens when there is a genuine server-side error at Instagram. It's not always your own fault.

**Comment by Subterraneus** [comment]
same problem and it keeps happening erasing the exif data.

**Comment by aliazizi** [comment]
same problem

**Comment by MacsInSpace** [comment]
Same error here.
I tried adding:
`from PIL import Image`
up top. 
And then:
`image = Image.open(photo)
 image.save(photo)`
right before the upload line:
`igapi.uploadPhoto(photo,caption=IGCaption,upload_id=None)`
to strip EXIF data without success. 
Still getting 500 server errors.

**Comment by aliazizi** [comment]
@mgp25 you should mark this issue as open

**Comment by MacsInSpace** [comment]
It seems to be working without removing EXIF data now. (for me at least.) It most likely was a server side issue.

**Comment by aliazizi** [comment]
For me sometime it's working sometime it's not also i try it in same photo
