### ISSUE TITLE
Unable to log in 

### ISSUE THREAD

**Issue by GlowMLG** [LevPasha/Instagram-API-python#310]
I'm trying to see how this works but whenever I try one of the examples I get this challenge error:

> Fail to import moviepy. Need only for Video upload.
> Request return 400 error!
> {'message': 'challenge_required', 'challenge': {'url': 'https://i.instagram.com/challenge/5627820565/(confirmation code that changes every time)/', 'api_path': '/challenge/5627820565/(confirmation code that changes every time)/', 'hide_webview_header': True, 'lock': True, 'logout': False, 'native_flow': True}, 'status': 'fail', 'error_type': 'checkpoint_challenge_required'}
> Traceback (most recent call last):
>   File "get_all_comments.py", line 18, in <module>
>     API.getUsernameInfo()
> TypeError: getUsernameInfo() missing 1 required positional argument: 'usernameId'
> 

First of all, I don't need moviepy so that's not the problem. I've already verified my phone number on IG and I still have to confirm it manually with the challenge when I go to that link.

What am I doing wrong? Thanks

**Comment by quantum2111** [comment]
Hi!
When you took this error, open IG account on smartphone and tap "It was me" and try to run your code again.
About moviepy:
`import imageio
imageio.plugins.ffmpeg.download()`
