### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by arthurecommerce** [LevPasha/Instagram-API-python#312]
Hey guys !

Thank you for this amazing project !
Do you know how I can post emojis (in comments or captions) ?

**Comment by ekremgurdal** [comment]
Did you try to search this question in closed issues?

**Comment by quantum2111** [comment]
Hi!
Just find emojis list, copy and paste to IDE. But not all emojis are supported.
Or you can try to create empty Microsoft Word document, open this doc on you smartphone and paste needed emojis. Then open doc on PC and paste to IDE.
