### ISSUE TITLE
proxy + useragent to avoid ban

### ISSUE THREAD

**Issue by rcolpo** [LevPasha/Instagram-API-python#314]
Hi folks,

I'm about to start using API to follow, unfollow, like media and write comments for a single Instagram account (I already wrote the code). Because I will be only using it for a single account, does it make sense to use proxy? I'm not sure what is the useragent function or how to use it. Does anyone mind to suggest names of proxy and useragent softwares that would do the job? (I'm thinking about running the python script on my computer - not sure if it's possible to use it on the phone.)
What is a safe time between every follow/unfollow/like/comment action? I suppose like/comment actions demand a longer wait time.

**Comment by rcolpo** [comment]
I have just noticed the function setProxy(). So, by setting up a proxy it was meant to just use the command api.setProxy() after login? 

```
api.login()
api.setProxy()
```

Or should be before login? I'm still unsure about what the useragent means.

**Comment by GitBib** [comment]
@rcolpo Of course, before the entrance. You can use up to 5 accounts per 1 ip

**Comment by GitBib** [comment]
api.setProxy(proxy="user:password@ip:port")
api.login()

**Comment by rcolpo** [comment]
In the string "user:password@ip:port" should I change "user" by my instagram user? The "password" by my Instagram password? should I change "ip" and "port" by some ip and port values? What should this values be?
Thank you!

**Comment by GitBib** [comment]
@rcolpo login and password should be used from the proxy server

**Comment by rcolpo** [comment]
Thank you. I have just seen that an proxy address consists of an ip and port. So I believe that that "ip" and "port" should be replaced with the proxy information. 
Does it make sense to use proxy to make my Instagram account less prone to be banned even if I'm using Instagram-API-python on a single account? Or it only make sense to use proxy if I'm accessing Instagram on multiple accounts?

**Comment by mehrab-wj** [comment]
its socks5 proxy or http ?
and if proxies not have username and password , how i can use it ?

**Comment by GitBib** [comment]
@mehrab-wj Do not write login and password.
api.setProxy("ip:port")
api.login()

**Comment by GitBib** [comment]
#317 @mehrab-wj

**Comment by mehrab-wj** [comment]
@GitBib i will test it .
Thanks ❤️

**Comment by mtalhagaoglu** [comment]
is it true?
api = InstagramAPI(nickname,password)
InstagramAPI.setProxy(ip:port)
api.login()
