### ISSUE TITLE
Anonymous access to public accounts?

### ISSUE THREAD

**Issue by julianodorneles** [LevPasha/Instagram-API-python#316]
Is there some way to get the last JSON of a public account?

What I mean: get the last post of a public account (but without use login credentials).

**Comment by ri7nz** [comment]
```python

import requests as req
import json

ig = req.get('https://instagram.com/{user}/?__a=1'.format(user=username))
data = ig.json()['user']
if req.status_code == 200:
   print data
```

**Comment by LevPasha** [comment]
@julianodorneles i think it is impossible wit this API. Try to use web version as on example.
