### ISSUE TITLE
Direct messaging

### ISSUE THREAD

**Issue by xmsid** [LevPasha/Instagram-API-python#319]
The lib should have a better direct messaging system so that anyone can make dm bots, and why is the repo so abandoned?

**Comment by ri7nz** [comment]
you can try this for bot program https://github.com/instabot-py/instabot.py

**Comment by werthd** [comment]
Is it possible to download a whole chat ?

**Comment by Seriusam** [comment]
@ri7nz Hey! Would you say that I could use instabot and this program in the same time simultaneously ?

**Comment by ri7nz** [comment]
@Seriusam no,i'm just share that bot . thank you

**Comment by LevPasha** [comment]
@xmsid i have no much free time. Do you want to help? Also this repo not a bot.
