### ISSUE TITLE
return 400 error

### ISSUE THREAD

**Issue by lemkova** [LevPasha/Instagram-API-python#32]
i think the api isnt working, i've test this from my home computer and also my cloud server.

both return 400 response
```
C:\Users\lemkova\Instagram-API-python>python test.py
Request return 400 error!
```

**Comment by lemkova** [comment]
ah my bad, it's authentication issue.

**Comment by danielb1234** [comment]
Hey @lemkova what do you mean with authentication issue because I keep getting this error?

Thanks

**Comment by lemkova** [comment]
@danielb1234 
when first login your account, instagram will ask for auth. try open your instagram official app(or instagram.com) when you first run the script. sorry for my english xD
