### ISSUE TITLE
AttributeError: 'InstagramAPI' object has no attribute 'token'

### ISSUE THREAD

**Issue by jockefardig** [LevPasha/Instagram-API-python#323]
Hi, I get the "Request return 400 error!" when trying the test.py. The error message reads like this at the end:

{'two_factor_required': True, 'message': '', 'two_factor_info': {'obfuscated_phone_number': '1814', 'show_messenger_code_option': False, 'username': 'demojdis', 'phone_verification_settings': {'resend_sms_delay_sec': 60, 'robocall_count_down_time_sec': 30, 'max_sms_count': 2, 'robocall_after_max_sms': True}, 'two_factor_identifier': 'Kjk5r8Puz3'}, 'phone_verification_settings': {'resend_sms_delay_sec': 60, 'robocall_count_down_time_sec': 30, 'max_sms_count': 2, 'robocall_after_max_sms': True}, 'status': 'fail'}
Can't login!

And when trying to run upload script I get this at the end...

Traceback (most recent call last):
  File "upload_photo.py", line 13, in <module>
    InstagramAPI.uploadPhoto(photo_path, caption=caption)
  File "/home/pi/Instagram-API-python/InstagramAPI/InstagramAPI.py", line 146, in uploadPhoto
    '_csrftoken': self.token,
AttributeError: 'InstagramAPI' object has no attribute 'token'

I'm just wondering if I need to get a token in some way and specify it somewhere or if this has to do with something else? All help appriciated!

**Comment by ri7nz** [comment]
are you activated 2 step auth factory on your instagram account ? if yes please disable if you want to use this package

**Comment by nikifot** [comment]
I get the same error and do not have 2-step auth on my account!

**Comment by jockefardig** [comment]
By some reason I thought I had read that the 2-step verification was supposed to be enabled. I disabled it and it works like a charm. Thanks ri7nz!

**Comment by alirezaafzalaghaei** [comment]
I have the same issue today:(

**Comment by confusedgorkha** [comment]
'_csrftoken': self.token,
AttributeError: 'InstagramAPI' object has no attribute 'token'

**Comment by Chadhendrixs** [comment]
> ```
> '_csrftoken': self.token,
> ```
> AttributeError: 'InstagramAPI' object has no attribute 'token'

I've had the same error, and I've never had 2 factor on. Earlier today it was working (my login logs show that on instagram) but after that point I got this error.

**Comment by lena-abarova** [comment]
any news on how to pass "checkpoint_required"?
