### ISSUE TITLE
Text with Latin characters 

### ISSUE THREAD

**Issue by rcolpo** [LevPasha/Instagram-API-python#327]
Hi all!

Is it possible to comment using Latin characters? 
I receive an error if I try to comment using Latin characters, as below: 

api.comment(userPk, "é ç")

The same happens if I send private messages with characters that don't exist in English. 

Is there any way to solve this?

Thanks!

**Comment by hanachan1026** [comment]
I got the same issue

**Comment by rcolpo** [comment]
I changed to pyhon 3 and this was solved.
