### ISSUE TITLE
Get Recent Media of a User

### ISSUE THREAD

**Issue by DjStorm** [LevPasha/Instagram-API-python#329]
Hey guys!
The Instagram API has a function to get the recent media a user published on his account [See here](https://www.instagram.com/developer/endpoints/users/#get_users_media_recent)

I wanted to implement it into the the python API. Therefore I wanted to create a getLastXPosts-Function. Unfortunately I always get 404 Error when I call it. Can somebody maybe give me a hint why it doesn't work? Or is there another option to get the last x posts a user has published on his instagram account in python?

```
    def getLastXPosts(self, usernameId, count):
        data = json.dumps({'_uuid': self.uuid,
                           '_uid': self.username_id,
                           '_csrftoken': self.token})
        return self.SendRequest('users/' + str(usernameId) + '/media/recent/?count=' + str(count), self.generateSignature(data))
```

Thanks in advance!

**Comment by Jame-Stitel** [comment]
Hey, did you get this working?

**Comment by Jame-Stitel** [comment]
Hey @DjStorm

**Comment by DjStorm** [comment]
def LikeLastXPostsThenFollow(self, usernameId, count):
        self.getUserFeed(usernameId)
        i = 0
        # Like Pictures is profile is public
        if 'items' in self.LastJson:
            info = self.LastJson['items']
            for media in info:
                if (media['caption']!=None):
                    self.like(str(media['caption']['media_id']))

**Comment by Jame-Stitel** [comment]
thanks @DjStorm 

I know I should probably be able to do it by myself, but how should I implement the "count" you have it there as a parameter, but then it is not used in the function

**Comment by DjStorm** [comment]
count is just an integer describing how many of the recent media shall be liked.
