### ISSUE TITLE
'DownloadThead' is not defined?!

### ISSUE THREAD

**Issue by werthd** [LevPasha/Instagram-API-python#330]
Hello, when i try to run the
 `python3 thread_download.py`
 i get the error 
`Traceback (most recent call last):
  File "thread_download.py", line 69, in <module>
    inst = DownloadThead(InstagramAPI, thread_id)
NameError: name 'DownloadThead' is not defined
` 
any idea how to fix this ? Thanks

**Comment by Seriusam** [comment]
You are misspelling DownloadThread. Look at the line you have written,
`inst = DownloadThead(InstagramAPI, thread_id)`

It should be ,
`inst = DownloadThread(InstagramAPI, thread_id)`

**Comment by Seriusam** [comment]
Oh Nvm, I just checked it again and it is a misspelling in the file in the repository. Just try replacing the line with
`inst = DownloadThead(InstagramAPI, thread_id)`
With the line below,
`inst = DownloadThread(InstagramAPI, thread_id)`

Note: I haven't tried it, but just speaking from observation.

**Comment by LevPasha** [comment]
https://github.com/LevPasha/Instagram-API-python/pull/332
