### ISSUE TITLE
How to get all media likers? 

### ISSUE THREAD

**Issue by hossein9118** [LevPasha/Instagram-API-python#333]
I am trying  to get all the likers of a meedia .
I am using : 
```
API.getMediaLikersm('media_id')
likers=API.LastJson
```

When i use 
`len(g['users'])
`The answer is 1001 while the actual number of likers is 8000. How can i get all likers username? please help 
Thanks

**Comment by carpediemzak** [comment]
how do you get the media_id ?

**Comment by hossein9118** [comment]
I use this method ; 
Right click on a photo and open in a new tab/window. Right click on inspect element. Search for:

instagram://media?id=

This will give you:

instagram://media?id=############# /// the ID

https://stackoverflow.com/questions/16758316/where-do-i-find-the-instagram-media-id-of-a-image

**Comment by hossein9118** [comment]
@xecgr  Can you help me? please 🙏

**Comment by xecgr** [comment]
@hossein9118 have a look to this example: https://github.com/LevPasha/Instagram-API-python/blob/master/examples/get_all_comments.py
Changing comments by likes you will get what you are looking for

**Comment by arthur-barsegyan** [comment]
@hossein9118 Yeah, I have this problems too.

**Comment by sleepywhiskey** [comment]
sure there's no way to get max_id neither has_more_likes or has_next_page for likers. @LevPasha  please reopen this issue

**Comment by xecgr** [comment]
Since this endpoint doesn't return any pagination parameter, I worry that it can't be iterated until the end
In php very-well-maintained-lib seems to be the same issue: https://github.com/mgp25/Instagram-API/blob/1699e99b8595a9ffc18fe8c26b26516ac4274bbc/src/Request/Media.php#L230

**Comment by Arseka44** [comment]
Guys, how can we get usernames of all likers without other info???

**Comment by arthur-barsegyan** [comment]
As I know — we can't

пн, 12 нояб. 2018 г., 23:49 Arseka44 notifications@github.com:

**Comment by corncobb** [comment]
> Guys, how can we get usernames of all likers without other info???

`from InstagramAPI import InstagramAPI

likes_list = []

def get_likes_list(username):

    API.searchUsername(username) #Gets most recent post from user
    info = API.LastJson
    username_id = info['user']['pk']
    user_posts = API.getUserFeed(username_id)
    info = API.LastJson
    media_id = info['items'][0]['id']

    API.getMediaLikers(media_id)
    f = API.LastJson['users']
    for x in f:
        likes_list.append(x['username'])

get_likes_list("tailopez")
print(likes_list)`

**Comment by corncobb** [comment]
> Guys, how can we get usernames of all likers without other info???

Check out my example [here](https://stackoverflow.com/questions/29058661/how-to-get-all-likes-for-a-given-media-id/54838330#54838330).
