### ISSUE TITLE
Need link for the documentation

### ISSUE THREAD

**Issue by udit-001** [LevPasha/Instagram-API-python#334]
I can't find the documentation to be able to use this wrapper :/

**Comment by ri7nz** [comment]
@udit-001 
you can try, practice, & do this example 
https://github.com/LevPasha/Instagram-API-python/tree/master/examples

**Comment by ice1x** [comment]
I assume it should be similar to https://github.com/mgp25/Instagram-API/wiki
since this project was forked there
