### ISSUE TITLE
Sentry block

### ISSUE THREAD

**Issue by Idrisskh** [LevPasha/Instagram-API-python#336]
Hi,

I am running 4 scripts on the same VPS with the same IP, each script is making a request to the API every 1 - 2 second (randomly). 
After some hours, each script received a sentry block error from Instagram. I have tried to wait 24h and then run again the scripts and after few time, same issue. The 4 Instagram accounts used by the scripts where created with the VPS IP (they are quite new and empty) and where phoned verified (1 phone number for 2 Instagram account). Has anyone faced the same issue ? Do you think that the speed is to high ? Should I try switching IP on the VPS ? Reduce the number of scripts with the same IP ? Use old Instagram accounts ?

Thank you for you answer,

**Comment by LevPasha** [comment]
Too much parameters. Proxy, account age, phone\email verify, connect with FB and etc. Test it yourself.
