### ISSUE TITLE
How do I get a list of followers

### ISSUE THREAD

**Issue by Jame-Stitel** [LevPasha/Instagram-API-python#338]
Hey, how can I get a list of usernames of my followers. Just a list of the usernames, nothing else, in txt or sth..

**Comment by JoaoGarcez** [comment]
i'm trying the same but i just can get a list of followers with 200 followers maximum, i don't know why this is happening. if anyone could help would be great

**Comment by Joeffison** [comment]
@Jame-Stitel @JoaoGarcez Hi guys!

Please, try the code below. If you can't get it to work, share the link to your code on github and I will try to be helpful. :)

```
api = InstagramAPI(username, password)
api.login()
followers = api.getTotalSelfFollowers()
```

**Comment by JoaoGarcez** [comment]
@Joeffison worked for profiles with a small number of followers like 900 followers. when the number is to high gives error

**Comment by Joeffison** [comment]
I had the code below before, but I thought it wouldn't be necessary.
Sorry if it's going to give you the same error.
I don't have an account with this amount of followers to test.

```
class MyInstagramAPI:
    def __init__(self, username, password, user_id):
        self.username = username
        self.password = password
        self.user_id = user_id

        self.api = InstagramAPI(self.username, self.password)
        self.api.login()

    def __getFollwxs(self, api_function):
        following = []
        next_max_id = True
        while next_max_id:
            # first iteration hack
            if next_max_id == True: next_max_id = ''
            _ = api_function(self.user_id, maxid=next_max_id)
            following.extend(self.api.LastJson.get('users', []))
            next_max_id = self.api.LastJson.get('next_max_id', '')
        return following

    def getFollowings(self):
        return self.__getFollwxs(self.api.getUserFollowings)

    def getFollowers(self):
        return self.__getFollwxs(self.api.getUserFollowers)
```

PS: @Jame-Stitel did you solve your problem? If you want only the usernames, you can use list comprehension to extract the 'usersame' attribute from the 'followers' list on my last answer.

**Comment by Jame-Stitel** [comment]
Yes, I got it working for my profile (22k followers) this is the code:


#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Use text editor to edit the script and type in valid Instagram username/password

from InstagramAPI import InstagramAPI

api = InstagramAPI("username", "password")
api.login()  # login
"""
api.getSelfUserFollowers()
"""
# api.getUserFollowers(media_id["ranked_items"][0]["user"]["pk"])  # get first media owner followers# #
"""
print(api.LastJson.get('users', []))
"""

# instagram id of the user you want to get the followings of
user_id = '1461295173'

# GET FOLLOWERS
followers = []
next_max_id = True
while next_max_id:
    # first iteration hack
    if next_max_id is True:
        next_max_id = ''
    _ = api.getUserFollowers(user_id, maxid=next_max_id)
    followers.extend(api.LastJson.get('users', []))
    next_max_id = api.LastJson.get('next_max_id', '')

unique_followers = {
    f['username']: f
    # username vs pk (for id)
    for f in followers
}

# Output all the IDs

for f in unique_followers:
    print(str(f))

**Comment by Jame-Stitel** [comment]
`#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Use text editor to edit the script and type in valid Instagram username/password

from InstagramAPI import InstagramAPI

api = InstagramAPI("jame_stitel", "upv-kxK-uyM-u3F")
api.login()  # login
"""
api.getSelfUserFollowers()
"""
# api.getUserFollowers(media_id["ranked_items"][0]["user"]["pk"])  # get first media owner followers# #
"""
print(api.LastJson.get('users', []))
"""

# instagram id of the user you want to get the followings of
user_id = '1461295173'

# GET FOLLOWINGS
followers = []
next_max_id = True
while next_max_id:
    # first iteration hack
    if next_max_id is True:
        next_max_id = ''
    _ = api.getUserFollowers(user_id, maxid=next_max_id)
    followers.extend(api.LastJson.get('users', []))
    next_max_id = api.LastJson.get('next_max_id', '')

unique_followers = {
    f['username']: f
    # username vs pk (for id)
    for f in followers
}

# Output all the IDs

for f in unique_followers:
    print(str(f))`

**Comment by LevPasha** [comment]
Guys, can you create "example.py" with your code and make pull? Thank you!

**Comment by clcox11** [comment]
I tried copy/paste Jame Stitel's solution with different user/pass but I'm still getting an incorrect amount of followers

**Comment by faniefikri** [comment]
> Yes, I got it working for my profile (22k followers) this is the code:
> 
> #!/usr/bin/env python
> #-_- coding: utf-8 -_-
> 
> #Use text editor to edit the script and type in valid Instagram username/password
> 
> from InstagramAPI import InstagramAPI
> 
> api = InstagramAPI("username", "password")
> api.login() # login
> """
> api.getSelfUserFollowers()
> """
> #api.getUserFollowers(media_id["ranked_items"][0]["user"]["pk"]) # get first media owner followers# #
> """
> print(api.LastJson.get('users', []))
> """
> 
> #instagram id of the user you want to get the followings of
> user_id = '1461295173'
> 
> #GET FOLLOWERS
> followers = []
> next_max_id = True
> while next_max_id:
> # first iteration hack
> if next_max_id is True:
> next_max_id = ''
> _ = api.getUserFollowers(user_id, maxid=next_max_id)
> followers.extend(api.LastJson.get('users', []))
> next_max_id = api.LastJson.get('next_max_id', '')
> 
> unique_followers = {
> f['username']: f
> # username vs pk (for id)
> for f in followers
> }
> 
> #Output all the IDs
> 
> for f in unique_followers:
> print(str(f))

I get following error list
Fanie-Fikri-MacBook-Pro:desktop faniefikri$ python getfollowerlist.py
  File "getfollowerlist.py", line 26
    if next_max_id is True:
     ^
IndentationError: expected an indented block
