### ISSUE TITLE
Max number follows per day

### ISSUE THREAD

**Issue by rcolpo** [LevPasha/Instagram-API-python#339]
I'm currently following 280 people per day without any problem. However, I suppose there is a limit for the number of people I can safely follow on the same day, and if I follow a too many people on the same day I might be temporarily banned. 
What is the number of people you safely follow on the same day? Or, what is the interval between each new follow that you use?

**Comment by LevPasha** [comment]
Too much parameters. Proxy, account age, phone\email verify, connect with FB and etc. Test it yourself.
