### ISSUE TITLE
Setup ???

### ISSUE THREAD

**Issue by BatuhanKahraman** [LevPasha/Instagram-API-python#35]
Im newuser for python. How to setup this ? Thnks

**Comment by ahmdrz** [comment]
After python 3 installed on your system , Clone this repository ,
Copy InstagramAPI.py to your project directory.
Copy test.py to your project directory.

if you are Linux guy ,
cd <path_to_your_project_directory>
python3 test.py

**Comment by BatuhanKahraman** [comment]
thnks for reply bro. I using windows . Project directory in C:\Python27 ???

**Comment by ahmdrz** [comment]
Ur Welcome dude ,

No , I mean your new project , your new project for Instagram. 

And No ! This repo used python3. 

You have to use python3.

You can change some codes to python2 or you can something like [this](https://github.com/ahmdrz/instagram-statistics/blob/master/insta.py) ...

**Comment by BatuhanKahraman** [comment]
Thnks Bro... I try in p3...

**Comment by torlakfaruk** [comment]
@BatuhanKahraman hocam yapmak istediğini ve problemleri yazabilirsen Türkçe de yardım edebilirim.

**Comment by BatuhanKahraman** [comment]
Merhaba Dostum... Python ile bu dağıtılan python kodunu compile edip command line üzerinde çalıştırmak istiyorum. Hesaplar sıkıntıya düşermi diyede düşünüyorum. Milleti takip edecek otomatik bir sistem yazmak istiyorum.

**Comment by torlakfaruk** [comment]
Burdaki dosyaları proje dosyasına kaydettikten sonra hesaplar için açacağın python dosyalarında import etmen gerekiyor. Bu şekilde kullanabilirsin kodu. Çok yoğun işlem yapmadığın sürece de hesaplar ile ilgili kolay kolay bir problem oluşmaz. Ben kullanıyorum. Hatta dışarıya da bir hizmet olarak sunuyorum. Süreçte yine bir problem olursa sorabilirsin.

**Comment by ranman034** [comment]
@ahmdrz after running python test.py in my applications folder I'm getting the error message
`Traceback (most recent call last):
  File "test.py", line 7, in <module>
    InstagramAPI.login() # login
  File "F:\djcode\picsearch\InstagramAPI.py", line 66, in login
    if (self.SendRequest('accounts/login/', self.generateSignature(json.dumps(data)), True)):
  File "F:\djcode\socialfotosearch\InstagramAPI.py", line 475, in generateSignature
    return 'ig_sig_key_version=' + self.SIG_KEY_VERSION + '&signed_body=' + hmac.new(self.IG_SIG_KEY.encode('utf-8'), data.encode('utf-8'), hashlib.sha256).hexdigest() + '.' + urllib.quote(data)
AttributeError: module 'urllib' has no attribute 'quote'`

**Comment by ranman034** [comment]
@ahmdrz I fixed my previous error by changing line 475 in InstagramAPI.py to urllib.parse.quote

I am getting another error now though.

`Request return 400 error!
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    InstagramAPI.tagFeed("cat") # get media list by tag #cat
  File "F:\djcode\picsearch\InstagramAPI.py", line 314, in tagFeed
    userFeed = self.SendRequest('feed/tag/'+ str(tag) +'/?rank_token=' + str(self.rank_token) + '&ranked_content=true&')
AttributeError: 'InstagramAPI' object has no attribute 'rank_token'`

**Comment by ahmdrz** [comment]
@ranman034  if you logged in successfully ([see this](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI.py#L69)) the rank_token will initialize...

So I think you did not login successfully !

**Comment by ahmdrz** [comment]
@ranman034 Thank you , line 475 have the problem.
Can you make PR ?

And ...

I run program and the result is :

test.py :

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from InstagramAPI import InstagramAPI

InstagramAPI = InstagramAPI("username", "password")
InstagramAPI.login() # login
print(InstagramAPI.LastJson)
```

result :

```
Login succuss!

{'new_stories': [], 'continuation_token': 0, 'subscription': None, 'status': 'ok', 'friend_request_stories': [], 'counts': {'photos_of_you': 0, 'requests': 0, 'relationships': 0}, 'old_stories': []}

```

**Comment by BatuhanKahraman** [comment]
torlakfaruk dostum proje dosyasına atmak derken python içinde bir klasörmü bu ? sen diğer hesaplar için kullanıyorum dedin. Bir batch file ilemi çözüyorsun bunu. Yani klasik command line üzerinde InstagramApi olarak exe miş gibi hareket ediyormu bu kod. Ben vb ve asp classic programcısıyım 20 yıldır uğraşıyorum ve yapamadığım bir şey yok. Eğer bunun mantığını çözersem gui mantığında bir şey yapacağım . Seninlede paylaşırım destek olursan. Teşekkürler... Skype adresim batuhankahraman(et)hotmail.com

**Comment by BatuhanKahraman** [comment]
return 'ig_sig_key_version=' + self.SIG_KEY_VERSION + '&signed_body=' + hmac
.new(self.IG_SIG_KEY.encode('utf-8'), data.encode('utf-8'), hashlib.sha256).hexd
igest() + '.' + urllib.quote(data)
AttributeError: module 'urllib' has no attribute 'quote'

Error found ? how to solve ?

**Comment by ahmdrz** [comment]
https://github.com/LevPasha/Instagram-API-python/pull/39

**Comment by BatuhanKahraman** [comment]
thnks ahmdrz
