### ISSUE TITLE
How to get media_id\url for uploaded photo ?

### ISSUE THREAD

**Issue by dE1l** [LevPasha/Instagram-API-python#36]
I'm succesfuly upload new photo ti my instagram.
I have upload_id(genereted on this API), but **how to get the url** or some native Instagram identifier for my uploaded file?
In documentation for php version i find information:
> Get info of an uploaded media
> $i->mediaInfo($mediaId);

But mediaId != upload_id

How i can get media_id\url for uploaded photo ?

I think that .uploadPhoto() must return this id. I can help and make pull request for this. But my exploring  of .uploadPhoto() response did'n help me...

**Comment by ahmdrz** [comment]
After photo uploaded , in the response from Instagram , we have something like this :

```
{
  "status":"ok",
  "media": { media object } ,
  "upload_id" : "2683192367879012"
}
```

in media , you can found media_id

**Comment by dE1l** [comment]
I thought too, but no.. in respons i see only '{"status": "ok", "upload_id": "1476866696517"}'
https://yadi.sk/i/OdU6Fagsx8XQw

**Comment by ahmdrz** [comment]
Yes, media JSON only fill after [this](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI.py#L133) , Are you sure about configure ?

**Comment by dE1l** [comment]
oh, guys, it's really some magic) Very big thanks. We made my day! It's a really very cool API project!
I am with you and ready to help any way I can!

I'm adding pull request now for it. And then it return 
```
{
  "status":"ok",
  "media": { media object } ,
  "upload_id" : "2683192367879012"
}
```

**Comment by ahmdrz** [comment]
Yes , This is very cool. Good Luck bro
