### ISSUE TITLE
"No module named InstagramAPI"

### ISSUE THREAD

**Issue by HarryRowolt** [LevPasha/Instagram-API-python#366]
Hey everyone, 
I see that some had  similar problem but all the solutions didn't work for me. 
When I run e.g. live_broadcast.py from the examples folder I get this: 

Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\Instagram-API-python\examples\live_broadcast.py", line 8, in <module>
    from InstagramAPI import InstagramAPI
ImportError: No module named InstagramAPI

Any Idea? The only thing I want from this API is the RTMP streamkey to stream live on Instagram. 
Thank you all!!

**Comment by jensenhuangyankai** [comment]
Uninstall the pip version. It's not the latest build. Download and install via the github itself. Use python setup.py install in the command line to install the module. Also the streaming part doesnt really work as referenced from #362

**Comment by jensenhuangyankai** [comment]
Also switch to python 3. There should be no reason to start a new project running python2
