### ISSUE TITLE
Your version of Instagram is out of date. Please upgrade your app to log in to Instagram.

### ISSUE THREAD

**Issue by lucasexe** [LevPasha/Instagram-API-python#375]
Hello guys, 
today i tried log in my account but the instagram returned:
`{"message": "Your version of Instagram is out of date. Please upgrade your app to log in to Instagram.", "status": "fail", "error_type": "needs_upgrade"}`

Did anyone else had this problem today?

Other infos:
`const IG_VERSION = '27.0.0.7.97';
const VERSION_CODE = '84433655';
const IG_SIG_KEY = '109513c04303341a7daf27bb41b268e633b30dcc65a3fe14503f743176113869';`

`User-Agent: Instagram 27.0.0.7.97 Android (23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; pt_BR)`

**Comment by aRandomStranger** [comment]
@lucasexe - how did you solve this issue?

**Comment by lucasexe** [comment]
@aRandomStranger 
I started rewrite the Requests using as base a api in PHP:
https://github.com/mgp25/Instagram-API

This API (PHP) is updated more frequently and I figured out that it has different constants (example: IG_SIG_KEY, Android version, etc.). So I'm analyzing it to get the newest protocol used by the Instagram.

I don't finish it yet, but it has already worked for log in.
