### ISSUE TITLE
Error at run - SOLVED

### ISSUE THREAD

**Issue by maxdid** [LevPasha/Instagram-API-python#38]
I copyed the files in a directory and when I run test.py I receive the following error:

`C:\Users\xxxx\Desktop\progetti\Instagram_api>python test.py
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    InstagramAPI.login() # login
  File "C:\Users\xxxx\Desktop\progetti\Instagram_api\InstagramAPI.py", line 66, in login
    if (self.SendRequest('accounts/login/', self.generateSignature(json.dumps(data)), True)):
  File "C:\Users\xxxx\Desktop\progetti\Instagram_api\InstagramAPI.py", line 475, in generateSignature
    return 'ig_sig_key_version=' + self.SIG_KEY_VERSION + '&signed_body=' + hmac.new(self.IG_SIG_KEY.encode('utf-8'), data.encode('utf-8'), hashlib.sha256).hexdig
est() + '.' + urllib.quote(data)
AttributeError: 'module' object has no attribute 'quote'
`
Could someone help me to solve it?
Thanks

**Comment by ahmdrz** [comment]
#35 @ranman034  said...

change to `urllib.parse.quote`

I commit it in new PR , waiting for @LevPasha

**Comment by maxdid** [comment]
Ok, error bypassed but my output is now 

`C:\Users\xxxx\Desktop\progetti\Instagram_api>python test.py
Request return 429 error!
Login success!
C:\Users\xxxx\Desktop\progetti\Instagram_api>`

**Comment by ahmdrz** [comment]
Add `print("Debugging ... " + endpoint)` to sendRequest
change sendRequest to ...
```python
   def SendRequest(self, endpoint, post = None, login = False):
        print("Debugging ... " + endpoint)
        if (not self.isLoggedIn and not login):
            raise Exception("Not logged in!\n")
            return;

        self.s.headers.update ({'Connection' : 'close',
                                'Accept' : '*/*',
                                'Content-type' : 'application/x-www-form-urlencoded; charset=UTF-8',
                                'Cookie2' : '$Version=1',
                                'Accept-Language' : 'en-US',
                                'User-Agent' : self.USER_AGENT})

        if (post != None): # POST
            response = self.s.post(self.API_URL + endpoint, data=post) # , verify=False
        else: # GET
            response = self.s.get(self.API_URL + endpoint) # , verify=False

        if response.status_code == 200:
            self.LastResponse = response
            self.LastJson = json.loads(response.text)
            return True
        else:
            print ("Request return " + str(response.status_code) + " error!")
            # for debugging
            try:
                self.LastResponse = response
                self.LastJson = json.loads(response.text)
            except:
                pass
            return False
```

And tell us what happend

**Comment by maxdid** [comment]
C:\Users\xxxx\Desktop\progetti\Instagram_api>python test.py
Debugging ... si/fetch_headers/?challenge_type=signup&guid=xxxxxxxxxxxxxxxxxxxxxxx
Debugging ... accounts/login/
Debugging ... qe/sync/
Debugging ... friendships/autocomplete_user_list/
Request return 429 error!
Debugging ... feed/timeline/
Debugging ... direct_v2/inbox/?
Debugging ... news/inbox/?
Login success!

Debugging ... feed/tag/SF/?rank_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxx&ranked_content=true&
Debugging ... media/1364216379796068040/like/
Debugging ... friendships/366022912/followers/?max_id=&ig_sig_key_version=4&rank_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

C:\Users\xxxx\Desktop\progetti\Instagram_api>


I masked my token

**Comment by ahmdrz** [comment]
Perfect ,  Nice work

Ok , Now we now problem is `autoCompleteUserList`

This code is a port of android Instagram version and works similarly with it.

But I think `autoCompleteUserList` is not very important and I think it we comment [this](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI.py#L73) line we can skip request 429

**Comment by maxdid** [comment]
Ok I didn't received any error.
But how can obtain my json file saved in the actual directory?

**Comment by ahmdrz** [comment]
>Do you think that removing the call to autoCompleteUserList is a safe way? 

Honestly , when I used this library , I didn't get any errors ,
After a while , I wrote my library for Golang and I didn't use `autoCompleteUserList` and it's working !

I think `autoCompleteUserList` is for android UI , Instagram UX or something like this and we don't need it anymore. And also I think if we remove `autoCompleteUserList` some features will not working...

I think ! I did not try it. :smile:

>But how can obtain my json file saved in the actual directory? 

I can't understand , can you explain more clearly ?

Do you want to save json result ?

**Comment by maxdid** [comment]
Ok I'll try without it ;)
Yes, in the directory of this project there is a file "response_example.json"
I thought to save my json output...

Thanks again

**Comment by ahmdrz** [comment]
There are no lines that mean result will write in `response_example.json` in InstagramAPI.py

If you want you can see : [this line](https://github.com/ahmdrz/instagram-statistics/blob/master/main.py#L93)

Note : **Don't forget to keep it safety ! for example , I don't want users to see my followers and other things because my Instagram is private. Use AES and base64 to keep it safety***

**Comment by maxdid** [comment]
Yes I mean a way to write my json file or txt file to post elaborate the content

**Comment by ahmdrz** [comment]
Did you see 
```python
with open('followers.json', 'w') as outfile:
    json.dump(followers, outfile)
```
?
Isn't enough?
If you have idea pls tell me too , thanks.

**Comment by maxdid** [comment]
You help has been precious for me. Thanks a lot and I'll keep this updated

**Comment by ahmdrz** [comment]
Good luck bro

**Comment by Ronaldomata34** [comment]
can you help? i don't know why i'm getting this problem:  
line 613, in SendRequest
    raise Exception("Not logged in!\n")
Exception: Not logged in!
