### ISSUE TITLE
Will this function work in the next release? What is the technical details of this function?

### ISSUE THREAD

**Issue by mark-vypyrailo** [LevPasha/Instagram-API-python#392]
https://github.com/LevPasha/Instagram-API-python/blob/cf0fe1d0167d153b0fc6c9be56e265e653c3da7a/InstagramAPI/InstagramAPI.py#L814

**Comment by Seriusam** [comment]
I assume it was left from an older version of Instagram-API when someone was porting. There is a comment in the function that notes the lines between 1470-1485, which do not exist right now. It is probably a feature that is removed.

**Comment by mark-vypyrailo** [comment]
OK, thanks.
