### ISSUE TITLE
rank_token

### ISSUE THREAD

**Issue by mieburungdara** [LevPasha/Instagram-API-python#4]
hi levpaha
i got an error like this 

rojects/InstagramAPI/.last_tmp.py" && exit   <
Request return 400 error!
Traceback (most recent call last):
  File "/storage/sdcard1/com.hipipal.qpyplus/projects/projects/InstagramAPI/.last_tmp.py", line 485, in <module>
    InstagramAPI.tagFeed("cat") # get media list by tag #cat
  File "/storage/sdcard1/com.hipipal.qpyplus/projects/projects/InstagramAPI/.last_tmp.py", line 261, in tagFeed
    userFeed = self.SendRequest('feed/tag/'+ str(tag) +'/?rank_token=' + str(self.rank_token) + '&ranked_content=true&')
AttributeError: InstagramAPI instance has no attribute 'rank_token'
1|u0_a227@hwCHM-H:/ $

i use your code without change

**Comment by velvetflower** [comment]
Same error.

**Comment by buzzo123** [comment]
try commented the last rows of InstagramAPI.py where there is the example of use

**Comment by mieburungdara** [comment]
how to solve this error?

**Comment by timbilino** [comment]
same error. How to solve?

**Comment by LevPasha** [comment]
@mieburungdara answer to @timbilino

**Comment by mieburungdara** [comment]
@levpasha its long ago bro, i dont remember it again :(

**Comment by Xigocloud** [comment]
I have got the same error. Can someone help me pls? @LevPasha @mieburungdara
