### ISSUE TITLE
Don't use this "API"

### ISSUE THREAD

**Issue by RaihanStark** [LevPasha/Instagram-API-python#410]
This will stole your username and password to their server and they use it (your password) as "follower bot". You will following random people that you don't know.

Tips:
If you already use this "API".  change password now :)

**Comment by anisayari** [comment]
Humm... I used this API for a long time and I never detected any problems. :)

**Comment by intothevoid** [comment]
@RaihanStark This API is open source. Care to share what part of the code is stealing our username and password?
