### ISSUE TITLE
NEEDS UPDATE. This doesn't work at the moment.

### ISSUE THREAD

**Issue by CoderzNation** [LevPasha/Instagram-API-python#413]
Says the app needs to be updated... This is what the JSON dump stated....

{u'status': u'ok', u'megaphone': {u'generic_megaphone': {u'uuid': u'cf3bda4d504840a183f8ba62da67ac7b', u'dismissible': False, u'title': u'Update Your App to Use Direct', u'buttons': [{u'url': u'https://play.google.com/store/apps/details?id=com.instagram.android', u'text': u'Update', u'style': u'confirm'}], u'button_location': u'bottom', u'action_info': {}, u'button_layout': u'vertical', u'megaphone_version': u'v1', u'message': u'Your Instagram app is out of date. Update it now to use Direct.', u'type': u'deprecate_raven_tray', u'icon': None}}, u'inbox': {}}

**Comment by xmsid** [comment]
I Solved it easily by changing something in the `USER_AGENT` variable at line 45.
it starts with `Instagram 10.26.0 Android` (notice the version number which is probably old) and changed the version number to `50.0.0.6.119` which is quite new, I didn't change the whole variable to `50.0.0.6.119` i just changed the version number.
each time you get that error you can just change the version number with the latest version for instagram(android).

**Comment by alvestobias** [comment]
how do I do this change?

**Comment by gregjotau** [comment]
> how do I do this change?

![image](https://user-images.githubusercontent.com/13047497/46244349-f1664400-c3dd-11e8-9e24-35bc4308bec6.png)

**Comment by gregjotau** [comment]
I can confirm that changing the user agent variable solves the problem, see above image
