### ISSUE TITLE
Changing "Uploaded image isn't in the right format" to error

### ISSUE THREAD

**Issue by ChrisBuetti** [LevPasha/Instagram-API-python#418]
Sometimes when I attempt to upload a photo, and it isn't in the right format, no picture is posted and "Uploaded image isn't in the right format".

```
Request return 400 error!
{u'status': u'fail', u'message': u"Uploaded image isn't in the right format"}
```
The issue is, this prints as a string and not an error. So if the photo isn't in the right format, nothing happens and the script continues to run. I want to change this from a print to an error so my script can pick up on it and try another photo or resize the photo and try again. However, this string isn't explicitly stated in the [api code](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI/InstagramAPI.py), so it must be returned directly from instagram and printed. Anyone have any idea how I can change this from a "print" to an "error"?

Thanks!

**Comment by ABeltramo** [comment]
You should check for LastJson after every API call in order to be able to detect error. 
```python
API = InstagramAPI(user, pass)
if API.LastResponse.status_code != 200:
   # error during last call
elif 'status' in API.LastJson and API.LastJson['status'] == 'fail':
  # error during last call. You should see API.LastJson['message']
```

**Comment by ChrisBuetti** [comment]
@ABeltramo you're a hero, thank you!
