### ISSUE TITLE
Instagram API Platform changes (will this api death by July 31?)

### ISSUE THREAD

**Issue by DLAcoding** [LevPasha/Instagram-API-python#424]
Hi everybody,

I just read [here](https://www.instagram.com/developer/) that Instagram is going to disable some features by the end of July as:

- Follower List – to get the list of followers and followed-by users

- Relationships – to follow and unfollow accounts on behalf of a user;

These are some of the features which I more use with this package. Does any knows if this announced changes will affect to this API?

More info [here](https://elfsight.com/blog/2018/02/instagram-graph-api-changes/)

**Comment by 404-brain** [comment]
Read the README.md

**Comment by DLAcoding** [comment]
Hi 404, I already did It. I am still learning Python so in the readme I dont find the answer to my question. Please, if you know the answer share It with me. Thanks

**Comment by screencrack** [comment]
I'm trying to figure this out too

**Comment by xmsid** [comment]
Those changes are for the public API, this lib is using the private API used in the mobile app so it won't get affected by those changes

**Comment by DLAcoding** [comment]
@xmsid Thank you so much for your help!!
