### ISSUE TITLE
Error when using proxy the caption text not shown

### ISSUE THREAD

**Issue by deounix** [LevPasha/Instagram-API-python#434]
When I'm using proxy and trying to post photo the photo shown but the caption text not shown.
When I'm using local ip address every thing work 100%

**Comment by ChrisBuetti** [comment]
Can you provide code? @deounix

**Comment by deounix** [comment]
@ChrisBuetti yes

with proxy:

```
from InstagramAPI import InstagramAPI

InstagramAPI = InstagramAPI("xxxx", "xxxx")
InstagramAPI.setProxy("https://user:user@1.1.1.1:1111")
InstagramAPI.login()  # login

InstagramAPI.uploadPhoto("1.jpg", caption="hello world")
```

the photo show but the caption not!

with out proxy every thing work 100%

```
from InstagramAPI import InstagramAPI

InstagramAPI = InstagramAPI("xxxx", "xxxx")
InstagramAPI.login()  # login

InstagramAPI.uploadPhoto("1.jpg", caption="hello world")

```

I also edit the : InstagramAPI.py in line : 87

I made it just https cuz instagram always use https : https://www.instagram.com

```
            proxies = {'http': proxy}
            self.s.proxies.update(proxies)
```

nothing work with proxy option.

**Comment by ChrisBuetti** [comment]
@deounix interesting. I don't see a problem. I use proxy and post and the caption works. I don't use "https://" infront of my password, i just provide user:pass@ip:port

**Comment by deounix** [comment]
@ChrisBuetti yeah both should work fine.

```
import requests
s = requests.Session()
s.get("https://httpbin.org/ip", proxies={"https": "185.53.152.x:41258"}, timeout=8).text

s.get("https://httpbin.org/ip", proxies={"https": "https://185.53.152.x:41258"}, timeout=8).text

# both return the same ip address
```

did u have any good website that give paid proxy

**Comment by ChrisBuetti** [comment]
@deounix I use proxy6.net

Also, I was having a problem with captions and I realized it wasn't showing the caption because I had too many hashtags. Doesn't seem like that is your problem but just wanted to throw that out there.
