### ISSUE TITLE
getTotalUsers

### ISSUE THREAD

**Issue by mseita** [LevPasha/Instagram-API-python#44]
I'm trying to retrieve all users from a specific user id, but after some time I get the "Request return 403 error"
Does anyone know why and how to fix it?

**Comment by ahmdrz** [comment]
May I see your code ?

**Comment by mseita** [comment]
sure, just promise not to laugh loud haha
i'm still crawling on python and these robots

followers = InstagramAPI.getTotalFollowers('370019846')

it seems that every time the sub tries to send the request it gets this
error.... but not for all userids some get blank messages in the middle of
various error messages


2016-10-25 9:41 GMT-02:00 Ahmadreza Zibaei <notifications@github.com>:

**Comment by JamesRGallagher** [comment]
Was this issue solved?

**Comment by mseita** [comment]
Yes, but any thoughts on how to go beyond 200 followers?

Em 11/12/2016 04:44, "James Gallagher" <notifications@github.com> escreveu:

**Comment by nosleepbeats** [comment]
How did you get it to work?  I receive a 403 error when I run the following code:

temp = InstagramAPI.getTotalFollowers('2284384863')
for f in temp['user']:
    print(f['pk'])

**Comment by aReaSa** [comment]
@nosleepbeats how did you run it?

for f in temp['user']: print(f['pk'])


Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    for f in temp['user']: print(f['pk'])
TypeError: list indices must be integers, not str
