### ISSUE TITLE
I can contribute!

### ISSUE THREAD

**Issue by ABeltramo** [LevPasha/Instagram-API-python#441]
@LevPasha I'm using this project daily and it's disappointing that this project it's going cold. You have a lot of pull requests open and ready to be deployed, and a lot of garbage Issues open.
I know it's difficult to trust someone on the web but I have a little bit of free time and I would love to contribute to your amazing project.
If you want help I can be a contributor!

**Comment by ChrisBuetti** [comment]
Willing to vouch for  @ABeltramo . He has helped me with countless questions with this repository.

**Comment by Spyder-exe** [comment]
(probably off-topic) but I have a dumb issue, and I feel bad opening an issue for it, anyway you could help me @ABeltramo ?

**Comment by ABeltramo** [comment]
@Spyder-exe it's better to open a new issue. You can close it whenever you wan't it.
