### ISSUE TITLE
Hide errors?

### ISSUE THREAD

**Issue by Spyder-exe** [LevPasha/Instagram-API-python#442]
hey there, I'd like to hide the erros that often araise on the API.

Example, a known (and yet unfixed) bug is the following:
`Request return 429 error!
{'message': 'Please wait a few minutes before you try again.', 'status': 'fail'}
Login success!`

In which when logging in, you'll get a too pmany request error even when no requests have yet been made.
Or for example when an incorrect password is entered:
`Request return 400 error!
{'message': 'The password you entered is incorrect. Please try again.', 'invalid_credentials': True, 'error_title': 'Incorrect password for ertert', 'buttons': [{'title': 'Try Again', 'action': 'dismiss'}], 'status': 'fail', 'error_type': 'bad_password'}`

I tried using `except Exception:` and `try:` fonctions but neither seem to work.

Is there anyway to replace or hide these error messages? So that instead you can get a clean "you've entered the wrong password" message?

**Comment by ABeltramo** [comment]
If you want to completely remove messages you should remove all of the print() inside the main python file.
If you want to manage messages differently you should check for API.LastResponse after every requests to Instagram.

**Comment by Spyder-exe** [comment]
so the only way I'd have to hide the error messages from the prompt would be to make a fork and edit them out myself?

**Comment by ABeltramo** [comment]
Yes not the best error handling out there..
There are not many print out there. You could just subclass InstagramAPI and rewrite the bad methods.
You could make a proper error handling with exceptions or using other methods and submit a pull request!

**Comment by Spyder-exe** [comment]
Alright thank you! Sadly I do not currently have the level or the time to make a proper error handling.

**[CLOSED]**
