### ISSUE TITLE
get most recent media of tag feed

### ISSUE THREAD

**Issue by maxpierini** [LevPasha/Instagram-API-python#45]
Hi, I'm tryin to get the most recent media of a tag feed by adding a new function (is it possible to do it with `tagFeed`?):

```
def recentTagFeed(self, tag):
    userFeed = self.SendRequest('tags/' + tag + '/media/recent')
    print json.dumps(userFeed, indent=4, sort_keys=True) #to check the response
    return userFeed
```

But it returns `false` so maybe it's not the right request url. Could you help? Thank you :D

**Comment by ahmdrz** [comment]
>But it returns false so maybe it's not the right request url. Could you help? Thank you :D

Try it :
`return LastJson` [see](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI.py#L527)
