### ISSUE TITLE
Unable to import InstagramAPI

### ISSUE THREAD

**Issue by impactcolor** [LevPasha/Instagram-API-python#454]
Thank you for doing this great script.
I have a problem when running it I get an error on import InstagramAPI.

File "/root/python-scripts/Instagram-API-python/InstagramAPI/__init__.py", line 1, in <module>
    from .InstagramAPI import *
  File "/root/python-scripts/Instagram-API-python/InstagramAPI/InstagramAPI.py", line 24, in <module>

I've ran pip install -r requirements.txt
Also pip install InstagramApi

**Comment by impactcolor** [comment]
Sorry hadn't seen this:  Duplicate: https://github.com/LevPasha/Instagram-API-python/issues/159

**Comment by impactcolor** [comment]
I have tried all the other responses given here but I'm still getting this error:
File "getup-run.py", line 3, in <module>
    from InstagramAPI import InstagramAPI
  File "/root/Instagram-API-python/InstagramAPI/__init__.py", line 1, in <module>
    from .InstagramAPI import *

Here is what I've tried:
python 2.7 and python3 
1. Recommended on here was to clone the repository.
2. Run python setup.py install.
3. Then attempt to load and I still get the error.

I've created a virtualenv so everything would be isolated.
1. I closed repository.
2. I ran pip install -r requirements.txt
3. Ran pip install InstagramApi
Same error

I've also tried different solutions given on issue #159, #161, #203

**Comment by bachirelkhoury** [comment]
Try this in a completely new setup/folder:
```
$ mkdir myApp && cd myApp
$ python3 -m venv venv
$ venv/bin/pip install InstagramAPI
```
Create an instaapi.py file in that directory:
```
from InstagramAPI import InstagramAPI

api = InstagramAPI('username', 'password')
api.login()

here = os.path.dirname(os.path.realpath(__file__))
photo_path = os.path.join(here, 'my-image.jpg')
api.uploadPhoto(photo_path, caption='Hello instagram #itworks')

```
Then from the command line execute:
```$ venv/bin/python instaapi.py```

let me know if this works for you.

**Comment by impactcolor** [comment]
@bachirelkhoury worked for me.
