### ISSUE TITLE
Following any people

### ISSUE THREAD

**Issue by emirmuminoglu** [LevPasha/Instagram-API-python#457]
How can i follow any people with this API?????

**Comment by Morplson** [comment]
I'm sorry, but how do I follow a person now?
I know that you have to get the user IDs, but how do I send the follow requst via the api?
What is the methods name?

**Comment by HenrySaba** [comment]
I hope you figured it out already! If not, then simply use the "follow(self, userId)" function which can be found in the InstagramAPI python file. All API functions can be found there.
