### ISSUE TITLE
Download user media

### ISSUE THREAD

**Issue by erfanh3h** [LevPasha/Instagram-API-python#464]
Hi.
How can get a user medias and save it on device?

**Comment by finaldzn** [comment]
get the user feed, the link of the image/video is in the json file, then download it

**Comment by erfanh3h** [comment]
how can get download link from json file?

**Comment by nik0x01** [comment]
How to get user feed?

**Comment by finaldzn** [comment]
You get the json with api.getLastJson()

Then you can use beautifulsoup or anything like that to fetch the link (maybe print the json then look with a text editor where the link is)

**Comment by erfanh3h** [comment]
there is no api.getLastJson()
its api.LastJson.get() , but what most put on Parentheses?

**Comment by erfanh3h** [comment]
I found answer
use :
_ = api.getSelfUserFeed(maxid=next_max_id,minTimestamp=0)
        followers.extend(api.LastJson.get('items',[]))
for it
