### ISSUE TITLE
getFollowingRecentActivity pagination

### ISSUE THREAD

**Issue by haliliceylan** [LevPasha/Instagram-API-python#468]
Hi Guys,

how can i get other pages of [getFollowingRecentActivity](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI/InstagramAPI.py#L663)

**Comment by haliliceylan** [comment]
I found seven functions which have `maxid` attribute:
- [getUserFeed](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI/InstagramAPI.py#L723)
- [getSelfUserFeed](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI/InstagramAPI.py#L728)
- [getHashtagFeed](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI/InstagramAPI.py#L731)
- [getLocationFeed](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI/InstagramAPI.py#L738)
- [getUserFollowings](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI/InstagramAPI.py#L745)
- [getUserFollowers](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI/InstagramAPI.py#L760)
- [getLikedMedia](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI/InstagramAPI.py#L871)

**Comment by haliliceylan** [comment]
is there anybody ?

**Comment by Filip3Dev** [comment]
I don't know if endpoint of getFollowingRecentActivity() accept a pagination

**Comment by haliliceylan** [comment]
it must accept.
