### ISSUE TITLE
Pagination issue

### ISSUE THREAD

**Issue by kiralore** [LevPasha/Instagram-API-python#48]
There is a pagination issue what when I run getTotalFollowers(self,usernameId) for a account who follows over 200 accounts, the next_max_id is presented like meaningless string 'AQAxY9x9YGaTvWvrsNkEPYFnl34DznBAAQ4RM43CxM9fgMVmAmDqgkFmOt0F6r6rWiMpPbX4tXMjSPcEcaRgg3BK4FsCSNMBcGOk-axWi7HEMhWw3twxc1Hq8jB-lOwdH3I'.
This makes the temp["big_list"] always be true that cannot break the loop. Any idea how to fix it?

**Comment by h-2-0** [comment]
Take a look [here](https://github.com/LevPasha/Instagram-API-python/pull/60)

**Comment by h-2-0** [comment]
@kiralore
