### ISSUE TITLE
About the function of getTotalFollowings

### ISSUE THREAD

**Issue by Gouper** [LevPasha/Instagram-API-python#49]
I have some problems on this.I used the function of getTotalFollowings,and i run it , it is always recycled ,it can not output the correct answer.Then i run it in debug,in the result,the next_max_id is a string,and i don't know what it is.So,I would like to know in this function getTotalFollowings,what is the next_max_id and the big_list means?And how can i get the correct answer?

**Comment by ahmdrz** [comment]
big_list tell us that we have more than 200 followers and next_max_id works as a pagination.
For example :
If I have 400 followes , At first step before a run getfollowers i have to set `next_max_id=""` and after i send request i will get next_max_id and big_list = true and 200 of my followers . big_list means I have more than 200 followers and if I want more I have to send next_max_id to get page 2. After that I will get all of my 400 followers.

> sorry for my english

**Comment by Gouper** [comment]
Thanks for your reply.Now , my question is that i can't get the correct answer when i use the getTotalFollowings function.
For example:
When i want to get an user's followings,he has 350 followings.I just can get the first 200 followings,and the function will loop out the output the first 200 followings .I don't know how to solve this problem.I just added the print,this is my code.Can you give me some advice?
Thank you very much!
My English is not well.I'm sorry.


    def getTotalFollowings(self, usernameId):
        index1 = 1
        followers = []
        next_max_id = ''
        while 1:
            self.getUserFollowings(usernameId, next_max_id)
            temp = self.LastJson

            for item in temp["users"]:
                followers.append(item)
                print(item)
                print(index1)
                index1 = index1 + 1


            if temp["big_list"] == False:
                return followers
            next_max_id = temp["next_max_id"]
            print (next_max_id)

**Comment by ahmdrz** [comment]
I use this code :
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from InstagramAPI import InstagramAPI

InstagramAPI = InstagramAPI("###", "###")
InstagramAPI.login() # login
print(len(InstagramAPI.getTotalSelfFollowers()))
```

And the result is : 

```
Request return 429 error!
Login success!

280
```

So i think it's ok ! But I found a bug in #50

**Comment by Gouper** [comment]
I tried your method. It is just suitable for self.When i want to get my followers,I can get the correct answer.But when i want to get others followers, i can't get the correct answer.It will loop the first 200 followings.You can try it.

**Comment by Instaerror** [comment]
anyone got this working properly?

**Comment by isdito** [comment]
Hello.

You solve your problem?? I have the same problem. I can not take more than 198 followers

**Comment by Gouper** [comment]
@isdito I have solved the problem.I found the code in another place.In instargramAPI.py, I use this code can get the correct answer.You can try it.
 
    def getUserFollowings(self, usernameId, maxid=''):
        if maxid == '':
            return self.SendRequest('friendships/' + str(usernameId) + '/following/?rank_token=' + self.rank_token)
        else:
            return self.SendRequest(
            'friendships/' + str(usernameId) + '/following/?rank_token=' + self.rank_token + '&max_id=' + str(maxid))
        



    def getUserFollowers(self, usernameId, maxid=''):
        if maxid == '':
            return self.SendRequest('friendships/' + str(usernameId) + '/followers/?rank_token=' + self.rank_token)
        else:
            return self.SendRequest(
            'friendships/' + str(usernameId) + '/followers/?rank_token=' + self.rank_token + '&max_id=' + str(maxid))

**Comment by isdito** [comment]
hello @Gouper But this functions I must to put inside the Api of InstagramAPI.py rewirte them

"maxid" is the last pk Of the previous consultation?

**Comment by isdito** [comment]
Ahh ok I resolve!!!

When you call 

seguidos= InstagramAPI.getTotalFollowings(my_id) this function call internally getUserFollowers() to complete all. In the var seguidos you have a array of list, you not have to call LastJson. This works for me

```
followings_count = InstagramAPI.getSelfUsernameInfo()
my_id = InstagramAPI.LastJson['user']['pk']
followings_count=InstagramAPI.LastJson['user']['following_count']
seguidos= InstagramAPI.getTotalFollowings(my_id)

for x in seguidos:
	print x
```
