### ISSUE TITLE
Output each func 

### ISSUE THREAD

**Issue by velvetflower** [LevPasha/Instagram-API-python#5]
@LevPasha я немного не понял принцип работы с выводом каждой функции.
При попытке, допустим, вывести список фолловеров - всегда возвращает значение true.
Да и любую функцию в апи какую только не пробовал - на выходе true/false.
Я что-то делаю не так?

**Comment by mieburungdara** [comment]
@velvetflower english please, i want to know what you say too? :)

**Comment by LevPasha** [comment]
@velvetflower привет. Функция возвращает bool, true если код ответа был 200, false иначе. Результат последнего запроса храниться в `InstagramAPI.LastJson # last response JSON`. Возможно это неправильная логика - пока руки не дошли изменить.

@mieburungdara this is Russian business, we talk about our bears, vodka and balaika ))
