### ISSUE TITLE
Is there any way to check if I liked a post?

### ISSUE THREAD

**Issue by ivenkrish** [LevPasha/Instagram-API-python#500]
I have the link or id or url of a post which is liked by many people. Is there any way to check if I have liked that post or not without retrieving all "likers" and going through that list?

**Comment by ddog1038** [comment]
Yeah what I did for this was using the API.getLikedMedia() function and it will return the ids to all the posts you have liked and put that in a list and then compare the picture id you are about to like to the ones you already liked and if there's a match then you already liked it else then you haven't

**Comment by ivenkrish** [comment]
So that API will return EVERYTHING that I have liked so far in the entire time I have been on Instagram?

**Comment by ddog1038** [comment]
Yes Exactly run and print the function you will see exactly what I am talking about After that just simply put all those media ids in a list and compare it to the post your curious about

**Comment by ivenkrish** [comment]
I tried it today, it only returns 21 items. How many times should I call this api to get everything I have ever liked?

**Comment by ddog1038** [comment]
`
gloabal liked_ids
liked_ids = [] 

```
def getliked():
	print("Alright im starting to look at your likes(this will take a second)")
	liked_data = []
	global liked_ids
	API.getLikedMedia()  
	API.LastJson
	##########################################
	next_max_id = True
	while next_max_id:
	    # first iteration hack
	    if next_max_id is True:
	        next_max_id = ''
	    _ = API.getLikedMedia(maxid=next_max_id)
	    liked_data.extend(API.LastJson.get('items', []))
	    next_max_id = API.LastJson.get('next_max_id', '')
	########################################################
	unique_likes = {
	    f['id']: f
	    for f in liked_data
	}
	#print(len(unique_likes))
	for l in unique_likes:
		liked_ids.append(l)
	print("All liked media successfully stored")
	print("les take a lil 10-30second nap")
	timetonap = random.randint(10,30)
	time.sleep(timetonap)
```
`
This is what I use for the bot I made I hope it helps and now whenever you like something new just append that to the global list

**Comment by ivenkrish** [comment]
Ok I found the solution. Once you have a media's number id, you just have to call `api.mediaInfo(id)`

The json returned will have a 'has_liked' entry which will have a True or False depending on whether you have liked the media or not.
