### ISSUE TITLE
400 error while like

### ISSUE THREAD

**Issue by goodillla** [LevPasha/Instagram-API-python#55]
I've just tested like function couple of days before and then it worked.
But now when I can get my timelinefeed - like function doesn't work itself.

Does it look like a ban? Some other functions works ok.
Tried to make sleep(10) between every request - didn't help.
Like from official apps also works.
Even InstaTool free liking works.

Could you help how to fix?

**Comment by LevPasha** [comment]
Wait some time. Look like ban.

**Comment by goodillla** [comment]
@LevPasha , but could you please explain - why this function works from other applications and doesn't work only from the API?
If it's ban - how long should it last? It's already lasts for about a week.
Is there smth else to check? Sorrfy for my urgency, it's too boring just to wait...
