### ISSUE TITLE
Benchtesting Follow

### ISSUE THREAD

**Issue by Instaerror** [LevPasha/Instagram-API-python#56]
After a while Instagram blocks follow with no error, unfollow is fine, you can still follow people on a browser or other service/bot just not on this api or an android phone for a while with no message. Can anyone else confirm?

**Comment by goodillla** [comment]
I have similar with like function, but I see "Request return 400 error".

**Comment by LevPasha** [comment]
@Instaerror i will update IG_SIG_KEY - test after this.

**Comment by Instaerror** [comment]
OK, will test when done!

**Comment by Instaerror** [comment]
@LevPasha I tried a brand new ig_sig_key and problem still persists.

**Comment by goodillla** [comment]
I have the same, but I also can't follow from phone, only from browser it works.

**Comment by LevPasha** [comment]
@Instaerror try other account.

**Comment by Instaerror** [comment]
Used fresh IG_SIG_KEY a brand new account and new AWS server (fresh ip) and does the same. mgp25 does the same, seems to be a big flaw in this concept.

**Comment by LevPasha** [comment]
@Instaerror what is your rates?

**Comment by Haydardi** [comment]
@goodillla yo, did you fix this problem buddy? I'm having the same thing

**Comment by goodillla** [comment]
@Haydardi , no, after some time problem dissapeared

**Comment by Instaerror** [comment]
It's still there, cash to anyone who can fix 👍
