### ISSUE TITLE
Fail to import moviepy. Need only for Video upload.

### ISSUE THREAD

**Issue by hmmthn** [LevPasha/Instagram-API-python#567]
Fail to import moviepy. Need only for Video upload.
Request return 400 error!
{u'status': u'fail', u'error_title': u'Incorrect Username', u'error_type': u'invalid_user', u'buttons': [{u'action': u'dismiss', u'title': u'Try Again'}], u'message': u"The username you entered doesn't appear to belong to an account. Please check your username and try again.", u'invalid_credentials': True}
Can't login!

**Comment by stilManiac** [comment]
Hello! Looks like you need to update moviepy. Use `pip install --upgrade moviepy`.

**Comment by mojI1380** [comment]
> Hello! Looks like you need to update moviepy. Use `pip install --upgrade moviepy`.
Thanks A Bunch
