### ISSUE TITLE
AttributeError: 'InstagramAPI' object has no attribute 'rank_token'

### ISSUE THREAD

**Issue by 01egi4** [LevPasha/Instagram-API-python#57]
How do I fix this problem?

**Comment by LevPasha** [comment]
@01egi4 how do you get this problem?

**Comment by grouchycoterie** [comment]
I think that this comes from not authenticating correctly. I got the same error and realized my logins were not correct.

**Comment by ezzat001** [comment]
This error comes with 429 error here 
i guess i got banned on the ip 
however i can still use the accounts on other devices but can't on the api so what is it?
