### ISSUE TITLE
Should getUsernameInfo(self, usernameId) return True?

### ISSUE THREAD

**Issue by phbprogramming** [LevPasha/Instagram-API-python#575]
If I misunderstand the purpose of this, is there a function to get a user description?

**Comment by BBowdon00** [comment]
I've been trying to do this, but to no avail. getProfileData(self) also returns true... something doesn't work correctly I think. I will be working on it over the next few days to think if I can figure out a solution.

**Comment by phbprogramming** [comment]
I've figured it out. The result is stored in API.LastJson. Just read that after making the call.

**Comment by BBowdon00** [comment]
Great thank you!
