### ISSUE TITLE
Get post/followers/following count of private account

### ISSUE THREAD

**Issue by paunzz** [LevPasha/Instagram-API-python#582]
How can I get the post/followers/following count of any user without getting the "Not authorized to view user" error?
getTotalUserFeed, getTotalFollowers and getTotalFollowings doesn't work if the profile is private, so getting len of it is impossible...
Any ideas?

**Comment by BBowdon00** [comment]
Impossible. Instagram is set up to not allow access of private accounts unless you follow them
