### ISSUE TITLE
 4 import InstagramApi ModuleNotFoundError: No module named 'InstagramApi'

### ISSUE THREAD

**Issue by sapna2092** [LevPasha/Instagram-API-python#586]
import InstagramApi

ModuleNotFoundError: No module named 'InstagramApi'

**Comment by Glarity** [comment]
`from InstagramAPI import InstagramAPI`

This is what you need.

**Comment by sapna2092** [comment]
> from InstagramAPI import InstagramAPI
> This is what you need.



---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-db22778df052> in <module>
      1 from InstagramAPI import InstagramAPI
----> 2 import pandas as pd
      3 from pandas.io.json import json_normalize
      4 import moviepy
      5 import numpy

~\Anaconda3\lib\site-packages\pandas\__init__.py in <module>
     17 if missing_dependencies:
     18     raise ImportError(
---> 19         "Missing required dependencies {0}".format(missing_dependencies))
     20 del hard_dependencies, dependency, missing_dependencies
     21 

ImportError: Missing required dependencies ['numpy']


cn you help me in this too?

**Comment by Glarity** [comment]
I believe that you do not have the package numpy installed.

**Comment by sapna2092** [comment]
> I believe that you do not have the package numpy installed.

its already installed 
I have updated the pandas also...
it shows requirement already satisfied

**Comment by sapna2092** [comment]
error resolved...….thanku soo much dear :)

**Comment by Glarity** [comment]
Can you close the issue? 👍
