### ISSUE TITLE
Recent Error 500 after login

### ISSUE THREAD

**Issue by KarlClinckspoor** [LevPasha/Instagram-API-python#593]
I had a script I made and it was running fine until about one or two days ago. Now, when I try to log in, I get an error 500 message. The password is correct, and I tried with two accounts. I can access and browse Instagram just fine in Firefox.

I simplified the problem down to this code. Any idea what could be causing a server error?

```python
from InstagramAPI import InstagramAPI

api = InstagramAPI('username', 'password')
api.login()
```

I am running the code in Python 3.7.1 and Windows 10.

**Comment by Glarity** [comment]
Instagram has been having lots of problems today.
https://downdetector.com/status/instagram

**Comment by KarlClinckspoor** [comment]
Thank you. It was indeed temporary. It's working now. I just thought it weird to be able to access Instagram from the Browser, but not through this script.
