### ISSUE TITLE
sig_key

### ISSUE THREAD

**Issue by mieburungdara** [LevPasha/Instagram-API-python#6]
whether we should replace sig_key?

**Comment by LevPasha** [comment]
@mieburungdara hi! sig_key need to signatere requests. In one time all user have same sig_key. If you can get new sig_key - please do it and write to me. I have no Android device, to do it myself.

https://github.com/mgp25/Instagram-API/wiki/Technical-information

Now Instagram on Android have 8.2 version, and some things don't work with current sig_key.
