### ISSUE TITLE
JSON ERRORS

### ISSUE THREAD

**Issue by ins3c7** [LevPasha/Instagram-API-python#63]
In [41]: data
Out[41]: 
{'_csrftoken': 'Fr28712TwAe34F85mu6vEF07mBp28xB9Y',
 'device_id': 'android-eb1494027953ef65',
 'guid': <module 'uuid' from '/usr/lib/python2.7/uuid.pyc'>,
 'login_attempt_count': '0',
 'password': '****',
 'phone_id': 'b372ec45-8540-68fc-b97b-c486899120ca',
 'username': '****'}

.....

In [48]: json.dumps(data)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-48-38fe964b7500> in <module>()
----> 1 json.dumps(data)

/usr/lib/python2.7/json/__init__.pyc in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, encoding, default, sort_keys, **kw)
    242         cls is None and indent is None and separators is None and
    243         encoding == 'utf-8' and default is None and not sort_keys and not kw):
--> 244         return _default_encoder.encode(obj)
    245     if cls is None:
    246         cls = JSONEncoder

/usr/lib/python2.7/json/encoder.pyc in encode(self, o)
    205         # exceptions aren't as detailed.  The list call should be roughly
    206         # equivalent to the PySequence_Fast that ''.join() would do.
--> 207         chunks = self.iterencode(o, _one_shot=True)
    208         if not isinstance(chunks, (list, tuple)):
    209             chunks = list(chunks)

/usr/lib/python2.7/json/encoder.pyc in iterencode(self, o, _one_shot)
    268                 self.key_separator, self.item_separator, self.sort_keys,
    269                 self.skipkeys, _one_shot)
--> 270         return _iterencode(o, 0)
    271 
    272 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

/usr/lib/python2.7/json/encoder.pyc in default(self, o)
    182 
    183         """
--> 184         raise TypeError(repr(o) + " is not JSON serializable")
    185 
    186     def encode(self, o):

TypeError: <module 'uuid' from '/usr/lib/python2.7/uuid.pyc'> is not JSON serializable

**Comment by Instaerror** [comment]
Use python version 3.4 or above!
