### ISSUE TITLE
Inbox endpoint deprecated

### ISSUE THREAD

**Issue by TheBigBen1** [LevPasha/Instagram-API-python#635]
The endpoint for getv2Inbox() is depreccated (returns 404):
'direct_v2/inbox/?'

Does anybody know how to find out the new endpoint? 
My first hunch was to look in the instagram APK, but had no luck until now, 

Thanks!

**Comment by navanchauhan** [comment]
It hasn't been deprecated, you just need to specify a user-agent. Add this to your code before running 

```api.USER_AGENT = 'Instagram 10.34.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)'```

Also, please close this issue if this solves it

**Comment by TheBigBen1** [comment]
Perfect, will try it out. Thank you!
