### ISSUE TITLE
what is the 429 error?

### ISSUE THREAD

**Issue by tiagokotryk** [LevPasha/Instagram-API-python#64]
![image](https://cloud.githubusercontent.com/assets/23374963/20814914/cd10fd0e-b802-11e6-9cbe-e42ba7fd8895.png)

**Comment by Instaerror** [comment]
Too many requests!

**Comment by BjornvdLaan** [comment]
I get this after doing one request.

**Comment by Instaerror** [comment]
And your code is?

**Comment by tiagokotryk** [comment]
@Instaerror which one should I edit? ![image](https://cloud.githubusercontent.com/assets/23374963/20871132/2ab022c8-ba79-11e6-8e16-1a79e43a6084.png)

**Comment by GitHub314** [comment]
have the same problem after one request i'm sure i don't exit rate limits as described below
https://www.instagram.com/developer/limits/
