### ISSUE TITLE
unable to follow. Request return 400 error!

### ISSUE THREAD

**Issue by MxDkl** [LevPasha/Instagram-API-python#646]
Request return 400 error!
{'feedback_ignore_label': 'OK', 'feedback_url': 'repute/report_problem/instagram_follow_users/', 'feedback_message': 'This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.', 'message': 'feedback_required', 'feedback_action': 'report_problem', 'spam': True, 'feedback_appeal_label': 'Tell us', 'status': 'fail', 'feedback_title': 'Action Blocked'}

`from InstagramAPI import InstagramAPI
import time

api = InstagramAPI("user", "pass")
api.login()

counter = 0

api.getUserFollowers(2374691999, maxid='')
#print(api.LastJson)
for x in api.LastJson['users']:
                if counter > 200:
                        break
                else:
                        print(x['pk'])
                        api.follow(x['pk'])
                        counter += 1
                        time.sleep(1)
`

**Comment by steam3d** [comment]
You was banned from instagram. Try does not use the account with bot 1-2 days. I think instagram made something, cuz my account also banned.

**Comment by MxDkl** [comment]
Yah I figured. I switched to a different machine and now it works fine. But I had to make it wait longer than 1 second before each follow. Now I make it wait for 15-30 seconds.
