### ISSUE TITLE
HELP WANTED : I want to write direct_message

### ISSUE THREAD

**Issue by ahmdrz** [LevPasha/Instagram-API-python#65]
https://github.com/mgp25/Instagram-API/blob/9e2dd8dfe1326691f418a25e108dba2dfa3faf06/src/http/HttpInterface.php#L682

Hi , 
I want to write direct_message , but I receive 500 status code ,
Note : I wrote my code in Golang , I don't know PHP enough , So I think if anyone wrote this code in python , I will reading it more easier.

> sorry for my bad english

**Comment by artemdumanov** [comment]
Did you send messages by instagram api? @ahmdrz

**Comment by ahmdrz** [comment]
Yes I wrote `DirectMessage` in my `goinsta` package.
