### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by linuscool2** [LevPasha/Instagram-API-python#67]
I get this when I run "§ sudo python3 test.py"

> Traceback (most recent call last):
>   File "test.py", line 4, in <module>
>     from InstagramAPI import InstagramAPI
>   File "/home/pi/Instagram-API-python/InstagramAPI.py", line 3, in <module>
>     import requests
> ImportError: No module named 'requests'

I have installed python3 and requests_toolbelt. But the moviepy fail so when I run "§ sudo python test.py" I get another error that says "AttributeError: 'module' object has no attribute 'parse'"

Please help :(

**Comment by dsouzarc** [comment]
Hey, it seems like you're having quite a few issues, mainly with installing libraries and running it using Python 2.x.

I address and fix those issues in [this Pull Request](https://github.com/LevPasha/Instagram-API-python/pull/71/files)

but until it gets merged, try running my forked version of it: [https://github.com/dsouzarc/Instagram-API-python](https://github.com/dsouzarc/Instagram-API-python)
