### ISSUE TITLE
Username ID

### ISSUE THREAD

**Issue by nosleepbeats** [LevPasha/Instagram-API-python#69]
Is there a way to search a username and return the username ID?

**Comment by Instaerror** [comment]
getUsernameInfo

**Comment by LevPasha** [comment]
if (self.SendRequest('accounts/login/', self.generateSignature(json.dumps(data)), True)):
                    self.isLoggedIn = True
                    self.username_id = self.LastJson["logged_in_user"]["pk"]

**Comment by nosleepbeats** [comment]
I don't follow.  This looks like it would return the username id for whoever logged in.  I want to search any username (I.E. champagnepapi) and get the username ID for that user (14455831).

**Comment by Instaerror** [comment]
Function for that is

searchUsername
