### ISSUE TITLE
InstagramAPI.tagFeed is getting Top Posts instead of Most Recent, is it correct?

### ISSUE THREAD

**Issue by rudnetto** [LevPasha/Instagram-API-python#70]
Is tagFeed() behaving correctly when returning Top Posts instead of Most Recent media? If so, what method should I use to retrieve most recent media?

**Comment by tarun7singh** [comment]
@LevPasha @rudnetto were you able to solve this issue?
I also want to get recent posts of a tag.

**Comment by LevPasha** [comment]
https://github.com/LevPasha/Instagram-API-python/issues/127

**Comment by LevPasha** [comment]
Same, close this one.
