### ISSUE TITLE
upload photos can't upload

### ISSUE THREAD

**Issue by tiago-aguiar** [LevPasha/Instagram-API-python#705]
The IG stopped to received upload photo with this method.. always returns false and response 400

**Comment by MxDkl** [comment]
> The IG stopped to received upload photo with this method.. always returns false and response 400

i get the same error

**Comment by THConer** [comment]
I'm getting the same error as well. I tried the code that we provided in the examples and made some very minor adjustments to it and still got this error.

**Comment by galactic16** [comment]
I have the error as well, it's not limited to this project because it seems like people using the PHP API also encountered this issue : https://github.com/mgp25/Instagram-API/issues/2972
Bottom line nobody knows what's going on and it may be just a temporary bug from Instagram...

**Comment by ad-1** [comment]
Any update on this? Having the same problem today with this api. Also tried [intapy-cli] which has a similar issue

((https://github.com/instagrambot/instapy-cli/issues/75))

**Comment by THConer** [comment]
@ad-1 I'm still getting the same issue as well and it seems like everybody else is getting this error as well. I think instagram changed their private API.

**Comment by tiago-aguiar** [comment]
Someone knows how to check api private url? I mean, uses a proxy or something else? This can helps to find a solution (eventually)

**Comment by morteza220** [comment]
it is ok for me today and work with it.....

**Comment by fernand0** [comment]
It seems to be working again now.

**Comment by Takenobou** [comment]
Yep, it works fine now.

**Comment by tiago-aguiar** [comment]
Yes, it works again.

**Comment by janpiter** [comment]
Anybody experiencing this issue again? I get the same error since yesterday.

**Comment by Takenobou** [comment]
> Anybody experiencing this issue again? I get the same error since yesterday.

I'm getting the same issue, I don't think it's something that can be fixed on our side. I think we just have to wait it out again. 

It took around 4 days last time so it's not too long.

**Comment by mbiparva** [comment]
I have the same issue too. It seems the API cannot login into the Instagram account so then the call to upload fails.

**Comment by fernand0** [comment]
By the way, I'm not sure about which values return the Python API when using uploadPhoto. It woud be nice to have some error message but I'm not being able to test this in an adequate way, so:
- Which is the expected value when everything is fine?
- Which is the expected return value when posting fails?

**Comment by Noorquacker** [comment]
It's definitely clear that the `uploadPhoto` function returns true on a successful post, iirc from testing out the API. Now it returns false every time the function is called, and `LastResponse` shows 200 while `LastJson` shows profile info. I don't know if `LastJson` is any different from when it was working, but it's definitely clear that `uploadPhoto` shouldn't be returning false if it's working correctly.

**Comment by FourKube** [comment]
Has anyone found a fix for this yet? thanks.

**Comment by mbiparva** [comment]
> Has anyone found a fix for this yet? thanks.

I don't think it is going to be fixed soon. The thing is the legacy API is going to be deprecated in the favour of the Graph API. 

Check this out:

https://stackoverflow.com/questions/55813629/instagram-api-deprecation-2020

**Comment by boldrack** [comment]
Anyone ? This is still not working. uploadPhoto returns False and LastJson returns the user profile information .

**Comment by Noorquacker** [comment]
The main problem is that Instagram probably changed their protocol
internally and we can't figure it out. They use SSL Pinning, making it a
pain to try and steal network activity.
I've been waiting months for this to get updated, too. I tried
disassembling Instagram's app myself and found where the public key is
located, but I don't know how to change it and reassemble it.

**Comment by MxDkl** [comment]
Does anyone think the problem will ever get resolved? I heard some
disappointing news about new IG policies.
https://github.com/LevPasha/Instagram-API-python/issues/739
