### ISSUE TITLE
Attempting to login causes error 400, challenge_required

### ISSUE THREAD

**Issue by raccoondude** [LevPasha/Instagram-API-python#706]
Code: 

`
from InstagramAPI import InstagramAPI

username = input("Username: ")
password = input("Password: ")
debug = False

photo = "owo.png"
caption = "I did it, this was uploaded via terminal!"

owo = InstagramAPI(username, password)
owo.login()
 `

error (json format):
`{'message': 'challenge_required', 'challenge': {'url': 'https://i.instagram.com/challenge/7486640407/ltZRGanAP6/', 'api_path': '/challenge/7486640407/ltZRGanAP6/', 'hide_webview_header': True, 'lock': True, 'logout': False, 'native_flow': True}, 'status': 'fail', 'error_type': 'checkpoint_challenge_required'}`
`
It will cause a alert on the app, if I accept it, it will return the error

I have no idea how to fix this.

**Comment by Quiec** [comment]
i have this error

**Comment by SomebodyOnceToldMeI** [comment]
Just had this too, tried to login from vps (before never had problems with challenge after one confirmation), solved a challenge few times and it didn't help. Then logged in from my pc (my phone from which I'm solving the challenges is connected to the same network my pc is), it sent a challenge again, but after solving it from my phone again it started to work (even on vps). Not sure what is caused by. Did you find any reliable solution?

**Comment by raccoondude** [comment]
no

**Comment by tatanfort** [comment]
I had the same issue. I solved it by connecting through my pc until instagram got used to this ip and I don't have to confirm on my phone (or mail) anymore. 
After 5-10 connections you won't need a challenge anymore.

**Comment by raccoondude** [comment]
Thanks, I will test and update later!

**Comment by basti3893** [comment]
I got two accounts. On my private one I don't get any challenge and with the other one (blog) I have issues.  I think I have the same settings for both accounts, also no link to facebook. Do you have any idea why it doesn't work on both?

**Comment by rasamrajas** [comment]
To start the account again or remove the challenge thing just Temporarily Disable Your Account for 2 to 5 hours and it will start working again. I have done that many times

**Comment by sahiltspaceo** [comment]
> Code:
> 
> `
> from InstagramAPI import InstagramAPI
> 
> username = input("Username: ")
> password = input("Password: ")
> debug = False
> 
> photo = "owo.png"
> caption = "I did it, this was uploaded via terminal!"
> 
> owo = InstagramAPI(username, password)
> owo.login()
> `
> 
> error (json format):
> `{'message': 'challenge_required', 'challenge': {'url': 'https://i.instagram.com/challenge/7486640407/ltZRGanAP6/', 'api_path': '/challenge/7486640407/ltZRGanAP6/', 'hide_webview_header': True, 'lock': True, 'logout': False, 'native_flow': True}, 'status': 'fail', 'error_type': 'checkpoint_challenge_required'}`
> `
> It will cause a alert on the app, if I accept it, it will return the error
> 
> I have no idea how to fix this.

Try this.
login with your username and password in IG web and run your code in parallel. 

Modify the code for login like this:

api.login()
time.sleep(15)    ### Within these 15 seconds,open your web and authorize 
api.login()

I stopped getting any challenge errors after I approved once with this method.

**Comment by sahiltspaceo** [comment]
> Code:
> 
> `
> from InstagramAPI import InstagramAPI
> 
> username = input("Username: ")
> password = input("Password: ")
> debug = False
> 
> photo = "owo.png"
> caption = "I did it, this was uploaded via terminal!"
> 
> owo = InstagramAPI(username, password)
> owo.login()
> `
> 
> error (json format):
> `{'message': 'challenge_required', 'challenge': {'url': 'https://i.instagram.com/challenge/7486640407/ltZRGanAP6/', 'api_path': '/challenge/7486640407/ltZRGanAP6/', 'hide_webview_header': True, 'lock': True, 'logout': False, 'native_flow': True}, 'status': 'fail', 'error_type': 'checkpoint_challenge_required'}`
> `
> It will cause a alert on the app, if I accept it, it will return the error
> 
> I have no idea how to fix this.

a workaround. 
https://github.com/LevPasha/Instagram-API-python/issues/706#issuecomment-560248053

**Comment by orest1114** [comment]
Fix
#718
