### ISSUE TITLE
Exception: Not logged in!

### ISSUE THREAD

**Issue by lollotaz** [LevPasha/Instagram-API-python#713]
Hi, i'm using these API in the last couple of week without any problems just to scrape some images from two different accounts of mine. 

Now i got this issue where instagram keep asking me to verify every single login attempt that i make (by clicking on the app "it was me") and this procedure prevent me to login properly because instagram doesn't save my choice. The weird fact is that i got this problem just for one of my two accounts.

Any  suggestion? Thanks

**Comment by T4O2M0** [comment]
I'm having this same problem but it only started after I got my account locked. It is now unlocked though and does this every single time I attempt to login.

**Comment by Yeppman** [comment]
I'm guessing Instagram is blocking your IP

**Comment by lollotaz** [comment]
Solved changing the USER_AGENT
