### ISSUE TITLE
Bot keeps logging me out of my phone

### ISSUE THREAD

**Issue by 179skr** [LevPasha/Instagram-API-python#72]
Am i the only one who keeps getting logged out on my phone when using the bot?

**Comment by Instaerror** [comment]
What is your USER_AGENT?

**Comment by 179skr** [comment]
USER_AGENT = 'Instagram 9.2.0 Android ({android_version}/{android_release}; 320dpi; 720x1280; {manufacturer}; {model}; armani; qcom; en_US)'.format(**DEVICE_SETTINTS)

**Comment by Instaerror** [comment]
try;

    USER_AGENT = 'Instagram 10.1.0 Android ({android_version}/{android_release}; 320dpi; 720x1280; {manufacturer}; {model}; armani; qcom; en_US)'.format(**DEVICE_SETTINTS)
    IG_SIG_KEY = 'f6bcd0639ea3d279c10d4ffe49bd59f1f5045cf73c62fc33c9e45766f6cf6c63'
    EXPERIMENTS = 'ig_android_reg_login_btn_active_state,ig_android_ci_opt_in_at_reg,ig_android_one_click_in_old_flow,ig_android_merge_fb_and_ci_friends_page,ig_android_non_fb_sso,ig_android_mandatory_full_name,ig_android_reg_enable_login_password_btn,ig_android_reg_phone_email_active_state,ig_android_analytics_data_loss,ig_fbns_blocked,ig_android_contact_point_triage,ig_android_reg_next_btn_active_state,ig_android_prefill_phone_number,ig_android_show_fb_social_context_in_nux,ig_android_one_tap_login_upsell,ig_fbns_push,ig_android_phoneid_sync_interval'

**Comment by h-2-0** [comment]
@Instaerror 
Could you please care to explain why do that? I'd like to learn as much as possible about the login process (especially when Instagram blocks it) . Thanks!
