### ISSUE TITLE
API Endpoint for saved photos

### ISSUE THREAD

**Issue by ducdigital** [LevPasha/Instagram-API-python#77]
As of today there's a new feed for saved media on instagram app.

Is there anybody has already got the API endpoint for this feed? My best guess is that it must be almost the same endpoint as self liked feed (`/feed/liked/`)

Thank you!

**Comment by krishven** [comment]
Anyone knows how to get saved photos of a user?
Is there any API endpoint pre existing for saved photos?

**Comment by RPSPandora** [comment]
do you mean save all photo by username? you can easily use instaLooter

*Best Regard,*
*Randhi Pratama Putra*
081 313 9000 99
0878 5345 6600

**Comment by krishven** [comment]
No, Instagram introduced a new feature where a user can privately save photos. I'm trying to use that and get a user's privately saved pics.

**Comment by ducdigital** [comment]
@krishven @RPSPandora the endpoint is `feed/saved/`

You have to be logged in to be able to access this. And yes it's all photos saved by that logged in user.

**Comment by krishven** [comment]
Thanks

**Comment by krishven** [comment]
I tried with the following code

```
from InstagramAPI import InstagramAPI

InstagramAPI = InstagramAPI("<user>", "<pass>")
InstagramAPI.login() # login
InstagramAPI.SendRequest('feed/saved/')
```

I get "Request return 404 error!" Any idea why?

**Comment by totoquarantedeux** [comment]
I'm also very interested in this feature, that's actually the only API I'm looking for right now, I have a growing list of saved pictures/videos but no way to access it from the computer.
I will try to make it work on my side, and keep you updated if I have any positive result.

**Comment by totoquarantedeux** [comment]
@krishven this works fine for me, did you make sure that the login worked?

**Comment by rcc26** [comment]
Hello @ducdigital , is this really working for you? After a successful login with broadened scope I tried the following uris but it always fails

https://api.instagram.com/v1/users/self/media/like?access_token=MY_ACCESS_TOKEN **this one works (liked)**

https://api.instagram.com/v1/users/self/saved?access_token=MY_ACCESS_TOKEN (fails 404)

https://api.instagram.com/v1/users/self/media/saved?access_token=MY_ACCESS_TOKEN (fails 404)

https://api.instagram.com/v1/feed/saved?access_token=MY_ACCESS_TOKEN (fails 404)

Which url would be the correct one?
Let me know, ty

**Comment by rcc26** [comment]
Paging @totoquarantedeux on my previous reply to this topic: https://github.com/LevPasha/Instagram-API-python/issues/77#issuecomment-314472889

**Comment by rcc26** [comment]
Damn, that's harsh @LevPasha

**Comment by LevPasha** [comment]
@rcc26 hey, I close all old issue. If you think this is actual one - i will reopen it.
