### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by nosleepbeats** [LevPasha/Instagram-API-python#78]
I receive a 403 error when running the code below.  Have you seen this?

InstagramAPI = InstagramAPI("xxxxxxx", "xxxxxxxxx")
InstagramAPI.login() # login

temp = InstagramAPI.getTotalFollowers('2284384863')
for f in temp['user']:
    print(f['pk'])

**Comment by LevPasha** [comment]
@nosleepbeats you solve this?

**Comment by nosleepbeats** [comment]
No this still is an issue...

**Comment by LevPasha** [comment]
@nosleepbeats check for 2 factor authentication
