### ISSUE TITLE
does anyone know how to upload a picture?

### ISSUE THREAD

**Issue by jorgetorresny** [LevPasha/Instagram-API-python#80]
Using the api does anyone know how to use or upload a pic. Im happy to create a sample code for every single function.? Anyone ?

**Comment by ahmdrz** [comment]
[See this function](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI.py#L122)

**Comment by targify** [comment]
@ahmdrz , I think @jorgetorresny is trying to find an implementation example.  Like him, I've looked at this function for ages, but getting nowhere without some sort of example.

**Comment by ahmdrz** [comment]
@targify @jorgetorresny Sorry , my english is bad and I didn't read your issue carefully.

Example is simple 

```python
from InstagramAPI import InstagramAPI

InstagramAPI = InstagramAPI("#", "#")
InstagramAPI.login()
InstagramAPI.uploadPhoto("test.jpg")
InstagramAPI.logout()
```

```bash
$ ls | grep .jpg
test.jpg
```

`uploadPhoto` function is very easy and thanks to @ethanliou

If you want to put caption under your uploaded photo use `uploadPhoto("test.jpg","my caption")`

In line [143](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI.py#L143) If everything was OK , `configure` will called in `uploadPhoto`

In `configure` function you can change cropped image in line [251](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI.py#L251)

And also you can use [Filter Type](https://github.com/ahmdrz/goinsta/blob/master/goinsta.go#L570) in my library, I didn't sure about it (:neutral_face:) but you can try it !

**Comment by targify** [comment]
Great advice thanks @ahmdrz :-)  Will give it a go.
