### ISSUE TITLE
"Install the dependencies" documentation issue

### ISSUE THREAD

**Issue by tim-durrant** [LevPasha/Instagram-API-python#81]
Step 3 in README is confusing:

> 3. Install the dependencies
> https://github.com/LevPasha/Instagram-API-python.git

What's the actual command to install the dependencies?

**Comment by dsouzarc** [comment]
Just addressed it in this PR: [https://github.com/LevPasha/Instagram-API-python/pull/82](https://github.com/LevPasha/Instagram-API-python/pull/82)
