### ISSUE TITLE
Like media by location

### ISSUE THREAD

**Issue by drhtcl** [LevPasha/Instagram-API-python#83]
Hi. I'm regular user from the non-API bot but I'm having difficulties in set the bot to like media by location. This is my code in test.py:

```
from InstagramAPI import InstagramAPI

InstagramAPI = InstagramAPI("xxx", "xxx")
InstagramAPI.login() # login
media_id = InstagramAPI.LastJson
InstagramAPI.getLocationFeed("213255513") 
InstagramAPI.like(media_id["ranked_items"][0]["pk"]) # like first media
```
This is what it returns:
```
Login success!

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    InstagramAPI.like(media_id["ranked_items"][0]["pk"]) # like first media
KeyError: 'ranked_items'
```
It seems that the bot can't read the ranked_items from the Json file?

**Comment by ThomasMW** [comment]
Using 
´´´media_ id["ranked_items"][0]["pk"]´´´
is correct, and get's the most recent photo tagged with that location.

What probably happened is that you got a 400 status response so the JSON isn't returned.
