### ISSUE TITLE
uploadVideo error

### ISSUE THREAD

**Issue by SeRDaR406** [LevPasha/Instagram-API-python#85]
I have a problem to uploadVideo.I use Python 2.7.13.I can't fixed it! Sorry my bad English.

Here is my problem: 

![error](https://cloud.githubusercontent.com/assets/24946801/21701934/4c7c234c-d3b1-11e6-8689-5f1bc3163a38.png)

Thank you.

**Comment by angelskieglazki** [comment]
This error tell us that "request_size" is float and start and float too.
Maybe later I'll fix it.
