### ISSUE TITLE
error when execute  test.py

### ISSUE THREAD

**Issue by isdito** [LevPasha/Instagram-API-python#86]
Hello give me error test.py

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    InstagramAPI.tagFeed("cat") # get media list by tag #cat
  File "C:\Python27\Instagram-API-python-master\InstagramAPI.py", line 405, in tagFeed
    userFeed = self.SendRequest('feed/tag/'+ str(tag) +'/?rank_token=' + str(self.rank_token) + '&ranked_content=true&')
AttributeError: InstagramAPI instance has no attribute 'rank_token'
>Exit code: 1

```

**Comment by ahmdrz** [comment]
Hi , 
According to (Line 79)[https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI.py#L79] 

Maybe Username or Password is incorrect.

**Comment by isdito** [comment]
Hello.

Thank you. if you dont mind say me this error

Request return 429 error!
Login success!

**Comment by ahmdrz** [comment]
@isdito This is Not Important Problem , you can do what you want.

`Request return 429 error!` is from one of these methods. 
.
```python
                    self.syncFeatures()
                    self.autoCompleteUserList()
                    self.timelineFeed()
                    self.getv2Inbox()
                    self.getRecentActivity()
```

But still you can do what you want.

**Comment by isdito** [comment]
But the test.py not return nothing?

Also I put 

print InstagramAPI.getUserFollowers(media_id["ranked_items"][0]["user"]["pk"]) # get first media owner followers

and return "true" not return a list

I put 

followings_count = InstagramAPI.getSelfUsernameInfo()
print followings_count

and give me true.

My question I will like the list of followers and the list of followings to un follow people that not follow me.

**Comment by ahmdrz** [comment]
The response is in `self.LastJson`
So you have to change your code to :

```python
InstagramAPI.getUserFollowers(media_id["ranked_items"][0]["user"]["pk"]) 
print(InstagramAPI.LastJson)
```

**Comment by isdito** [comment]
Ahmdrz more thank you and if you dont mind.

The instagram structure of childs inside  "ranked_item"  "user"  .... I could find in any place? and functions with vars .tagFeed()

Where is the information of jason element and functions?Sorry my bad english.

**Comment by ahmdrz** [comment]
@isdito I can't understand what you want , Please tell me ...

**Comment by isdito** [comment]
@ahmdrz Thank you first.

The structure of the jason file, media_id["ranked_items"][0]["user"]["pk"] , here is inside ranked_items element 0 inside uer the element pk. I think that this have a structure of data it is posible to see, to understand instagram.

And another thing is the callbacks of InstagramAPI and the vars that need.

**Comment by isdito** [comment]
you put in this page the jason returned to know the path??

**Comment by isdito** [comment]
When I put the jason return to the website give me error

{u'status': u'ok', u'user': {u'usertags_count': 12, u'auto_expand_chaining': False, u'hd_profile_pic_versions': [{u'url': u'http://instagram.fmad3-1.fna.fbcdn.net/t51.2885-19/s320x320/15538399_319400745120183_3213178558713167872_a.jpg', u'width': 320, u'height': 320}], u'following_count': 1715, u'city_id': 271963079548530L, u'public_phone_number': u'654438339', u'has_anonymous_profile_picture': False, u'has_biography_translation': True, u'external_lynx_url': u'http://l.instagram.com/?u=http%3A%2F%2Fwww.video-boda.es%2F&e=ATO4KSthT7HHwv3q6TtaUqoGp4v1NyActUHWPQexuf-Xd9-zKl8W4wNrZf7tOeDXnVU7eGk', u'city_name': u'Valencia', u'can_boost_post': True, u'full_name': u'fotograf\xeda y video de boda', u'page_id': 1470035686591772L, u'address_street': u'calle rio duero 72', u'public_phone_country_code': u'34', u'category': u'Consulting/Business Service', u'is_profile_action_needed': False, u'has_chaining': True, u'media_count': 133, u'zip': u'46184', u'page_name': u'video-boda.es', u'biography': u'Fotograf\xedas \xfanicas, reportajes de boda. v\xeddeos con c\xe1maras de cine.  #fot\xf3grafo #boda #wedding #photographer #feeling #sentimientos', u'latitude': 39.57354, u'pk': 1531580299, u'is_verified': False, u'username': u'video_boda', u'public_email': u'info@video-boda.es', u'is_business': True, u'follower_count': 353, u'include_direct_blacklist_status': True, u'profile_pic_url': u'http://instagram.fmad3-1.fna.fbcdn.net/t51.2885-19/s150x150/15538399_319400745120183_3213178558713167872_a.jpg', u'profile_pic_id': u'1403604419777910067_1531580299', u'can_see_organic_insights': True, u'can_convert_to_business': False, u'is_private': False, u'business_contact_method': u'CALL', u'show_business_conversion_icon': False, u'direct_messaging': u'UNKNOWN', u'geo_media_count': 2, u'show_feed_biz_conversion_icon': False, u'show_conversion_edit_entry': False, u'longitude': -0.51142, u'biz_feature_notice': {}, u'show_insights_terms': False, u'hd_profile_pic_url_info': {u'url': u'http://instagram.fmad3-1.fna.fbcdn.net/t51.2885-19/15538399_319400745120183_3213178558713167872_a.jpg', u'width': 591, u'height': 591}, u'contact_phone_number': u'654438339', u'usertag_review_enabled': False, u'is_needy': False, u'external_url': u'http://www.video-boda.es/'}}

**Comment by ahmdrz** [comment]
Sorry , I just tell put JSON into that site, It's not a JSON ! this is a python type.
So you should convert it to JSON string put it into that site.
Use :
```python
print(json.dumps(InstagramAPI.LastJson))
```

**Comment by isdito** [comment]
OK thank you for all. I think That I understand the structure.

I find this page http://jsonviewer.stack.hu/  not give error and works and yes I see json and I import.. I think that you clarify me a bit to understand what I am doing.

Thank you

**Comment by ahmdrz** [comment]
Your Welcome , Good luck

**Comment by isdito** [comment]
One thing more ;)

Why this works

followings_count = InstagramAPI.getSelfUsernameInfo()
prueba= InstagramAPI.LastJson
print prueba['user']['following_count']

Why this not works
followings_count = InstagramAPI.getSelfUsernameInfo()['user']['following_count']
print followings_count

> File "test.py", line 23, in <module>
>     followings_count = InstagramAPI.getSelfUsernameInfo()['user']['following_count']
> TypeError: 'bool' object has no attribute '__getitem__'

**Comment by ahmdrz** [comment]
```python
followings_count = InstagramAPI.getSelfUsernameInfo()['user']['following_count']
print followings_count
```

because `getSelfUsernameInfo` return `true` or `false` depends on `sendRequest` function.

#### Read the source !

**Comment by isdito** [comment]
This I dont understand this. Where is the resource?

**Comment by ahmdrz** [comment]
https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI.py !! :1st_place_medal:

**Comment by isdito** [comment]
ok the source of the api. Thank you.

**Comment by isdito** [comment]
Hello,

How I could return the next 198 users? because only return me the first 198 users, it is normal.

seguidos= InstagramAPI.getUserFollowers(my_id)
seguidos= InstagramAPI.LastJson['users']
for x in seguidos:
	print x['username'],x['pk']
print followings_count
print seguidos

**Comment by ahmdrz** [comment]
Hi Again

Do something like `getTotalFollowings`

Look at (L664)[https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI.py#L644]

**Comment by isdito** [comment]
Hello 

I can not return all the followings? I dont know what is the problem.

if you dont mind help me.
```
import json

from InstagramAPI import InstagramAPI
InstagramAPI = InstagramAPI("video_boda", "********************")
InstagramAPI.login() # login
followings_count = InstagramAPI.getSelfUsernameInfo()
my_id = InstagramAPI.LastJson['user']['pk']
followings_count=InstagramAPI.LastJson['user']['following_count']
seguidos= InstagramAPI.getTotalFollowings(my_id)
seguidos= InstagramAPI.LastJson['users']
my_followings = 0
while my_followings < followings_count:
	for x in seguidos:
		print x['username'],x['pk']
		my_followings+=1
	try: 
		print "ENTRO------------------------>"
		print x['pk']
		seguidos =  InstagramAPI.getTotalFollowings(my_id,x['pk'])
		seguidos= InstagramAPI.LastJson['users']
		print "SALGO|||||||||"
	except: break
```

**Comment by ahmdrz** [comment]
@isdito @Gouper This is so basicly , You have to do something like `getTotalFollowings`
In `LastJson` we have `next_max_id` or something like this , We need to send this variable to getFollower method and get another 200 followers.
This is something like pagination.

**Comment by isdito** [comment]
Hello,
But I dont know how I realease the call and send this next_max_id
Thank you

**Comment by isdito** [comment]
Ahh ok I resolve!!!

When you call 

seguidos= InstagramAPI.getTotalFollowings(my_id) this function call internally getUserFollowers() to complete all. In the var seguidos you have a array of list, you not have to call LastJson

```
followings_count = InstagramAPI.getSelfUsernameInfo()
my_id = InstagramAPI.LastJson['user']['pk']
followings_count=InstagramAPI.LastJson['user']['following_count']
seguidos= InstagramAPI.getTotalFollowings(my_id)

for x in seguidos:
	print x
```
