### ISSUE TITLE
How to upload photos from folder with interval

### ISSUE THREAD

**Issue by deniscolak** [LevPasha/Instagram-API-python#88]
Hi all, 

I'm just trying to add photos from my library from /upload/pending/ folder. 
And try to upload them from this folder with 4 hour interval.

How should i need to change in the following part,

`
    def uploadPhoto(self, photo, caption = None, upload_id = None):
        if upload_id is None:
            upload_id = str(int(time.time() * 1000))
        data = {
        'upload_id'         : upload_id,
        '_uuid'             : self.uuid,
        '_csrftoken'        : self.token,
        'image_compression' : '{"lib_name":"jt","lib_version":"1.3.0","quality":"87"}',
        'photo'             : ('pending_media_%s.jpg'%upload_id, open(photo, 'rb'), 'application/octet-stream', {'Content-Transfer-Encoding':'binary'})
        }
        m = MultipartEncoder(data, boundary=self.uuid)
        self.s.headers.update ({'X-IG-Capabilities' : '3Q4=',
                                'X-IG-Connection-Type' : 'WIFI',
                                'Cookie2' : '$Version=1',
                                'Accept-Language' : 'en-US',
                                'Accept-Encoding' : 'gzip, deflate',
                                'Content-type': m.content_type,
                                'Connection' : 'close',
                                'User-Agent' : self.USER_AGENT})
        response = self.s.post(self.API_URL + "upload/photo/", data=m.to_string())
        if response.status_code == 200:
            if self.configure(upload_id, photo, caption):
                self.expose()
        return False
`

And also i want to add interval between follow request how can i do that?
Could you please inform us?

**Comment by torlakfaruk** [comment]
ikisi için de time modülünü kullanabilirsiniz. Paylaşımı dilerseniz kullandığınız cihaza göre cronlayabilirsiniz.

**Comment by deniscolak** [comment]
I want to upload the files in specified folder, so that can choose the files themselves. For example first img_01 will be uploaded then img_02 will be uploaded 4 hours later. It will continue like this way.

And could you please share how can i import time module and set the intervals.

I'm newbie on python :D

**Comment by torlakfaruk** [comment]
Paylaşımları yaparken herhangi bir caption eklemek istiyor musun? Yoksa boş metinle mi paylaşacaksın?

**Comment by deniscolak** [comment]
onu da random atayabilirsem muhteşem olur :)

**Comment by LevPasha** [comment]
English plz!

**Comment by RPSPandora** [comment]
how to set i=(i) to filename in directory? sorry for noob question.
i want to upload pics already in folder with pause/delay.
```
for i in xrange(repeat):
  InstagramAPI.uploadPhoto(photo=(i),caption='test',upload_id=None)
  time.sleep(90)
```

**Comment by RPSPandora** [comment]
Hi, i tried creating script for bulk uploading photo in the folder.
1st time coding with python, still ugly, but it works.

check here : [https://github.com/RPSPandora/InstaBulkUpload.py](https://github.com/RPSPandora/InstaBulkUpload.py)
