### ISSUE TITLE
Can I search by location AND hashtags?

### ISSUE THREAD

**Issue by TheScoobyBoy** [LevPasha/Instagram-API-python#92]
Hey man, this is great work. Everything is working but I have a problem. When looking for specific hashtags, obviously all the countries appear that used that hashtag. Is there any way to look for hashtag -> location or location -> hashtag the good way with the API?

Thanks a lot.

**Comment by TheScoobyBoy** [comment]
Hello?

**Comment by LevPasha** [comment]
No.
