### ISSUE TITLE
Could not find a version that satisfies the requirement requirements.txt (from versions: ) No matching distribution found for requirements.txt

### ISSUE THREAD

**Issue by pattrickrice** [LevPasha/Instagram-API-python#93]
Error in console after running the command in setting up:
`pip install requirements.txt`

`Could not find a version that satisfies the requirement requirements.txt (from versions: ) No matching distribution found for requirements.txt`

**Comment by kierrez** [comment]
`pip install -r requirements.txt`
worked for me

**Comment by ThomasMW** [comment]
To install dependencies from a textfile use the '-r' argument.

So: 'pip install -r requirements.txt'

**Comment by LevPasha** [comment]
https://github.com/LevPasha/Instagram-API-python/commit/4d81d4babdad6b4fa902d4b378d5b63e346f8a9b
