### ISSUE TITLE
Request return 400 error!

### ISSUE THREAD

**Issue by say1ted** [LevPasha/Instagram-API-python#95]
```
import InstagramAPI                                                                                                                     
api = InstagramAPI.InstagramAPI('****', '*****')                     
api.login()                                                                       
api.uploadPhoto('/home/***/test.jpg')   
``` 

> Login success!
> 
> Request return 400 error!

Error in 143 line: self.configure(...)
Photo does not upload (

**Comment by miahunsicker** [comment]
You need to reconfigure the photo in photoshop and save it to a jpeg. I found simply changing the extension doesn't work. Mine worked when I resized to 500x500

**Comment by say1ted** [comment]
Thanks! jpeg 500x500 work!

**Comment by LevPasha** [comment]
@miahunsicker thx
